// Code generated by ent, DO NOT EDIT.

package qarecord

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestID, v))
}

// TrajectoryID applies equality check predicate on the "trajectory_id" field. It's identical to TrajectoryIDEQ.
func TrajectoryID(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldTrajectoryID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldGroupID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldAPIKeyID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldAccountID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldPlatform, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldProvider, v))
}

// ChannelType applies equality check predicate on the "channel_type" field. It's identical to ChannelTypeEQ.
func ChannelType(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldChannelType, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestedModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldUpstreamModel, v))
}

// InboundEndpoint applies equality check predicate on the "inbound_endpoint" field. It's identical to InboundEndpointEQ.
func InboundEndpoint(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldInboundEndpoint, v))
}

// UpstreamEndpoint applies equality check predicate on the "upstream_endpoint" field. It's identical to UpstreamEndpointEQ.
func UpstreamEndpoint(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldStatusCode, v))
}

// Success applies equality check predicate on the "success" field. It's identical to SuccessEQ.
func Success(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSuccess, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldDurationMs, v))
}

// FirstTokenMs applies equality check predicate on the "first_token_ms" field. It's identical to FirstTokenMsEQ.
func FirstTokenMs(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldFirstTokenMs, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldStream, v))
}

// ToolCallsPresent applies equality check predicate on the "tool_calls_present" field. It's identical to ToolCallsPresentEQ.
func ToolCallsPresent(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldToolCallsPresent, v))
}

// MultimodalPresent applies equality check predicate on the "multimodal_present" field. It's identical to MultimodalPresentEQ.
func MultimodalPresent(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldMultimodalPresent, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldOutputTokens, v))
}

// CachedTokens applies equality check predicate on the "cached_tokens" field. It's identical to CachedTokensEQ.
func CachedTokens(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldCachedTokens, v))
}

// RequestSha256 applies equality check predicate on the "request_sha256" field. It's identical to RequestSha256EQ.
func RequestSha256(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestSha256, v))
}

// ResponseSha256 applies equality check predicate on the "response_sha256" field. It's identical to ResponseSha256EQ.
func ResponseSha256(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldResponseSha256, v))
}

// BlobURI applies equality check predicate on the "blob_uri" field. It's identical to BlobURIEQ.
func BlobURI(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldBlobURI, v))
}

// RequestBlobURI applies equality check predicate on the "request_blob_uri" field. It's identical to RequestBlobURIEQ.
func RequestBlobURI(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestBlobURI, v))
}

// ResponseBlobURI applies equality check predicate on the "response_blob_uri" field. It's identical to ResponseBlobURIEQ.
func ResponseBlobURI(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldResponseBlobURI, v))
}

// StreamBlobURI applies equality check predicate on the "stream_blob_uri" field. It's identical to StreamBlobURIEQ.
func StreamBlobURI(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldStreamBlobURI, v))
}

// RedactionVersion applies equality check predicate on the "redaction_version" field. It's identical to RedactionVersionEQ.
func RedactionVersion(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRedactionVersion, v))
}

// CaptureStatus applies equality check predicate on the "capture_status" field. It's identical to CaptureStatusEQ.
func CaptureStatus(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldCaptureStatus, v))
}

// SynthSessionID applies equality check predicate on the "synth_session_id" field. It's identical to SynthSessionIDEQ.
func SynthSessionID(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSynthSessionID, v))
}

// SynthRole applies equality check predicate on the "synth_role" field. It's identical to SynthRoleEQ.
func SynthRole(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSynthRole, v))
}

// SynthEngineerLevel applies equality check predicate on the "synth_engineer_level" field. It's identical to SynthEngineerLevelEQ.
func SynthEngineerLevel(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSynthEngineerLevel, v))
}

// DialogSynth applies equality check predicate on the "dialog_synth" field. It's identical to DialogSynthEQ.
func DialogSynth(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldDialogSynth, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldCreatedAt, v))
}

// RetentionUntil applies equality check predicate on the "retention_until" field. It's identical to RetentionUntilEQ.
func RetentionUntil(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRetentionUntil, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldRequestID, v))
}

// TrajectoryIDEQ applies the EQ predicate on the "trajectory_id" field.
func TrajectoryIDEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldTrajectoryID, v))
}

// TrajectoryIDNEQ applies the NEQ predicate on the "trajectory_id" field.
func TrajectoryIDNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldTrajectoryID, v))
}

// TrajectoryIDIn applies the In predicate on the "trajectory_id" field.
func TrajectoryIDIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldTrajectoryID, vs...))
}

// TrajectoryIDNotIn applies the NotIn predicate on the "trajectory_id" field.
func TrajectoryIDNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldTrajectoryID, vs...))
}

// TrajectoryIDGT applies the GT predicate on the "trajectory_id" field.
func TrajectoryIDGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldTrajectoryID, v))
}

// TrajectoryIDGTE applies the GTE predicate on the "trajectory_id" field.
func TrajectoryIDGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldTrajectoryID, v))
}

// TrajectoryIDLT applies the LT predicate on the "trajectory_id" field.
func TrajectoryIDLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldTrajectoryID, v))
}

// TrajectoryIDLTE applies the LTE predicate on the "trajectory_id" field.
func TrajectoryIDLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldTrajectoryID, v))
}

// TrajectoryIDContains applies the Contains predicate on the "trajectory_id" field.
func TrajectoryIDContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldTrajectoryID, v))
}

// TrajectoryIDHasPrefix applies the HasPrefix predicate on the "trajectory_id" field.
func TrajectoryIDHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldTrajectoryID, v))
}

// TrajectoryIDHasSuffix applies the HasSuffix predicate on the "trajectory_id" field.
func TrajectoryIDHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldTrajectoryID, v))
}

// TrajectoryIDIsNil applies the IsNil predicate on the "trajectory_id" field.
func TrajectoryIDIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldTrajectoryID))
}

// TrajectoryIDNotNil applies the NotNil predicate on the "trajectory_id" field.
func TrajectoryIDNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldTrajectoryID))
}

// TrajectoryIDEqualFold applies the EqualFold predicate on the "trajectory_id" field.
func TrajectoryIDEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldTrajectoryID, v))
}

// TrajectoryIDContainsFold applies the ContainsFold predicate on the "trajectory_id" field.
func TrajectoryIDContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldTrajectoryID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldGroupID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldAPIKeyID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldAccountID))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldPlatform, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderIsNil applies the IsNil predicate on the "provider" field.
func ProviderIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldProvider))
}

// ProviderNotNil applies the NotNil predicate on the "provider" field.
func ProviderNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldProvider))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldProvider, v))
}

// ChannelTypeEQ applies the EQ predicate on the "channel_type" field.
func ChannelTypeEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldChannelType, v))
}

// ChannelTypeNEQ applies the NEQ predicate on the "channel_type" field.
func ChannelTypeNEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldChannelType, v))
}

// ChannelTypeIn applies the In predicate on the "channel_type" field.
func ChannelTypeIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldChannelType, vs...))
}

// ChannelTypeNotIn applies the NotIn predicate on the "channel_type" field.
func ChannelTypeNotIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldChannelType, vs...))
}

// ChannelTypeGT applies the GT predicate on the "channel_type" field.
func ChannelTypeGT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldChannelType, v))
}

// ChannelTypeGTE applies the GTE predicate on the "channel_type" field.
func ChannelTypeGTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldChannelType, v))
}

// ChannelTypeLT applies the LT predicate on the "channel_type" field.
func ChannelTypeLT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldChannelType, v))
}

// ChannelTypeLTE applies the LTE predicate on the "channel_type" field.
func ChannelTypeLTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldChannelType, v))
}

// ChannelTypeIsNil applies the IsNil predicate on the "channel_type" field.
func ChannelTypeIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldChannelType))
}

// ChannelTypeNotNil applies the NotNil predicate on the "channel_type" field.
func ChannelTypeNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldChannelType))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldRequestedModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelIsNil applies the IsNil predicate on the "upstream_model" field.
func UpstreamModelIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldUpstreamModel))
}

// UpstreamModelNotNil applies the NotNil predicate on the "upstream_model" field.
func UpstreamModelNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldUpstreamModel))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// InboundEndpointEQ applies the EQ predicate on the "inbound_endpoint" field.
func InboundEndpointEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldInboundEndpoint, v))
}

// InboundEndpointNEQ applies the NEQ predicate on the "inbound_endpoint" field.
func InboundEndpointNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldInboundEndpoint, v))
}

// InboundEndpointIn applies the In predicate on the "inbound_endpoint" field.
func InboundEndpointIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldInboundEndpoint, vs...))
}

// InboundEndpointNotIn applies the NotIn predicate on the "inbound_endpoint" field.
func InboundEndpointNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldInboundEndpoint, vs...))
}

// InboundEndpointGT applies the GT predicate on the "inbound_endpoint" field.
func InboundEndpointGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldInboundEndpoint, v))
}

// InboundEndpointGTE applies the GTE predicate on the "inbound_endpoint" field.
func InboundEndpointGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldInboundEndpoint, v))
}

// InboundEndpointLT applies the LT predicate on the "inbound_endpoint" field.
func InboundEndpointLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldInboundEndpoint, v))
}

// InboundEndpointLTE applies the LTE predicate on the "inbound_endpoint" field.
func InboundEndpointLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldInboundEndpoint, v))
}

// InboundEndpointContains applies the Contains predicate on the "inbound_endpoint" field.
func InboundEndpointContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldInboundEndpoint, v))
}

// InboundEndpointHasPrefix applies the HasPrefix predicate on the "inbound_endpoint" field.
func InboundEndpointHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldInboundEndpoint, v))
}

// InboundEndpointHasSuffix applies the HasSuffix predicate on the "inbound_endpoint" field.
func InboundEndpointHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldInboundEndpoint, v))
}

// InboundEndpointEqualFold applies the EqualFold predicate on the "inbound_endpoint" field.
func InboundEndpointEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldInboundEndpoint, v))
}

// InboundEndpointContainsFold applies the ContainsFold predicate on the "inbound_endpoint" field.
func InboundEndpointContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldInboundEndpoint, v))
}

// UpstreamEndpointEQ applies the EQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointNEQ applies the NEQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIn applies the In predicate on the "upstream_endpoint" field.
func UpstreamEndpointIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointNotIn applies the NotIn predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointGT applies the GT predicate on the "upstream_endpoint" field.
func UpstreamEndpointGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointGTE applies the GTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLT applies the LT predicate on the "upstream_endpoint" field.
func UpstreamEndpointLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLTE applies the LTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContains applies the Contains predicate on the "upstream_endpoint" field.
func UpstreamEndpointContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasPrefix applies the HasPrefix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasSuffix applies the HasSuffix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIsNil applies the IsNil predicate on the "upstream_endpoint" field.
func UpstreamEndpointIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldUpstreamEndpoint))
}

// UpstreamEndpointNotNil applies the NotNil predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldUpstreamEndpoint))
}

// UpstreamEndpointEqualFold applies the EqualFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContainsFold applies the ContainsFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldUpstreamEndpoint, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldStatusCode, v))
}

// SuccessEQ applies the EQ predicate on the "success" field.
func SuccessEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSuccess, v))
}

// SuccessNEQ applies the NEQ predicate on the "success" field.
func SuccessNEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldSuccess, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldDurationMs, v))
}

// FirstTokenMsEQ applies the EQ predicate on the "first_token_ms" field.
func FirstTokenMsEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsNEQ applies the NEQ predicate on the "first_token_ms" field.
func FirstTokenMsNEQ(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsIn applies the In predicate on the "first_token_ms" field.
func FirstTokenMsIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsNotIn applies the NotIn predicate on the "first_token_ms" field.
func FirstTokenMsNotIn(vs ...int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsGT applies the GT predicate on the "first_token_ms" field.
func FirstTokenMsGT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldFirstTokenMs, v))
}

// FirstTokenMsGTE applies the GTE predicate on the "first_token_ms" field.
func FirstTokenMsGTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldFirstTokenMs, v))
}

// FirstTokenMsLT applies the LT predicate on the "first_token_ms" field.
func FirstTokenMsLT(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldFirstTokenMs, v))
}

// FirstTokenMsLTE applies the LTE predicate on the "first_token_ms" field.
func FirstTokenMsLTE(v int64) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldFirstTokenMs, v))
}

// FirstTokenMsIsNil applies the IsNil predicate on the "first_token_ms" field.
func FirstTokenMsIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldFirstTokenMs))
}

// FirstTokenMsNotNil applies the NotNil predicate on the "first_token_ms" field.
func FirstTokenMsNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldFirstTokenMs))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldStream, v))
}

// ToolCallsPresentEQ applies the EQ predicate on the "tool_calls_present" field.
func ToolCallsPresentEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldToolCallsPresent, v))
}

// ToolCallsPresentNEQ applies the NEQ predicate on the "tool_calls_present" field.
func ToolCallsPresentNEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldToolCallsPresent, v))
}

// MultimodalPresentEQ applies the EQ predicate on the "multimodal_present" field.
func MultimodalPresentEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldMultimodalPresent, v))
}

// MultimodalPresentNEQ applies the NEQ predicate on the "multimodal_present" field.
func MultimodalPresentNEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldMultimodalPresent, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldOutputTokens, v))
}

// CachedTokensEQ applies the EQ predicate on the "cached_tokens" field.
func CachedTokensEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldCachedTokens, v))
}

// CachedTokensNEQ applies the NEQ predicate on the "cached_tokens" field.
func CachedTokensNEQ(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldCachedTokens, v))
}

// CachedTokensIn applies the In predicate on the "cached_tokens" field.
func CachedTokensIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldCachedTokens, vs...))
}

// CachedTokensNotIn applies the NotIn predicate on the "cached_tokens" field.
func CachedTokensNotIn(vs ...int) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldCachedTokens, vs...))
}

// CachedTokensGT applies the GT predicate on the "cached_tokens" field.
func CachedTokensGT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldCachedTokens, v))
}

// CachedTokensGTE applies the GTE predicate on the "cached_tokens" field.
func CachedTokensGTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldCachedTokens, v))
}

// CachedTokensLT applies the LT predicate on the "cached_tokens" field.
func CachedTokensLT(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldCachedTokens, v))
}

// CachedTokensLTE applies the LTE predicate on the "cached_tokens" field.
func CachedTokensLTE(v int) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldCachedTokens, v))
}

// RequestSha256EQ applies the EQ predicate on the "request_sha256" field.
func RequestSha256EQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestSha256, v))
}

// RequestSha256NEQ applies the NEQ predicate on the "request_sha256" field.
func RequestSha256NEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldRequestSha256, v))
}

// RequestSha256In applies the In predicate on the "request_sha256" field.
func RequestSha256In(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldRequestSha256, vs...))
}

// RequestSha256NotIn applies the NotIn predicate on the "request_sha256" field.
func RequestSha256NotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldRequestSha256, vs...))
}

// RequestSha256GT applies the GT predicate on the "request_sha256" field.
func RequestSha256GT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldRequestSha256, v))
}

// RequestSha256GTE applies the GTE predicate on the "request_sha256" field.
func RequestSha256GTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldRequestSha256, v))
}

// RequestSha256LT applies the LT predicate on the "request_sha256" field.
func RequestSha256LT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldRequestSha256, v))
}

// RequestSha256LTE applies the LTE predicate on the "request_sha256" field.
func RequestSha256LTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldRequestSha256, v))
}

// RequestSha256Contains applies the Contains predicate on the "request_sha256" field.
func RequestSha256Contains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldRequestSha256, v))
}

// RequestSha256HasPrefix applies the HasPrefix predicate on the "request_sha256" field.
func RequestSha256HasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldRequestSha256, v))
}

// RequestSha256HasSuffix applies the HasSuffix predicate on the "request_sha256" field.
func RequestSha256HasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldRequestSha256, v))
}

// RequestSha256EqualFold applies the EqualFold predicate on the "request_sha256" field.
func RequestSha256EqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldRequestSha256, v))
}

// RequestSha256ContainsFold applies the ContainsFold predicate on the "request_sha256" field.
func RequestSha256ContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldRequestSha256, v))
}

// ResponseSha256EQ applies the EQ predicate on the "response_sha256" field.
func ResponseSha256EQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldResponseSha256, v))
}

// ResponseSha256NEQ applies the NEQ predicate on the "response_sha256" field.
func ResponseSha256NEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldResponseSha256, v))
}

// ResponseSha256In applies the In predicate on the "response_sha256" field.
func ResponseSha256In(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldResponseSha256, vs...))
}

// ResponseSha256NotIn applies the NotIn predicate on the "response_sha256" field.
func ResponseSha256NotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldResponseSha256, vs...))
}

// ResponseSha256GT applies the GT predicate on the "response_sha256" field.
func ResponseSha256GT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldResponseSha256, v))
}

// ResponseSha256GTE applies the GTE predicate on the "response_sha256" field.
func ResponseSha256GTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldResponseSha256, v))
}

// ResponseSha256LT applies the LT predicate on the "response_sha256" field.
func ResponseSha256LT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldResponseSha256, v))
}

// ResponseSha256LTE applies the LTE predicate on the "response_sha256" field.
func ResponseSha256LTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldResponseSha256, v))
}

// ResponseSha256Contains applies the Contains predicate on the "response_sha256" field.
func ResponseSha256Contains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldResponseSha256, v))
}

// ResponseSha256HasPrefix applies the HasPrefix predicate on the "response_sha256" field.
func ResponseSha256HasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldResponseSha256, v))
}

// ResponseSha256HasSuffix applies the HasSuffix predicate on the "response_sha256" field.
func ResponseSha256HasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldResponseSha256, v))
}

// ResponseSha256EqualFold applies the EqualFold predicate on the "response_sha256" field.
func ResponseSha256EqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldResponseSha256, v))
}

// ResponseSha256ContainsFold applies the ContainsFold predicate on the "response_sha256" field.
func ResponseSha256ContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldResponseSha256, v))
}

// BlobURIEQ applies the EQ predicate on the "blob_uri" field.
func BlobURIEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldBlobURI, v))
}

// BlobURINEQ applies the NEQ predicate on the "blob_uri" field.
func BlobURINEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldBlobURI, v))
}

// BlobURIIn applies the In predicate on the "blob_uri" field.
func BlobURIIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldBlobURI, vs...))
}

// BlobURINotIn applies the NotIn predicate on the "blob_uri" field.
func BlobURINotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldBlobURI, vs...))
}

// BlobURIGT applies the GT predicate on the "blob_uri" field.
func BlobURIGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldBlobURI, v))
}

// BlobURIGTE applies the GTE predicate on the "blob_uri" field.
func BlobURIGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldBlobURI, v))
}

// BlobURILT applies the LT predicate on the "blob_uri" field.
func BlobURILT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldBlobURI, v))
}

// BlobURILTE applies the LTE predicate on the "blob_uri" field.
func BlobURILTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldBlobURI, v))
}

// BlobURIContains applies the Contains predicate on the "blob_uri" field.
func BlobURIContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldBlobURI, v))
}

// BlobURIHasPrefix applies the HasPrefix predicate on the "blob_uri" field.
func BlobURIHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldBlobURI, v))
}

// BlobURIHasSuffix applies the HasSuffix predicate on the "blob_uri" field.
func BlobURIHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldBlobURI, v))
}

// BlobURIIsNil applies the IsNil predicate on the "blob_uri" field.
func BlobURIIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldBlobURI))
}

// BlobURINotNil applies the NotNil predicate on the "blob_uri" field.
func BlobURINotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldBlobURI))
}

// BlobURIEqualFold applies the EqualFold predicate on the "blob_uri" field.
func BlobURIEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldBlobURI, v))
}

// BlobURIContainsFold applies the ContainsFold predicate on the "blob_uri" field.
func BlobURIContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldBlobURI, v))
}

// RequestBlobURIEQ applies the EQ predicate on the "request_blob_uri" field.
func RequestBlobURIEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRequestBlobURI, v))
}

// RequestBlobURINEQ applies the NEQ predicate on the "request_blob_uri" field.
func RequestBlobURINEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldRequestBlobURI, v))
}

// RequestBlobURIIn applies the In predicate on the "request_blob_uri" field.
func RequestBlobURIIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldRequestBlobURI, vs...))
}

// RequestBlobURINotIn applies the NotIn predicate on the "request_blob_uri" field.
func RequestBlobURINotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldRequestBlobURI, vs...))
}

// RequestBlobURIGT applies the GT predicate on the "request_blob_uri" field.
func RequestBlobURIGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldRequestBlobURI, v))
}

// RequestBlobURIGTE applies the GTE predicate on the "request_blob_uri" field.
func RequestBlobURIGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldRequestBlobURI, v))
}

// RequestBlobURILT applies the LT predicate on the "request_blob_uri" field.
func RequestBlobURILT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldRequestBlobURI, v))
}

// RequestBlobURILTE applies the LTE predicate on the "request_blob_uri" field.
func RequestBlobURILTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldRequestBlobURI, v))
}

// RequestBlobURIContains applies the Contains predicate on the "request_blob_uri" field.
func RequestBlobURIContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldRequestBlobURI, v))
}

// RequestBlobURIHasPrefix applies the HasPrefix predicate on the "request_blob_uri" field.
func RequestBlobURIHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldRequestBlobURI, v))
}

// RequestBlobURIHasSuffix applies the HasSuffix predicate on the "request_blob_uri" field.
func RequestBlobURIHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldRequestBlobURI, v))
}

// RequestBlobURIIsNil applies the IsNil predicate on the "request_blob_uri" field.
func RequestBlobURIIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldRequestBlobURI))
}

// RequestBlobURINotNil applies the NotNil predicate on the "request_blob_uri" field.
func RequestBlobURINotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldRequestBlobURI))
}

// RequestBlobURIEqualFold applies the EqualFold predicate on the "request_blob_uri" field.
func RequestBlobURIEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldRequestBlobURI, v))
}

// RequestBlobURIContainsFold applies the ContainsFold predicate on the "request_blob_uri" field.
func RequestBlobURIContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldRequestBlobURI, v))
}

// ResponseBlobURIEQ applies the EQ predicate on the "response_blob_uri" field.
func ResponseBlobURIEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldResponseBlobURI, v))
}

// ResponseBlobURINEQ applies the NEQ predicate on the "response_blob_uri" field.
func ResponseBlobURINEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldResponseBlobURI, v))
}

// ResponseBlobURIIn applies the In predicate on the "response_blob_uri" field.
func ResponseBlobURIIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldResponseBlobURI, vs...))
}

// ResponseBlobURINotIn applies the NotIn predicate on the "response_blob_uri" field.
func ResponseBlobURINotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldResponseBlobURI, vs...))
}

// ResponseBlobURIGT applies the GT predicate on the "response_blob_uri" field.
func ResponseBlobURIGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldResponseBlobURI, v))
}

// ResponseBlobURIGTE applies the GTE predicate on the "response_blob_uri" field.
func ResponseBlobURIGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldResponseBlobURI, v))
}

// ResponseBlobURILT applies the LT predicate on the "response_blob_uri" field.
func ResponseBlobURILT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldResponseBlobURI, v))
}

// ResponseBlobURILTE applies the LTE predicate on the "response_blob_uri" field.
func ResponseBlobURILTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldResponseBlobURI, v))
}

// ResponseBlobURIContains applies the Contains predicate on the "response_blob_uri" field.
func ResponseBlobURIContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldResponseBlobURI, v))
}

// ResponseBlobURIHasPrefix applies the HasPrefix predicate on the "response_blob_uri" field.
func ResponseBlobURIHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldResponseBlobURI, v))
}

// ResponseBlobURIHasSuffix applies the HasSuffix predicate on the "response_blob_uri" field.
func ResponseBlobURIHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldResponseBlobURI, v))
}

// ResponseBlobURIIsNil applies the IsNil predicate on the "response_blob_uri" field.
func ResponseBlobURIIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldResponseBlobURI))
}

// ResponseBlobURINotNil applies the NotNil predicate on the "response_blob_uri" field.
func ResponseBlobURINotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldResponseBlobURI))
}

// ResponseBlobURIEqualFold applies the EqualFold predicate on the "response_blob_uri" field.
func ResponseBlobURIEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldResponseBlobURI, v))
}

// ResponseBlobURIContainsFold applies the ContainsFold predicate on the "response_blob_uri" field.
func ResponseBlobURIContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldResponseBlobURI, v))
}

// StreamBlobURIEQ applies the EQ predicate on the "stream_blob_uri" field.
func StreamBlobURIEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldStreamBlobURI, v))
}

// StreamBlobURINEQ applies the NEQ predicate on the "stream_blob_uri" field.
func StreamBlobURINEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldStreamBlobURI, v))
}

// StreamBlobURIIn applies the In predicate on the "stream_blob_uri" field.
func StreamBlobURIIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldStreamBlobURI, vs...))
}

// StreamBlobURINotIn applies the NotIn predicate on the "stream_blob_uri" field.
func StreamBlobURINotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldStreamBlobURI, vs...))
}

// StreamBlobURIGT applies the GT predicate on the "stream_blob_uri" field.
func StreamBlobURIGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldStreamBlobURI, v))
}

// StreamBlobURIGTE applies the GTE predicate on the "stream_blob_uri" field.
func StreamBlobURIGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldStreamBlobURI, v))
}

// StreamBlobURILT applies the LT predicate on the "stream_blob_uri" field.
func StreamBlobURILT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldStreamBlobURI, v))
}

// StreamBlobURILTE applies the LTE predicate on the "stream_blob_uri" field.
func StreamBlobURILTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldStreamBlobURI, v))
}

// StreamBlobURIContains applies the Contains predicate on the "stream_blob_uri" field.
func StreamBlobURIContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldStreamBlobURI, v))
}

// StreamBlobURIHasPrefix applies the HasPrefix predicate on the "stream_blob_uri" field.
func StreamBlobURIHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldStreamBlobURI, v))
}

// StreamBlobURIHasSuffix applies the HasSuffix predicate on the "stream_blob_uri" field.
func StreamBlobURIHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldStreamBlobURI, v))
}

// StreamBlobURIIsNil applies the IsNil predicate on the "stream_blob_uri" field.
func StreamBlobURIIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldStreamBlobURI))
}

// StreamBlobURINotNil applies the NotNil predicate on the "stream_blob_uri" field.
func StreamBlobURINotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldStreamBlobURI))
}

// StreamBlobURIEqualFold applies the EqualFold predicate on the "stream_blob_uri" field.
func StreamBlobURIEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldStreamBlobURI, v))
}

// StreamBlobURIContainsFold applies the ContainsFold predicate on the "stream_blob_uri" field.
func StreamBlobURIContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldStreamBlobURI, v))
}

// RedactionVersionEQ applies the EQ predicate on the "redaction_version" field.
func RedactionVersionEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRedactionVersion, v))
}

// RedactionVersionNEQ applies the NEQ predicate on the "redaction_version" field.
func RedactionVersionNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldRedactionVersion, v))
}

// RedactionVersionIn applies the In predicate on the "redaction_version" field.
func RedactionVersionIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldRedactionVersion, vs...))
}

// RedactionVersionNotIn applies the NotIn predicate on the "redaction_version" field.
func RedactionVersionNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldRedactionVersion, vs...))
}

// RedactionVersionGT applies the GT predicate on the "redaction_version" field.
func RedactionVersionGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldRedactionVersion, v))
}

// RedactionVersionGTE applies the GTE predicate on the "redaction_version" field.
func RedactionVersionGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldRedactionVersion, v))
}

// RedactionVersionLT applies the LT predicate on the "redaction_version" field.
func RedactionVersionLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldRedactionVersion, v))
}

// RedactionVersionLTE applies the LTE predicate on the "redaction_version" field.
func RedactionVersionLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldRedactionVersion, v))
}

// RedactionVersionContains applies the Contains predicate on the "redaction_version" field.
func RedactionVersionContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldRedactionVersion, v))
}

// RedactionVersionHasPrefix applies the HasPrefix predicate on the "redaction_version" field.
func RedactionVersionHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldRedactionVersion, v))
}

// RedactionVersionHasSuffix applies the HasSuffix predicate on the "redaction_version" field.
func RedactionVersionHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldRedactionVersion, v))
}

// RedactionVersionEqualFold applies the EqualFold predicate on the "redaction_version" field.
func RedactionVersionEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldRedactionVersion, v))
}

// RedactionVersionContainsFold applies the ContainsFold predicate on the "redaction_version" field.
func RedactionVersionContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldRedactionVersion, v))
}

// CaptureStatusEQ applies the EQ predicate on the "capture_status" field.
func CaptureStatusEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldCaptureStatus, v))
}

// CaptureStatusNEQ applies the NEQ predicate on the "capture_status" field.
func CaptureStatusNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldCaptureStatus, v))
}

// CaptureStatusIn applies the In predicate on the "capture_status" field.
func CaptureStatusIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldCaptureStatus, vs...))
}

// CaptureStatusNotIn applies the NotIn predicate on the "capture_status" field.
func CaptureStatusNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldCaptureStatus, vs...))
}

// CaptureStatusGT applies the GT predicate on the "capture_status" field.
func CaptureStatusGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldCaptureStatus, v))
}

// CaptureStatusGTE applies the GTE predicate on the "capture_status" field.
func CaptureStatusGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldCaptureStatus, v))
}

// CaptureStatusLT applies the LT predicate on the "capture_status" field.
func CaptureStatusLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldCaptureStatus, v))
}

// CaptureStatusLTE applies the LTE predicate on the "capture_status" field.
func CaptureStatusLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldCaptureStatus, v))
}

// CaptureStatusContains applies the Contains predicate on the "capture_status" field.
func CaptureStatusContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldCaptureStatus, v))
}

// CaptureStatusHasPrefix applies the HasPrefix predicate on the "capture_status" field.
func CaptureStatusHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldCaptureStatus, v))
}

// CaptureStatusHasSuffix applies the HasSuffix predicate on the "capture_status" field.
func CaptureStatusHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldCaptureStatus, v))
}

// CaptureStatusEqualFold applies the EqualFold predicate on the "capture_status" field.
func CaptureStatusEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldCaptureStatus, v))
}

// CaptureStatusContainsFold applies the ContainsFold predicate on the "capture_status" field.
func CaptureStatusContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldCaptureStatus, v))
}

// SynthSessionIDEQ applies the EQ predicate on the "synth_session_id" field.
func SynthSessionIDEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSynthSessionID, v))
}

// SynthSessionIDNEQ applies the NEQ predicate on the "synth_session_id" field.
func SynthSessionIDNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldSynthSessionID, v))
}

// SynthSessionIDIn applies the In predicate on the "synth_session_id" field.
func SynthSessionIDIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldSynthSessionID, vs...))
}

// SynthSessionIDNotIn applies the NotIn predicate on the "synth_session_id" field.
func SynthSessionIDNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldSynthSessionID, vs...))
}

// SynthSessionIDGT applies the GT predicate on the "synth_session_id" field.
func SynthSessionIDGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldSynthSessionID, v))
}

// SynthSessionIDGTE applies the GTE predicate on the "synth_session_id" field.
func SynthSessionIDGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldSynthSessionID, v))
}

// SynthSessionIDLT applies the LT predicate on the "synth_session_id" field.
func SynthSessionIDLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldSynthSessionID, v))
}

// SynthSessionIDLTE applies the LTE predicate on the "synth_session_id" field.
func SynthSessionIDLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldSynthSessionID, v))
}

// SynthSessionIDContains applies the Contains predicate on the "synth_session_id" field.
func SynthSessionIDContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldSynthSessionID, v))
}

// SynthSessionIDHasPrefix applies the HasPrefix predicate on the "synth_session_id" field.
func SynthSessionIDHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldSynthSessionID, v))
}

// SynthSessionIDHasSuffix applies the HasSuffix predicate on the "synth_session_id" field.
func SynthSessionIDHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldSynthSessionID, v))
}

// SynthSessionIDIsNil applies the IsNil predicate on the "synth_session_id" field.
func SynthSessionIDIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldSynthSessionID))
}

// SynthSessionIDNotNil applies the NotNil predicate on the "synth_session_id" field.
func SynthSessionIDNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldSynthSessionID))
}

// SynthSessionIDEqualFold applies the EqualFold predicate on the "synth_session_id" field.
func SynthSessionIDEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldSynthSessionID, v))
}

// SynthSessionIDContainsFold applies the ContainsFold predicate on the "synth_session_id" field.
func SynthSessionIDContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldSynthSessionID, v))
}

// SynthRoleEQ applies the EQ predicate on the "synth_role" field.
func SynthRoleEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSynthRole, v))
}

// SynthRoleNEQ applies the NEQ predicate on the "synth_role" field.
func SynthRoleNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldSynthRole, v))
}

// SynthRoleIn applies the In predicate on the "synth_role" field.
func SynthRoleIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldSynthRole, vs...))
}

// SynthRoleNotIn applies the NotIn predicate on the "synth_role" field.
func SynthRoleNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldSynthRole, vs...))
}

// SynthRoleGT applies the GT predicate on the "synth_role" field.
func SynthRoleGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldSynthRole, v))
}

// SynthRoleGTE applies the GTE predicate on the "synth_role" field.
func SynthRoleGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldSynthRole, v))
}

// SynthRoleLT applies the LT predicate on the "synth_role" field.
func SynthRoleLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldSynthRole, v))
}

// SynthRoleLTE applies the LTE predicate on the "synth_role" field.
func SynthRoleLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldSynthRole, v))
}

// SynthRoleContains applies the Contains predicate on the "synth_role" field.
func SynthRoleContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldSynthRole, v))
}

// SynthRoleHasPrefix applies the HasPrefix predicate on the "synth_role" field.
func SynthRoleHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldSynthRole, v))
}

// SynthRoleHasSuffix applies the HasSuffix predicate on the "synth_role" field.
func SynthRoleHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldSynthRole, v))
}

// SynthRoleIsNil applies the IsNil predicate on the "synth_role" field.
func SynthRoleIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldSynthRole))
}

// SynthRoleNotNil applies the NotNil predicate on the "synth_role" field.
func SynthRoleNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldSynthRole))
}

// SynthRoleEqualFold applies the EqualFold predicate on the "synth_role" field.
func SynthRoleEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldSynthRole, v))
}

// SynthRoleContainsFold applies the ContainsFold predicate on the "synth_role" field.
func SynthRoleContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldSynthRole, v))
}

// SynthEngineerLevelEQ applies the EQ predicate on the "synth_engineer_level" field.
func SynthEngineerLevelEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelNEQ applies the NEQ predicate on the "synth_engineer_level" field.
func SynthEngineerLevelNEQ(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelIn applies the In predicate on the "synth_engineer_level" field.
func SynthEngineerLevelIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldSynthEngineerLevel, vs...))
}

// SynthEngineerLevelNotIn applies the NotIn predicate on the "synth_engineer_level" field.
func SynthEngineerLevelNotIn(vs ...string) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldSynthEngineerLevel, vs...))
}

// SynthEngineerLevelGT applies the GT predicate on the "synth_engineer_level" field.
func SynthEngineerLevelGT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelGTE applies the GTE predicate on the "synth_engineer_level" field.
func SynthEngineerLevelGTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelLT applies the LT predicate on the "synth_engineer_level" field.
func SynthEngineerLevelLT(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelLTE applies the LTE predicate on the "synth_engineer_level" field.
func SynthEngineerLevelLTE(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelContains applies the Contains predicate on the "synth_engineer_level" field.
func SynthEngineerLevelContains(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContains(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelHasPrefix applies the HasPrefix predicate on the "synth_engineer_level" field.
func SynthEngineerLevelHasPrefix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasPrefix(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelHasSuffix applies the HasSuffix predicate on the "synth_engineer_level" field.
func SynthEngineerLevelHasSuffix(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldHasSuffix(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelIsNil applies the IsNil predicate on the "synth_engineer_level" field.
func SynthEngineerLevelIsNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldIsNull(FieldSynthEngineerLevel))
}

// SynthEngineerLevelNotNil applies the NotNil predicate on the "synth_engineer_level" field.
func SynthEngineerLevelNotNil() predicate.QARecord {
	return predicate.QARecord(sql.FieldNotNull(FieldSynthEngineerLevel))
}

// SynthEngineerLevelEqualFold applies the EqualFold predicate on the "synth_engineer_level" field.
func SynthEngineerLevelEqualFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldEqualFold(FieldSynthEngineerLevel, v))
}

// SynthEngineerLevelContainsFold applies the ContainsFold predicate on the "synth_engineer_level" field.
func SynthEngineerLevelContainsFold(v string) predicate.QARecord {
	return predicate.QARecord(sql.FieldContainsFold(FieldSynthEngineerLevel, v))
}

// DialogSynthEQ applies the EQ predicate on the "dialog_synth" field.
func DialogSynthEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldDialogSynth, v))
}

// DialogSynthNEQ applies the NEQ predicate on the "dialog_synth" field.
func DialogSynthNEQ(v bool) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldDialogSynth, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldCreatedAt, v))
}

// RetentionUntilEQ applies the EQ predicate on the "retention_until" field.
func RetentionUntilEQ(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldEQ(FieldRetentionUntil, v))
}

// RetentionUntilNEQ applies the NEQ predicate on the "retention_until" field.
func RetentionUntilNEQ(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldNEQ(FieldRetentionUntil, v))
}

// RetentionUntilIn applies the In predicate on the "retention_until" field.
func RetentionUntilIn(vs ...time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldIn(FieldRetentionUntil, vs...))
}

// RetentionUntilNotIn applies the NotIn predicate on the "retention_until" field.
func RetentionUntilNotIn(vs ...time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldNotIn(FieldRetentionUntil, vs...))
}

// RetentionUntilGT applies the GT predicate on the "retention_until" field.
func RetentionUntilGT(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldGT(FieldRetentionUntil, v))
}

// RetentionUntilGTE applies the GTE predicate on the "retention_until" field.
func RetentionUntilGTE(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldGTE(FieldRetentionUntil, v))
}

// RetentionUntilLT applies the LT predicate on the "retention_until" field.
func RetentionUntilLT(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldLT(FieldRetentionUntil, v))
}

// RetentionUntilLTE applies the LTE predicate on the "retention_until" field.
func RetentionUntilLTE(v time.Time) predicate.QARecord {
	return predicate.QARecord(sql.FieldLTE(FieldRetentionUntil, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QARecord) predicate.QARecord {
	return predicate.QARecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QARecord) predicate.QARecord {
	return predicate.QARecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QARecord) predicate.QARecord {
	return predicate.QARecord(sql.NotPredicates(p))
}
