//go:build unit

package admin

import (
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/handler/dto"
	"github.com/Wei-Shaw/sub2api/internal/service"
	"github.com/stretchr/testify/require"
)

// BLOCKER3 regression: the priced-serving-gate enabled SET must survive the admin
// PUT MERGE layer (tkApplyTokenKeySettingsFields), not just the lower
// service-layer round-trip. The original bug was that PricedServingGateEnabled
// was absent from UpdateSettingsRequest / the merge / the persisted struct, so a
// partial PUT left it "" and tkAppendColdStartSettingUpdates clobbered the DB
// "gemini" to "" — silently disabling the gate on every save.
//
// These tests exercise the REAL merge function (the layer the self-built
// service-level round-trip test bypassed, which is why it was green while the
// gate was being clobbered in prod).

func strPtr(s string) *string { return &s }

// TestMerge_PartialPUT_PreservesGateSet pins the clobber fix: a PUT that does NOT
// include priced_serving_gate_enabled (nil pointer) must keep the previously
// persisted set, not reset it to "".
func TestMerge_PartialPUT_PreservesGateSet(t *testing.T) {
	previous := &service.SystemSettings{
		AutoGenerateDefaultTokenName: "trial",
		PricedServingGateEnabled:     "gemini", // already enabled in DB
	}
	// Partial PUT: operator toggles some unrelated field, omits the gate set.
	req := &UpdateSettingsRequest{
		PricedServingGateEnabled: nil, // not in payload
	}
	dst := &service.SystemSettings{}

	tkApplyTokenKeySettingsFields(dst, req, previous)

	require.Equal(t, "gemini", dst.PricedServingGateEnabled,
		"partial PUT (nil pointer) must PRESERVE the persisted enabled set, not clobber it to \"\"")
}

// TestMerge_ExplicitSet_ChangesGateSet pins the rollback/gray-rollout knob: an
// explicit value in the PUT actually changes the set (the operator can add a
// platform or roll back).
func TestMerge_ExplicitSet_ChangesGateSet(t *testing.T) {
	previous := &service.SystemSettings{
		AutoGenerateDefaultTokenName: "trial",
		PricedServingGateEnabled:     "gemini",
	}

	t.Run("add a platform", func(t *testing.T) {
		req := &UpdateSettingsRequest{PricedServingGateEnabled: strPtr("gemini,openai")}
		dst := &service.SystemSettings{}
		tkApplyTokenKeySettingsFields(dst, req, previous)
		require.Equal(t, "gemini,openai", dst.PricedServingGateEnabled)
	})

	t.Run("explicit empty rolls back", func(t *testing.T) {
		req := &UpdateSettingsRequest{PricedServingGateEnabled: strPtr("")}
		dst := &service.SystemSettings{}
		tkApplyTokenKeySettingsFields(dst, req, previous)
		require.Equal(t, "", dst.PricedServingGateEnabled,
			"an explicit empty set IS honored (rollback) even though previous was gemini")
	})

	t.Run("whitespace trimmed", func(t *testing.T) {
		req := &UpdateSettingsRequest{PricedServingGateEnabled: strPtr("  gemini , openai  ")}
		dst := &service.SystemSettings{}
		tkApplyTokenKeySettingsFields(dst, req, previous)
		require.Equal(t, "gemini , openai", dst.PricedServingGateEnabled,
			"outer whitespace trimmed; inner set string preserved for IsPricedServingGateEnabled to split")
	})
}

// TestAttach_GateSetMirroredToDTO pins that the persisted set reaches the admin
// GET response DTO (so the UI can render/edit it). Without this the admin can
// never see or change the set through the API.
func TestAttach_GateSetMirroredToDTO(t *testing.T) {
	s := &service.SystemSettings{
		PricedServingGateEnabled: "gemini,openai",
	}
	dst := &dto.SystemSettings{}
	tkAttachColdStartSettings(dst, s)
	require.Equal(t, "gemini,openai", dst.PricedServingGateEnabled,
		"persisted enabled set must be echoed into the admin GET DTO")
}

// TestDiff_GateSetChangeAudited pins the audit-diff coverage: a change to the set
// is recorded in the settings audit diff.
func TestDiff_GateSetChangeAudited(t *testing.T) {
	before := &service.SystemSettings{PricedServingGateEnabled: "gemini"}
	after := &service.SystemSettings{PricedServingGateEnabled: "gemini,openai"}
	changed := tkDiffColdStartSettings(before, after)
	require.Contains(t, changed, "priced_serving_gate_enabled",
		"a change to the enabled set must appear in the audit diff")

	// No change → not in diff.
	same := tkDiffColdStartSettings(before, before)
	require.NotContains(t, same, "priced_serving_gate_enabled")
}
