package admin

import (
	"strings"

	"github.com/Wei-Shaw/sub2api/internal/handler/dto"
	"github.com/Wei-Shaw/sub2api/internal/service"
)

// tkCoalesceOptionalBool merges a JSON pointer field with the previous persisted value
// (nil pointer means "keep previous"), used for TokenKey-specific toggles on SystemSettings.
func tkCoalesceOptionalBool(req *bool, previous bool) bool {
	if req != nil {
		return *req
	}
	return previous
}

func tkCoalesceOptionalFloat64(req *float64, previous float64) float64 {
	if req != nil {
		return *req
	}
	return previous
}

func tkCoalesceOptionalString(req *string, previous string) string {
	if req != nil {
		return *req
	}
	return previous
}

// tkApplyTokenKeySettingsFields merges TokenKey toggles (bridge + new-user cold start)
// from the admin update payload onto the SystemSettings being persisted. Nil pointers
// keep the previous persisted value so partial PUTs cannot accidentally reset toggles.
func tkApplyTokenKeySettingsFields(dst *service.SystemSettings, req *UpdateSettingsRequest, previous *service.SystemSettings) {
	if dst == nil || req == nil || previous == nil {
		return
	}
	dst.NewAPIBridgeEnabled = tkCoalesceOptionalBool(req.NewAPIBridgeEnabled, previous.NewAPIBridgeEnabled)

	// New-User Cold Start (docs/approved/user-cold-start.md §5).
	dst.SignupBonusEnabled = tkCoalesceOptionalBool(req.SignupBonusEnabled, previous.SignupBonusEnabled)
	bonus := tkCoalesceOptionalFloat64(req.SignupBonusBalance, previous.SignupBonusBalance)
	if bonus < 0 {
		bonus = 0
	}
	dst.SignupBonusBalance = bonus
	dst.AutoGenerateDefaultToken = tkCoalesceOptionalBool(req.AutoGenerateDefaultToken, previous.AutoGenerateDefaultToken)
	tokenName := strings.TrimSpace(tkCoalesceOptionalString(req.AutoGenerateDefaultTokenName, previous.AutoGenerateDefaultTokenName))
	if tokenName == "" {
		tokenName = previous.AutoGenerateDefaultTokenName
	}
	if tokenName == "" {
		tokenName = "trial"
	}
	dst.AutoGenerateDefaultTokenName = tokenName
	dst.PricingCatalogPublic = tkCoalesceOptionalBool(req.PricingCatalogPublic, previous.PricingCatalogPublic)
}

// tkTokenKeyBridgeSetting exposes the bridge flag for admin settings DTO assembly.
func tkTokenKeyBridgeSetting(s *service.SystemSettings) bool {
	if s == nil {
		return false
	}
	return s.NewAPIBridgeEnabled
}

// tkAttachColdStartSettings mirrors the persisted cold-start fields into the admin
// settings DTO. Called from both GetSettings and UpdateSettings response paths so
// the upstream-shaped struct literal in setting_handler.go stays untouched by the
// new TK fields except for one helper invocation.
func tkAttachColdStartSettings(dst *dto.SystemSettings, s *service.SystemSettings) {
	if dst == nil || s == nil {
		return
	}
	dst.SignupBonusEnabled = s.SignupBonusEnabled
	dst.SignupBonusBalance = s.SignupBonusBalance
	dst.AutoGenerateDefaultToken = s.AutoGenerateDefaultToken
	dst.AutoGenerateDefaultTokenName = s.AutoGenerateDefaultTokenName
	dst.PricingCatalogPublic = s.PricingCatalogPublic
}

// tkDiffColdStartSettings appends audit diff entries for the cold-start fields.
// Returns the list of changed snake_case field names; matches the shape used by
// diffSettings in setting_handler.go.
func tkDiffColdStartSettings(before, after *service.SystemSettings) []string {
	if before == nil || after == nil {
		return nil
	}
	changed := make([]string, 0, 5)
	if before.SignupBonusEnabled != after.SignupBonusEnabled {
		changed = append(changed, "signup_bonus_enabled")
	}
	if before.SignupBonusBalance != after.SignupBonusBalance {
		changed = append(changed, "signup_bonus_balance")
	}
	if before.AutoGenerateDefaultToken != after.AutoGenerateDefaultToken {
		changed = append(changed, "auto_generate_default_token")
	}
	if before.AutoGenerateDefaultTokenName != after.AutoGenerateDefaultTokenName {
		changed = append(changed, "auto_generate_default_token_name")
	}
	if before.PricingCatalogPublic != after.PricingCatalogPublic {
		changed = append(changed, "pricing_catalog_public")
	}
	return changed
}
