#!/usr/bin/env python3
"""Gate B (authoritative half): execute every ops-generated SQL on a real Postgres.

PR #563 shipped generators whose SQL Postgres rejected with a syntax error, but
the tests only mocked the DB + asserted substrings, so it was green. The honest
check is to let Postgres — the real parser — judge every generated statement.

This test renders every SQL from each ops module's ``iter_self_check_sql()`` and
runs it under ``psql -v ON_ERROR_STOP=1`` against a throwaway Postgres. The
companion static check ``scripts/checks/ops-sql-coverage.py`` guarantees every
generator is enumerated here, so "covered" really means "executed".

Postgres source:
  * ``TK_SQL_EXEC_PSQL`` (a libpq conninfo to an empty DB) if set; else
  * a self-provisioned ``postgres:16-alpine`` container when ``docker`` is on PATH.
Skips (does not fail) when neither is available — CI has docker, so it runs there.
stdlib-only.
"""
from __future__ import annotations

import importlib.util
import os
import pathlib
import shutil
import subprocess
import sys
import time
import unittest

OPS_ANTHROPIC = pathlib.Path(__file__).resolve().parent
OPS_DIR = OPS_ANTHROPIC.parent

# Minimal schema covering every column/constraint the generators touch. Seeded so
# the mutation generators execute cleanly: users.id=1 must exist (the balance SQL
# RAISEs otherwise); tls_fingerprint_profiles.id auto-generates + name is unique
# (generate_sql INSERT ... ON CONFLICT (name)).
SCHEMA = """
CREATE TABLE api_keys(id bigint, user_id bigint, key text, status text, deleted_at timestamptz, expires_at timestamptz);
CREATE TABLE qa_records(request_id text, user_id bigint, api_key_id bigint, requested_model text,
  inbound_endpoint text, stream boolean, tool_calls_present boolean, multimodal_present boolean,
  blob_uri text, created_at timestamptz, duration_ms bigint, success boolean);
CREATE TABLE usage_logs(request_id text, created_at timestamptz);
CREATE TABLE accounts(id bigint, name text, platform text, type text, status text, schedulable boolean,
  concurrency int, load_factor numeric, priority int, channel_type int, rate_multiplier numeric,
  auto_pause_on_expired boolean, proxy_id bigint, error_message text, last_used_at timestamptz,
  session_window_end timestamptz, credentials jsonb DEFAULT '{}', extra jsonb DEFAULT '{}',
  created_at timestamptz, updated_at timestamptz, deleted_at timestamptz);
CREATE TABLE groups(id bigint, name text, platform text, status text, claude_code_only boolean,
  supported_model_scopes jsonb, fallback_group_id bigint, created_at timestamptz, updated_at timestamptz, deleted_at timestamptz);
CREATE TABLE account_groups(account_id bigint, group_id bigint);
CREATE TABLE users(id bigint, balance numeric, concurrency int,
  created_at timestamptz, updated_at timestamptz, deleted_at timestamptz);
CREATE TABLE tiers(name text, concurrency int, priority int, rate_multiplier numeric, base_rpm int,
  rpm_sticky_buffer int, max_sessions int, session_idle_timeout_minutes int,
  cache_ttl_override_enabled boolean, cache_ttl_override_target text,
  tls_profile_name text, created_at timestamptz, updated_at timestamptz);
CREATE TABLE settings(key text PRIMARY KEY, value text, created_at timestamptz, updated_at timestamptz);
CREATE TABLE scheduler_outbox(id bigserial PRIMARY KEY, event_type text NOT NULL, account_id bigint,
  group_id bigint, payload jsonb, created_at timestamptz NOT NULL DEFAULT NOW());
CREATE TABLE tls_fingerprint_profiles(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE, description text, enable_grease boolean, cipher_suites jsonb, curves jsonb,
  point_formats jsonb, signature_algorithms jsonb, alpn_protocols jsonb, supported_versions jsonb,
  key_share_groups jsonb, psk_modes jsonb, extensions jsonb, created_at timestamptz, updated_at timestamptz);
INSERT INTO users(id,balance,concurrency) VALUES (1,0,8),(5,0,4);
INSERT INTO accounts(id,name,platform,type,status,schedulable,concurrency,priority,channel_type,
  rate_multiplier,auto_pause_on_expired,extra)
  VALUES (42,'weird''name','anthropic','oauth','active',true,10,50,0,1.0,true,'{"stability_tier":"l5"}');
"""

_OPS_MODULES = [
    OPS_ANTHROPIC / "manage-anthropic-config.py",
    OPS_ANTHROPIC / "check-edge-oauth-stability.py",
    OPS_ANTHROPIC / "rebalance-anthropic-priority.py",
    OPS_DIR / "antigravity" / "check-antigravity-account-config.py",
    OPS_DIR / "grok" / "migrate-grok-relay-stubs.py",
    OPS_DIR / "stage0" / "prod_replay.py",
]


def _load(path: pathlib.Path):
    for sub in sorted(p for p in OPS_DIR.iterdir() if p.is_dir()):
        if str(sub) not in sys.path:
            sys.path.insert(0, str(sub))
    spec = importlib.util.spec_from_file_location("opssqlx_" + path.stem.replace("-", "_"), path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _have_backend() -> bool:
    # Docker path runs psql INSIDE the container (docker exec) — no host psql,
    # no port mapping, no host->container networking (the fragile bits that fail
    # in CI). So docker alone is enough; host psql is only needed for the
    # explicit TK_SQL_EXEC_PSQL opt-in DSN.
    if os.environ.get("TK_SQL_EXEC_PSQL"):
        return bool(shutil.which("psql"))
    return bool(shutil.which("docker"))


@unittest.skipUnless(
    _have_backend(),
    "needs TK_SQL_EXEC_PSQL(+psql) or docker to execute generated SQL on a real Postgres",
)
class OpsSqlExecuteTest(unittest.TestCase):
    _container: str | None = None
    _dsn: str = ""  # set when using an external Postgres via TK_SQL_EXEC_PSQL

    @classmethod
    def setUpClass(cls) -> None:
        # Any infra problem (no docker daemon, image pull offline, connection
        # failure, schema rejected) must SKIP — never red the gate on infra. The
        # static coverage check stays the always-on floor.
        try:
            dsn = os.environ.get("TK_SQL_EXEC_PSQL")
            if dsn:
                cls._dsn = dsn
            else:
                cls._container = "tk-ops-sql-" + str(os.getpid())
                subprocess.run(
                    ["docker", "run", "-d", "--rm", "--name", cls._container,
                     "-e", "POSTGRES_PASSWORD=x", "-e", "POSTGRES_DB=t", "postgres:16-alpine"],
                    check=True, capture_output=True, text=True,
                )
                ready = False
                deadline = time.time() + 60
                while time.time() < deadline:
                    if subprocess.run(["docker", "exec", cls._container, "pg_isready", "-U", "postgres"],
                                      capture_output=True).returncode == 0:
                        ready = True
                        break
                    time.sleep(1)
                if not ready:
                    raise RuntimeError("postgres did not become ready in 60s")
            schema = cls._run_sql(cls, SCHEMA)  # type: ignore[arg-type]
            if schema.returncode != 0:
                raise RuntimeError(f"schema setup failed: {schema.stderr.strip()}")
        except (subprocess.CalledProcessError, RuntimeError, OSError) as exc:
            cls.tearDownClass()
            raise unittest.SkipTest(f"postgres backend unavailable: {exc}")

    @classmethod
    def tearDownClass(cls) -> None:
        if cls._container:
            subprocess.run(["docker", "rm", "-f", cls._container], capture_output=True)
            cls._container = None

    def _run_sql(self, sql: str) -> subprocess.CompletedProcess:
        if not sql.strip().endswith(";"):
            sql += ";"
        base = ["psql", "-v", "ON_ERROR_STOP=1", "-q", "-t", "-A", "-f", "-"]
        if self._container:  # run psql inside the container — robust, no networking
            cmd = ["docker", "exec", "-i", self._container,
                   "psql", "-U", "postgres", "-d", "t", "-v", "ON_ERROR_STOP=1", "-q", "-t", "-A"]
        else:
            cmd = ["psql", self._dsn, *base[1:]]
        return subprocess.run(cmd, input=sql, text=True, capture_output=True)

    def test_every_generated_sql_executes(self) -> None:
        total = 0
        for path in _OPS_MODULES:
            mod = _load(path)
            for label, sql in mod.iter_self_check_sql():
                total += 1
                with self.subTest(generator=f"{path.name}:{label}"):
                    proc = self._run_sql(sql)
                    self.assertEqual(
                        proc.returncode, 0,
                        f"Postgres rejected {path.name}:{label}:\n{proc.stderr}\n---\n{sql}",
                    )
        self.assertGreaterEqual(total, 15, "expected the full ops generator fleet")

    def test_replay_selection_covers_window_ends_and_keeps_revoked_strata(self):
        replay = _load(OPS_DIR / "stage0" / "prod_replay.py")
        self.assertEqual(self._run_sql("""
INSERT INTO api_keys (id,user_id,status,deleted_at,expires_at) VALUES (71,71,'active',NULL,NULL), (72,72,'disabled',now(),NULL);
INSERT INTO qa_records
SELECT 'req-'||n,71,71,'m','/v1/messages',false,false,false,'file:///retained',
       now()-n*interval '1 minute',5000,true FROM generate_series(1,200) n;
INSERT INTO qa_records VALUES ('revoked',72,72,'m','/v1/messages',false,false,false,
       'file:///retained',now(),5000,true);
""").returncode, 0)
        try:
            import json
            proc = self._run_sql(replay.capture_query())
            self.assertEqual(proc.returncode, 0, proc.stderr)
            rows = [json.loads(line) for line in proc.stdout.splitlines() if line.strip()]
            active = [r for r in rows if r['user_id'] == 71]
            self.assertEqual(len(active), 50)
            self.assertTrue(all(r["key_replayable"] and r["key_state"] == "active" for r in active))
            self.assertEqual({r['request_id'] for r in active},
                             {'req-'+str(i) for i in (*range(1,26), *range(176,201))})
            revoked = [r for r in rows if r['user_id'] == 72]
            self.assertEqual(len(revoked), 1)
            self.assertFalse(revoked[0]['key_replayable'])
        finally:
            self.assertEqual(self._run_sql('DELETE FROM qa_records; DELETE FROM api_keys;').returncode, 0)

    def test_replay_key_state_matches_auth_precedence_and_introspection(self):
        import json
        replay = _load(OPS_DIR / "stage0" / "prod_replay.py")
        self.assertEqual(self._run_sql("""
INSERT INTO api_keys (id,user_id,status,deleted_at,expires_at) VALUES
(901,901,'disabled',NULL,now()-interval '1 hour'),
(902,902,'quota_exhausted',NULL,now()-interval '1 hour'),
(903,903,'active',NULL,now()-interval '1 hour'),
(904,904,'active',now(),NULL);
INSERT INTO qa_records
SELECT 'auth-state-'||id,user_id,id,'m','/v1/models',false,false,false,'file:///retained',now(),1,true
FROM api_keys WHERE id BETWEEN 901 AND 904;
""").returncode, 0)
        try:
            expected = {901:'disabled',902:'quota_exhausted',903:'expired',904:'deleted'}
            for query in (replay.capture_query(), replay.credential_snapshot_query()):
                proc = self._run_sql(query)
                self.assertEqual(proc.returncode, 0, proc.stderr)
                rows = [json.loads(line) for line in proc.stdout.splitlines() if line.strip()]
                for r in rows:
                    if r['user_id'] not in expected:
                        continue
                    self.assertEqual(r['key_state'], expected[r['user_id']])
                    if 'key_replayable' in r:
                        self.assertEqual(r['key_replayable'], r['user_id'] in (902,903))
        finally:
            self.assertEqual(self._run_sql('DELETE FROM qa_records; DELETE FROM api_keys;').returncode, 0)

    def test_reverse_teeth_corrupt_sql_is_rejected(self) -> None:
        # Prove the gate has teeth: an unbalanced COALESCE( (the PR #563 shape)
        # must be rejected by Postgres.
        broken = "SELECT COALESCE(jsonb_agg(jsonb_build_object('x', 1)), '[]'::jsonb FROM accounts;"
        proc = self._run_sql(broken)
        self.assertNotEqual(proc.returncode, 0, "corrupted SQL should be rejected")


if __name__ == "__main__":
    unittest.main()
