#!/usr/bin/env python3
"""Open or refresh a human-facing issue when TokenKey is behind upstream/main.

CI entry:  python3 scripts/upstream/notify-merge-needed.py apply ...
Local:     python3 scripts/upstream/notify-merge-needed.py --selftest

This tool never merges, never opens a PR, and never runs an agent.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Protocol

LABEL = "upstream-merge-needed"
LEGACY_LABEL = "upstream-merge-agent"
AUTOMATED_LABEL = "automated"
COMMIT_LIMIT = 30
WORKFLOW_RELPATH = ".github/workflows/upstream-merge-notify.yml"
FORBIDDEN_WORKFLOW_NEEDLES = (
    "run-headless-agent",
    "ANTHROPIC_AUTH_TOKEN",
    "git merge --no-ff",
    "gh workflow run",
    "claude -p",
    "UPSTREAM_MERGE_GH_TOKEN",
    "merge-state.sh",
    # Private-repo origin fetch needs the checkout token. The old daily
    # agent rewrote origin with a PAT after persist-credentials: false;
    # this workflow has no PAT and must not drop credentials.
    "persist-credentials: false",
)


class IssueHost(Protocol):
    def list_open(self, label: str) -> list[int]: ...
    def create(self, title: str, body: str, labels: list[str]) -> int: ...
    def update(self, number: int, title: str, body: str) -> None: ...
    def comment(self, number: int, body: str) -> None: ...
    def close(self, number: int, comment: str) -> None: ...
    def ensure_label(self, name: str, color: str, description: str) -> None: ...


def decide_action(*, behind: int, existing_open: bool) -> str:
    if behind < 0:
        raise ValueError("behind must be >= 0")
    if behind > 0:
        return "update" if existing_open else "create"
    return "close" if existing_open else "noop"


def render_title(behind: int) -> str:
    unit = "commit" if behind == 1 else "commits"
    return f"[upstream-merge] Wei-Shaw/sub2api is {behind} {unit} ahead of TokenKey"


def parse_merge_tree_conflicts(raw: str) -> list[str]:
    """Parse `git merge-tree --write-tree --name-only --no-messages` output.

    First line is the merged tree OID; remaining non-empty lines are conflicted paths.
    """
    lines = [line for line in raw.splitlines() if line.strip()]
    if not lines:
        return []
    first = lines[0].strip()
    if not re.fullmatch(r"[0-9a-f]{40,64}", first):
        raise ValueError("merge-tree output missing leading tree OID")
    return lines[1:]


def truncate_commits(commits: list[str], limit: int = COMMIT_LIMIT) -> tuple[list[str], int]:
    cleaned = [line.rstrip("\n") for line in commits if line.strip()]
    if len(cleaned) <= limit:
        return cleaned, 0
    return cleaned[:limit], len(cleaned) - limit


def render_body(
    *,
    drift: dict[str, Any],
    commits: list[str],
    conflicts: list[str],
    open_prs: list[dict[str, Any]],
    run_url: str,
    hidden_commit_count: int = 0,
) -> str:
    behind = int(drift.get("behind") or 0)
    ahead = int(drift.get("ahead") or 0)
    upstream_head = str(drift.get("upstream_head") or "")
    origin_head = str(drift.get("origin_head") or "")
    shown, hidden = truncate_commits(commits)
    if hidden_commit_count:
        hidden = hidden_commit_count

    commit_block = "\n".join(shown) if shown else "(none)"
    if hidden:
        commit_block += f"\n... ({hidden} more)"

    if conflicts:
        conflict_block = "\n".join(f"- `{path}`" for path in conflicts)
    else:
        conflict_block = "none (clean merge-tree)"

    if open_prs:
        pr_lines = [
            "- Do not treat leftover `merge/upstream-*` PRs as human-approved.",
            "",
        ]
        for pr in open_prs:
            number = pr.get("number")
            title = pr.get("title") or ""
            url = pr.get("url") or ""
            head = pr.get("headRefName") or ""
            pr_lines.append(f"- #{number} `{head}` {title} {url}".rstrip())
        pr_block = "\n".join(pr_lines)
    else:
        pr_block = "none"

    return "\n".join(
        [
            "> Auto-generated by `.github/workflows/upstream-merge-notify.yml`.",
            "> This workflow does **not** merge, open a PR, or run an agent.",
            "",
            "## Drift",
            "",
            f"- TokenKey behind: {behind} commits (`origin/main..upstream/main`)",
            f"- TokenKey ahead: {ahead} commits (`upstream/main..origin/main`)",
            f"- upstream/main: `{upstream_head}`",
            f"- origin/main: `{origin_head}`",
            f"- run: {run_url or 'n/a'}",
            "",
            "## New upstream commits (`origin/main..upstream/main`)",
            "",
            "```",
            commit_block,
            "```",
            "",
            "## merge-tree conflict files (read-only)",
            "",
            "If we merged `upstream/main` into `origin/main` now, these files would conflict:",
            "",
            conflict_block,
            "",
            "## Open merge/upstream-* PRs",
            "",
            pr_block,
            "",
            "## Human next steps",
            "",
            "1. Decide whether this batch is worth merging. Large or hotspot-heavy batches can wait.",
            "2. Follow `.cursor/skills/tokenkey-upstream-merge/SKILL.md`.",
            "3. `git fetch upstream && git fetch origin`",
            "4. `git checkout -b merge/upstream-$(date -u +%Y%m%d) origin/main`",
            "5. `git merge --no-ff upstream/main`",
            "6. Resolve conflicts, keep TokenKey companions/sentinels, run `./scripts/preflight.sh` and `make test`.",
            "7. Open a `merge/upstream-*` PR. `upstream-merge-pr-shape.yml` is the shape gate.",
            "",
        ]
    ) + "\n"


def apply(
    *,
    drift: dict[str, Any],
    commits: list[str],
    conflicts: list[str],
    open_prs: list[dict[str, Any]],
    run_url: str,
    host: IssueHost,
) -> dict[str, Any]:
    if "behind" not in drift:
        raise ValueError("drift JSON missing 'behind'")
    behind = int(drift["behind"])
    existing = host.list_open(LABEL)
    action = decide_action(behind=behind, existing_open=bool(existing))
    primary: int | None = existing[0] if existing else None

    host.ensure_label(LABEL, "D93F0B", "TokenKey is behind Wei-Shaw/sub2api")
    host.ensure_label(AUTOMATED_LABEL, "C5DEF5", "Automated signal")

    if action in {"create", "update"}:
        title = render_title(behind)
        body = render_body(
            drift=drift,
            commits=commits,
            conflicts=conflicts,
            open_prs=open_prs,
            run_url=run_url,
        )
        if action == "create":
            primary = host.create(title, body, [LABEL, AUTOMATED_LABEL])
        else:
            assert primary is not None
            host.update(primary, title, body)
            host.comment(primary, f"Refreshed by {run_url}: still {behind} commit(s) behind.")
            for extra in existing[1:]:
                host.close(extra, f"Duplicate of #{primary}.")
    elif action == "close":
        close_comment = (
            f"origin/main now contains upstream/main (`{drift.get('upstream_head') or ''}`). "
            f"{run_url}".rstrip()
        )
        for number in existing:
            host.close(number, close_comment)
        primary = None

    legacy_msg = "The Daily Upstream Merge Agent no longer auto-merges."
    if primary is not None:
        legacy_msg += f" See #{primary}."
    else:
        legacy_msg += (
            " A new `upstream-merge-needed` issue will open when TokenKey is behind upstream/main."
        )
    closed_legacy = []
    for number in host.list_open(LEGACY_LABEL):
        host.close(number, legacy_msg)
        closed_legacy.append(number)

    return {
        "action": action,
        "issue": primary,
        "closed_legacy": closed_legacy,
    }


class GhIssueHost:
    def __init__(self, runner: Any | None = None) -> None:
        self._run = runner or _run_gh

    def list_open(self, label: str) -> list[int]:
        raw = self._run(
            [
                "gh",
                "issue",
                "list",
                "--state",
                "open",
                "--label",
                label,
                "--json",
                "number",
                "--jq",
                "[.[].number]",
            ]
        )
        data = json.loads(raw or "[]")
        return [int(item) for item in data]

    def create(self, title: str, body: str, labels: list[str]) -> int:
        raw = self._run(
            [
                "gh",
                "issue",
                "create",
                "--title",
                title,
                "--body",
                body,
                "--label",
                ",".join(labels),
            ]
        )
        match = re.search(r"/issues/(\d+)", raw)
        if not match:
            raise RuntimeError(f"gh issue create did not return an issue URL: {raw!r}")
        return int(match.group(1))

    def update(self, number: int, title: str, body: str) -> None:
        self._run(["gh", "issue", "edit", str(number), "--title", title, "--body", body])

    def comment(self, number: int, body: str) -> None:
        self._run(["gh", "issue", "comment", str(number), "--body", body])

    def close(self, number: int, comment: str) -> None:
        self._run(["gh", "issue", "close", str(number), "--comment", comment])

    def ensure_label(self, name: str, color: str, description: str) -> None:
        self._run(
            [
                "gh",
                "label",
                "create",
                name,
                "--color",
                color,
                "--description",
                description[:100],
            ],
            allow_failure=True,
        )


def _run_gh(args: list[str], allow_failure: bool = False) -> str:
    result = subprocess.run(args, text=True, capture_output=True, check=False)
    if result.returncode != 0 and not allow_failure:
        raise RuntimeError(
            f"{args[0]} failed ({result.returncode}): {result.stderr.strip() or result.stdout.strip()}"
        )
    return result.stdout.strip()


def _load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return default
    return json.loads(text)


def _load_lines(path: Path) -> list[str]:
    if not path.exists():
        return []
    return [line.rstrip("\n") for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def cmd_apply(args: argparse.Namespace) -> int:
    drift = _load_json(Path(args.drift), {})
    if not isinstance(drift, dict) or "behind" not in drift:
        print("FAIL: --drift must be JSON with a 'behind' field", file=sys.stderr)
        return 2
    commits = _load_lines(Path(args.commits)) if args.commits else []
    conflicts_raw = Path(args.conflicts).read_text(encoding="utf-8") if args.conflicts else ""
    conflicts = parse_merge_tree_conflicts(conflicts_raw) if conflicts_raw.strip() else []
    open_prs = _load_json(Path(args.open_prs), []) if args.open_prs else []
    if not isinstance(open_prs, list):
        print("FAIL: --open-prs must be a JSON array", file=sys.stderr)
        return 2
    result = apply(
        drift=drift,
        commits=commits,
        conflicts=conflicts,
        open_prs=open_prs,
        run_url=args.run_url,
        host=GhIssueHost(),
    )
    print(json.dumps(result, ensure_ascii=False))
    return 0


def assert_workflow_is_notify_only(text: str) -> None:
    for needle in FORBIDDEN_WORKFLOW_NEEDLES:
        if needle in text:
            raise AssertionError(f"notify workflow must not contain {needle!r}")
    if "notify-merge-needed.py" not in text:
        raise AssertionError("notify workflow must invoke notify-merge-needed.py")
    if "check-drift.sh" not in text:
        raise AssertionError("notify workflow must invoke check-drift.sh")


class MemoryHost:
    def __init__(self, open_issues: dict[str, list[int]] | None = None) -> None:
        self.open_issues = {key: list(value) for key, value in (open_issues or {}).items()}
        self.created: list[tuple[str, str, list[str]]] = []
        self.updated: list[tuple[int, str, str]] = []
        self.comments: list[tuple[int, str]] = []
        self.closed: list[tuple[int, str]] = []
        self.labels: list[str] = []
        self._next_number = 9000

    def list_open(self, label: str) -> list[int]:
        return list(self.open_issues.get(label, []))

    def create(self, title: str, body: str, labels: list[str]) -> int:
        self._next_number += 1
        number = self._next_number
        self.created.append((title, body, labels))
        self.open_issues.setdefault(LABEL, []).append(number)
        return number

    def update(self, number: int, title: str, body: str) -> None:
        self.updated.append((number, title, body))

    def comment(self, number: int, body: str) -> None:
        self.comments.append((number, body))

    def close(self, number: int, comment: str) -> None:
        self.closed.append((number, comment))
        for values in self.open_issues.values():
            if number in values:
                values.remove(number)

    def ensure_label(self, name: str, color: str, description: str) -> None:
        self.labels.append(name)


def run_selftest() -> int:
    failures: list[str] = []

    def expect(name: str, cond: bool) -> None:
        print(f"{'PASS' if cond else 'FAIL'} {name}")
        if not cond:
            failures.append(name)

    expect("decide_create", decide_action(behind=3, existing_open=False) == "create")
    expect("decide_update", decide_action(behind=3, existing_open=True) == "update")
    expect("decide_close", decide_action(behind=0, existing_open=True) == "close")
    expect("decide_noop", decide_action(behind=0, existing_open=False) == "noop")
    expect("decide_single_commit_title", "1 commit ahead" in render_title(1))
    expect("decide_plural_title", "2 commits ahead" in render_title(2))

    raised = False
    try:
        decide_action(behind=-1, existing_open=False)
    except ValueError:
        raised = True
    expect("decide_rejects_negative", raised)

    tree = "0123456789abcdef0123456789abcdef01234567\nbackend/foo.go\nfrontend/bar.vue\n"
    expect("parse_conflicts", parse_merge_tree_conflicts(tree) == ["backend/foo.go", "frontend/bar.vue"])
    expect("parse_clean_tree", parse_merge_tree_conflicts("0123456789abcdef0123456789abcdef01234567\n") == [])
    parse_bad = False
    try:
        parse_merge_tree_conflicts("not-a-tree\nfile.go\n")
    except ValueError:
        parse_bad = True
    expect("parse_rejects_missing_oid", parse_bad)

    shown, hidden = truncate_commits([f"c{i}" for i in range(32)], limit=30)
    expect("truncate_keeps_30", shown == [f"c{i}" for i in range(30)] and hidden == 2)

    body = render_body(
        drift={"behind": 4, "ahead": 12, "upstream_head": "abc1234", "origin_head": "def5678"},
        commits=["aaaaaaa first", "bbbbbbb second"],
        conflicts=["backend/internal/service/gateway.go"],
        open_prs=[{"number": 1775, "title": "agent leftover", "url": "https://example.test/1775", "headRefName": "merge/upstream-2026-08-21"}],
        run_url="https://example.test/run/1",
    )
    expect("body_has_range", "origin/main..upstream/main" in body)
    expect("body_has_skill", "tokenkey-upstream-merge" in body)
    expect("body_has_conflict", "backend/internal/service/gateway.go" in body)
    expect("body_warns_leftover_pr", "Do not treat leftover" in body)
    expect("body_no_agent", "run-headless-agent" not in body)
    clean_body = render_body(
        drift={"behind": 1, "ahead": 0, "upstream_head": "a", "origin_head": "b"},
        commits=[],
        conflicts=[],
        open_prs=[],
        run_url="",
    )
    expect("body_clean_merge_tree", "none (clean merge-tree)" in clean_body)

    created_host = MemoryHost(open_issues={LEGACY_LABEL: [1776]})
    created = apply(
        drift={"behind": 5, "ahead": 1, "upstream_head": "up", "origin_head": "tk"},
        commits=["deadbeef feat"],
        conflicts=[],
        open_prs=[],
        run_url="https://example.test/run/2",
        host=created_host,
    )
    expect("apply_create", created["action"] == "create" and created["issue"] == 9001)
    expect("apply_create_closes_legacy", created["closed_legacy"] == [1776])
    expect("apply_create_mentions_new_issue", any("See #9001" in comment for _, comment in created_host.closed))

    updated_host = MemoryHost(open_issues={LABEL: [10, 11]})
    updated = apply(
        drift={"behind": 2, "ahead": 0, "upstream_head": "up", "origin_head": "tk"},
        commits=["c1"],
        conflicts=[],
        open_prs=[],
        run_url="https://example.test/run/3",
        host=updated_host,
    )
    expect("apply_update", updated["action"] == "update" and updated["issue"] == 10)
    expect("apply_update_closes_duplicate", any(number == 11 for number, _ in updated_host.closed))

    closed_host = MemoryHost(open_issues={LABEL: [10]})
    closed = apply(
        drift={"behind": 0, "ahead": 3, "upstream_head": "up", "origin_head": "tk"},
        commits=[],
        conflicts=[],
        open_prs=[],
        run_url="https://example.test/run/4",
        host=closed_host,
    )
    expect("apply_close", closed["action"] == "close" and closed["issue"] is None)
    expect("apply_close_comment", any("now contains upstream/main" in comment for _, comment in closed_host.closed))

    noop_host = MemoryHost()
    noop = apply(
        drift={"behind": 0, "ahead": 0, "upstream_head": "up", "origin_head": "tk"},
        commits=[],
        conflicts=[],
        open_prs=[],
        run_url="https://example.test/run/5",
        host=noop_host,
    )
    expect("apply_noop", noop["action"] == "noop" and not noop_host.created and not noop_host.closed)

    missing = False
    try:
        apply(drift={}, commits=[], conflicts=[], open_prs=[], run_url="", host=MemoryHost())
    except ValueError:
        missing = True
    expect("apply_rejects_missing_behind", missing)

    repo_root = Path(__file__).resolve().parents[2]
    workflow = repo_root / WORKFLOW_RELPATH
    expect("workflow_file_exists", workflow.is_file())
    if workflow.is_file():
        try:
            assert_workflow_is_notify_only(workflow.read_text(encoding="utf-8"))
            expect("workflow_is_notify_only", True)
        except AssertionError as exc:
            print(f"FAIL workflow_is_notify_only: {exc}")
            failures.append("workflow_is_notify_only")
            expect("workflow_is_notify_only", False)
    preflight = (repo_root / "scripts/preflight.sh").read_text(encoding="utf-8")
    expect(
        "preflight_runs_selftest",
        "scripts/upstream/notify-merge-needed.py --selftest" in preflight,
    )
    expect(
        "preflight_dropped_daily_agent",
        "upstream-merge-agent-daily.yml" not in preflight,
    )

    passed = 29 - len(failures)
    print(f"notify-merge-needed self-test ({passed}/29 cases passed)")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Create or refresh the upstream-merge-needed issue.")
    parser.add_argument("--selftest", action="store_true")
    sub = parser.add_subparsers(dest="command")
    apply_parser = sub.add_parser("apply", help="create/update/close the tracking issue via gh")
    apply_parser.add_argument("--drift", required=True, help="path to check-drift.sh --json output")
    apply_parser.add_argument("--commits", default="", help="path to git log origin/main..upstream/main")
    apply_parser.add_argument("--conflicts", default="", help="path to git merge-tree --name-only output")
    apply_parser.add_argument("--open-prs", default="", help="path to leftover merge/upstream-* PR JSON")
    apply_parser.add_argument("--run-url", default="", help="CI run URL written into the issue body")
    args = parser.parse_args()

    if args.selftest:
        return run_selftest()
    if args.command == "apply":
        return cmd_apply(args)
    parser.error("one of apply / --selftest is required")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
