// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelavailability"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ModelAvailabilityUpdate is the builder for updating ModelAvailability entities.
type ModelAvailabilityUpdate struct {
	config
	hooks    []Hook
	mutation *ModelAvailabilityMutation
}

// Where appends a list predicates to the ModelAvailabilityUpdate builder.
func (_u *ModelAvailabilityUpdate) Where(ps ...predicate.ModelAvailability) *ModelAvailabilityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelAvailabilityUpdate) SetUpdatedAt(v time.Time) *ModelAvailabilityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelAvailabilityUpdate) SetPlatform(v modelavailability.Platform) *ModelAvailabilityUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillablePlatform(v *modelavailability.Platform) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelAvailabilityUpdate) SetModelID(v string) *ModelAvailabilityUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableModelID(v *string) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelAvailabilityUpdate) SetStatus(v modelavailability.Status) *ModelAvailabilityUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableStatus(v *modelavailability.Status) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenOkAt sets the "last_seen_ok_at" field.
func (_u *ModelAvailabilityUpdate) SetLastSeenOkAt(v time.Time) *ModelAvailabilityUpdate {
	_u.mutation.SetLastSeenOkAt(v)
	return _u
}

// SetNillableLastSeenOkAt sets the "last_seen_ok_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableLastSeenOkAt(v *time.Time) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetLastSeenOkAt(*v)
	}
	return _u
}

// ClearLastSeenOkAt clears the value of the "last_seen_ok_at" field.
func (_u *ModelAvailabilityUpdate) ClearLastSeenOkAt() *ModelAvailabilityUpdate {
	_u.mutation.ClearLastSeenOkAt()
	return _u
}

// SetLastFailureAt sets the "last_failure_at" field.
func (_u *ModelAvailabilityUpdate) SetLastFailureAt(v time.Time) *ModelAvailabilityUpdate {
	_u.mutation.SetLastFailureAt(v)
	return _u
}

// SetNillableLastFailureAt sets the "last_failure_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableLastFailureAt(v *time.Time) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetLastFailureAt(*v)
	}
	return _u
}

// ClearLastFailureAt clears the value of the "last_failure_at" field.
func (_u *ModelAvailabilityUpdate) ClearLastFailureAt() *ModelAvailabilityUpdate {
	_u.mutation.ClearLastFailureAt()
	return _u
}

// SetLastFailureKind sets the "last_failure_kind" field.
func (_u *ModelAvailabilityUpdate) SetLastFailureKind(v string) *ModelAvailabilityUpdate {
	_u.mutation.SetLastFailureKind(v)
	return _u
}

// SetNillableLastFailureKind sets the "last_failure_kind" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableLastFailureKind(v *string) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetLastFailureKind(*v)
	}
	return _u
}

// SetUpstreamStatusCodeLast sets the "upstream_status_code_last" field.
func (_u *ModelAvailabilityUpdate) SetUpstreamStatusCodeLast(v int) *ModelAvailabilityUpdate {
	_u.mutation.ResetUpstreamStatusCodeLast()
	_u.mutation.SetUpstreamStatusCodeLast(v)
	return _u
}

// SetNillableUpstreamStatusCodeLast sets the "upstream_status_code_last" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableUpstreamStatusCodeLast(v *int) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetUpstreamStatusCodeLast(*v)
	}
	return _u
}

// AddUpstreamStatusCodeLast adds value to the "upstream_status_code_last" field.
func (_u *ModelAvailabilityUpdate) AddUpstreamStatusCodeLast(v int) *ModelAvailabilityUpdate {
	_u.mutation.AddUpstreamStatusCodeLast(v)
	return _u
}

// ClearUpstreamStatusCodeLast clears the value of the "upstream_status_code_last" field.
func (_u *ModelAvailabilityUpdate) ClearUpstreamStatusCodeLast() *ModelAvailabilityUpdate {
	_u.mutation.ClearUpstreamStatusCodeLast()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *ModelAvailabilityUpdate) SetLastCheckedAt(v time.Time) *ModelAvailabilityUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableLastCheckedAt(v *time.Time) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *ModelAvailabilityUpdate) ClearLastCheckedAt() *ModelAvailabilityUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetSampleOk24h sets the "sample_ok_24h" field.
func (_u *ModelAvailabilityUpdate) SetSampleOk24h(v int) *ModelAvailabilityUpdate {
	_u.mutation.ResetSampleOk24h()
	_u.mutation.SetSampleOk24h(v)
	return _u
}

// SetNillableSampleOk24h sets the "sample_ok_24h" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableSampleOk24h(v *int) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetSampleOk24h(*v)
	}
	return _u
}

// AddSampleOk24h adds value to the "sample_ok_24h" field.
func (_u *ModelAvailabilityUpdate) AddSampleOk24h(v int) *ModelAvailabilityUpdate {
	_u.mutation.AddSampleOk24h(v)
	return _u
}

// SetSampleTotal24h sets the "sample_total_24h" field.
func (_u *ModelAvailabilityUpdate) SetSampleTotal24h(v int) *ModelAvailabilityUpdate {
	_u.mutation.ResetSampleTotal24h()
	_u.mutation.SetSampleTotal24h(v)
	return _u
}

// SetNillableSampleTotal24h sets the "sample_total_24h" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableSampleTotal24h(v *int) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetSampleTotal24h(*v)
	}
	return _u
}

// AddSampleTotal24h adds value to the "sample_total_24h" field.
func (_u *ModelAvailabilityUpdate) AddSampleTotal24h(v int) *ModelAvailabilityUpdate {
	_u.mutation.AddSampleTotal24h(v)
	return _u
}

// SetRollingWindowStartedAt sets the "rolling_window_started_at" field.
func (_u *ModelAvailabilityUpdate) SetRollingWindowStartedAt(v time.Time) *ModelAvailabilityUpdate {
	_u.mutation.SetRollingWindowStartedAt(v)
	return _u
}

// SetNillableRollingWindowStartedAt sets the "rolling_window_started_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableRollingWindowStartedAt(v *time.Time) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetRollingWindowStartedAt(*v)
	}
	return _u
}

// ClearRollingWindowStartedAt clears the value of the "rolling_window_started_at" field.
func (_u *ModelAvailabilityUpdate) ClearRollingWindowStartedAt() *ModelAvailabilityUpdate {
	_u.mutation.ClearRollingWindowStartedAt()
	return _u
}

// SetLastAccountID sets the "last_account_id" field.
func (_u *ModelAvailabilityUpdate) SetLastAccountID(v int64) *ModelAvailabilityUpdate {
	_u.mutation.ResetLastAccountID()
	_u.mutation.SetLastAccountID(v)
	return _u
}

// SetNillableLastAccountID sets the "last_account_id" field if the given value is not nil.
func (_u *ModelAvailabilityUpdate) SetNillableLastAccountID(v *int64) *ModelAvailabilityUpdate {
	if v != nil {
		_u.SetLastAccountID(*v)
	}
	return _u
}

// AddLastAccountID adds value to the "last_account_id" field.
func (_u *ModelAvailabilityUpdate) AddLastAccountID(v int64) *ModelAvailabilityUpdate {
	_u.mutation.AddLastAccountID(v)
	return _u
}

// ClearLastAccountID clears the value of the "last_account_id" field.
func (_u *ModelAvailabilityUpdate) ClearLastAccountID() *ModelAvailabilityUpdate {
	_u.mutation.ClearLastAccountID()
	return _u
}

// Mutation returns the ModelAvailabilityMutation object of the builder.
func (_u *ModelAvailabilityUpdate) Mutation() *ModelAvailabilityMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelAvailabilityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelAvailabilityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelAvailabilityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelAvailabilityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelAvailabilityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelavailability.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelAvailabilityUpdate) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelavailability.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelavailability.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelavailability.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastFailureKind(); ok {
		if err := modelavailability.LastFailureKindValidator(v); err != nil {
			return &ValidationError{Name: "last_failure_kind", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.last_failure_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelAvailabilityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelavailability.Table, modelavailability.Columns, sqlgraph.NewFieldSpec(modelavailability.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelavailability.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelavailability.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelavailability.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelavailability.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeenOkAt(); ok {
		_spec.SetField(modelavailability.FieldLastSeenOkAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenOkAtCleared() {
		_spec.ClearField(modelavailability.FieldLastSeenOkAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFailureAt(); ok {
		_spec.SetField(modelavailability.FieldLastFailureAt, field.TypeTime, value)
	}
	if _u.mutation.LastFailureAtCleared() {
		_spec.ClearField(modelavailability.FieldLastFailureAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFailureKind(); ok {
		_spec.SetField(modelavailability.FieldLastFailureKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamStatusCodeLast(); ok {
		_spec.SetField(modelavailability.FieldUpstreamStatusCodeLast, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpstreamStatusCodeLast(); ok {
		_spec.AddField(modelavailability.FieldUpstreamStatusCodeLast, field.TypeInt, value)
	}
	if _u.mutation.UpstreamStatusCodeLastCleared() {
		_spec.ClearField(modelavailability.FieldUpstreamStatusCodeLast, field.TypeInt)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(modelavailability.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(modelavailability.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SampleOk24h(); ok {
		_spec.SetField(modelavailability.FieldSampleOk24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSampleOk24h(); ok {
		_spec.AddField(modelavailability.FieldSampleOk24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SampleTotal24h(); ok {
		_spec.SetField(modelavailability.FieldSampleTotal24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSampleTotal24h(); ok {
		_spec.AddField(modelavailability.FieldSampleTotal24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RollingWindowStartedAt(); ok {
		_spec.SetField(modelavailability.FieldRollingWindowStartedAt, field.TypeTime, value)
	}
	if _u.mutation.RollingWindowStartedAtCleared() {
		_spec.ClearField(modelavailability.FieldRollingWindowStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAccountID(); ok {
		_spec.SetField(modelavailability.FieldLastAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastAccountID(); ok {
		_spec.AddField(modelavailability.FieldLastAccountID, field.TypeInt64, value)
	}
	if _u.mutation.LastAccountIDCleared() {
		_spec.ClearField(modelavailability.FieldLastAccountID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelavailability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelAvailabilityUpdateOne is the builder for updating a single ModelAvailability entity.
type ModelAvailabilityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelAvailabilityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelAvailabilityUpdateOne) SetUpdatedAt(v time.Time) *ModelAvailabilityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *ModelAvailabilityUpdateOne) SetPlatform(v modelavailability.Platform) *ModelAvailabilityUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillablePlatform(v *modelavailability.Platform) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ModelAvailabilityUpdateOne) SetModelID(v string) *ModelAvailabilityUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableModelID(v *string) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelAvailabilityUpdateOne) SetStatus(v modelavailability.Status) *ModelAvailabilityUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableStatus(v *modelavailability.Status) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetLastSeenOkAt sets the "last_seen_ok_at" field.
func (_u *ModelAvailabilityUpdateOne) SetLastSeenOkAt(v time.Time) *ModelAvailabilityUpdateOne {
	_u.mutation.SetLastSeenOkAt(v)
	return _u
}

// SetNillableLastSeenOkAt sets the "last_seen_ok_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableLastSeenOkAt(v *time.Time) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetLastSeenOkAt(*v)
	}
	return _u
}

// ClearLastSeenOkAt clears the value of the "last_seen_ok_at" field.
func (_u *ModelAvailabilityUpdateOne) ClearLastSeenOkAt() *ModelAvailabilityUpdateOne {
	_u.mutation.ClearLastSeenOkAt()
	return _u
}

// SetLastFailureAt sets the "last_failure_at" field.
func (_u *ModelAvailabilityUpdateOne) SetLastFailureAt(v time.Time) *ModelAvailabilityUpdateOne {
	_u.mutation.SetLastFailureAt(v)
	return _u
}

// SetNillableLastFailureAt sets the "last_failure_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableLastFailureAt(v *time.Time) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetLastFailureAt(*v)
	}
	return _u
}

// ClearLastFailureAt clears the value of the "last_failure_at" field.
func (_u *ModelAvailabilityUpdateOne) ClearLastFailureAt() *ModelAvailabilityUpdateOne {
	_u.mutation.ClearLastFailureAt()
	return _u
}

// SetLastFailureKind sets the "last_failure_kind" field.
func (_u *ModelAvailabilityUpdateOne) SetLastFailureKind(v string) *ModelAvailabilityUpdateOne {
	_u.mutation.SetLastFailureKind(v)
	return _u
}

// SetNillableLastFailureKind sets the "last_failure_kind" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableLastFailureKind(v *string) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetLastFailureKind(*v)
	}
	return _u
}

// SetUpstreamStatusCodeLast sets the "upstream_status_code_last" field.
func (_u *ModelAvailabilityUpdateOne) SetUpstreamStatusCodeLast(v int) *ModelAvailabilityUpdateOne {
	_u.mutation.ResetUpstreamStatusCodeLast()
	_u.mutation.SetUpstreamStatusCodeLast(v)
	return _u
}

// SetNillableUpstreamStatusCodeLast sets the "upstream_status_code_last" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableUpstreamStatusCodeLast(v *int) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetUpstreamStatusCodeLast(*v)
	}
	return _u
}

// AddUpstreamStatusCodeLast adds value to the "upstream_status_code_last" field.
func (_u *ModelAvailabilityUpdateOne) AddUpstreamStatusCodeLast(v int) *ModelAvailabilityUpdateOne {
	_u.mutation.AddUpstreamStatusCodeLast(v)
	return _u
}

// ClearUpstreamStatusCodeLast clears the value of the "upstream_status_code_last" field.
func (_u *ModelAvailabilityUpdateOne) ClearUpstreamStatusCodeLast() *ModelAvailabilityUpdateOne {
	_u.mutation.ClearUpstreamStatusCodeLast()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *ModelAvailabilityUpdateOne) SetLastCheckedAt(v time.Time) *ModelAvailabilityUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableLastCheckedAt(v *time.Time) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *ModelAvailabilityUpdateOne) ClearLastCheckedAt() *ModelAvailabilityUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetSampleOk24h sets the "sample_ok_24h" field.
func (_u *ModelAvailabilityUpdateOne) SetSampleOk24h(v int) *ModelAvailabilityUpdateOne {
	_u.mutation.ResetSampleOk24h()
	_u.mutation.SetSampleOk24h(v)
	return _u
}

// SetNillableSampleOk24h sets the "sample_ok_24h" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableSampleOk24h(v *int) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetSampleOk24h(*v)
	}
	return _u
}

// AddSampleOk24h adds value to the "sample_ok_24h" field.
func (_u *ModelAvailabilityUpdateOne) AddSampleOk24h(v int) *ModelAvailabilityUpdateOne {
	_u.mutation.AddSampleOk24h(v)
	return _u
}

// SetSampleTotal24h sets the "sample_total_24h" field.
func (_u *ModelAvailabilityUpdateOne) SetSampleTotal24h(v int) *ModelAvailabilityUpdateOne {
	_u.mutation.ResetSampleTotal24h()
	_u.mutation.SetSampleTotal24h(v)
	return _u
}

// SetNillableSampleTotal24h sets the "sample_total_24h" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableSampleTotal24h(v *int) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetSampleTotal24h(*v)
	}
	return _u
}

// AddSampleTotal24h adds value to the "sample_total_24h" field.
func (_u *ModelAvailabilityUpdateOne) AddSampleTotal24h(v int) *ModelAvailabilityUpdateOne {
	_u.mutation.AddSampleTotal24h(v)
	return _u
}

// SetRollingWindowStartedAt sets the "rolling_window_started_at" field.
func (_u *ModelAvailabilityUpdateOne) SetRollingWindowStartedAt(v time.Time) *ModelAvailabilityUpdateOne {
	_u.mutation.SetRollingWindowStartedAt(v)
	return _u
}

// SetNillableRollingWindowStartedAt sets the "rolling_window_started_at" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableRollingWindowStartedAt(v *time.Time) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetRollingWindowStartedAt(*v)
	}
	return _u
}

// ClearRollingWindowStartedAt clears the value of the "rolling_window_started_at" field.
func (_u *ModelAvailabilityUpdateOne) ClearRollingWindowStartedAt() *ModelAvailabilityUpdateOne {
	_u.mutation.ClearRollingWindowStartedAt()
	return _u
}

// SetLastAccountID sets the "last_account_id" field.
func (_u *ModelAvailabilityUpdateOne) SetLastAccountID(v int64) *ModelAvailabilityUpdateOne {
	_u.mutation.ResetLastAccountID()
	_u.mutation.SetLastAccountID(v)
	return _u
}

// SetNillableLastAccountID sets the "last_account_id" field if the given value is not nil.
func (_u *ModelAvailabilityUpdateOne) SetNillableLastAccountID(v *int64) *ModelAvailabilityUpdateOne {
	if v != nil {
		_u.SetLastAccountID(*v)
	}
	return _u
}

// AddLastAccountID adds value to the "last_account_id" field.
func (_u *ModelAvailabilityUpdateOne) AddLastAccountID(v int64) *ModelAvailabilityUpdateOne {
	_u.mutation.AddLastAccountID(v)
	return _u
}

// ClearLastAccountID clears the value of the "last_account_id" field.
func (_u *ModelAvailabilityUpdateOne) ClearLastAccountID() *ModelAvailabilityUpdateOne {
	_u.mutation.ClearLastAccountID()
	return _u
}

// Mutation returns the ModelAvailabilityMutation object of the builder.
func (_u *ModelAvailabilityUpdateOne) Mutation() *ModelAvailabilityMutation {
	return _u.mutation
}

// Where appends a list predicates to the ModelAvailabilityUpdate builder.
func (_u *ModelAvailabilityUpdateOne) Where(ps ...predicate.ModelAvailability) *ModelAvailabilityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelAvailabilityUpdateOne) Select(field string, fields ...string) *ModelAvailabilityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelAvailability entity.
func (_u *ModelAvailabilityUpdateOne) Save(ctx context.Context) (*ModelAvailability, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelAvailabilityUpdateOne) SaveX(ctx context.Context) *ModelAvailability {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelAvailabilityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelAvailabilityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelAvailabilityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelavailability.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelAvailabilityUpdateOne) check() error {
	if v, ok := _u.mutation.Platform(); ok {
		if err := modelavailability.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModelID(); ok {
		if err := modelavailability.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelavailability.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastFailureKind(); ok {
		if err := modelavailability.LastFailureKindValidator(v); err != nil {
			return &ValidationError{Name: "last_failure_kind", err: fmt.Errorf(`ent: validator failed for field "ModelAvailability.last_failure_kind": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelAvailabilityUpdateOne) sqlSave(ctx context.Context) (_node *ModelAvailability, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelavailability.Table, modelavailability.Columns, sqlgraph.NewFieldSpec(modelavailability.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelAvailability.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelavailability.FieldID)
		for _, f := range fields {
			if !modelavailability.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelavailability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelavailability.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(modelavailability.FieldPlatform, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(modelavailability.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelavailability.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LastSeenOkAt(); ok {
		_spec.SetField(modelavailability.FieldLastSeenOkAt, field.TypeTime, value)
	}
	if _u.mutation.LastSeenOkAtCleared() {
		_spec.ClearField(modelavailability.FieldLastSeenOkAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFailureAt(); ok {
		_spec.SetField(modelavailability.FieldLastFailureAt, field.TypeTime, value)
	}
	if _u.mutation.LastFailureAtCleared() {
		_spec.ClearField(modelavailability.FieldLastFailureAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastFailureKind(); ok {
		_spec.SetField(modelavailability.FieldLastFailureKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamStatusCodeLast(); ok {
		_spec.SetField(modelavailability.FieldUpstreamStatusCodeLast, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpstreamStatusCodeLast(); ok {
		_spec.AddField(modelavailability.FieldUpstreamStatusCodeLast, field.TypeInt, value)
	}
	if _u.mutation.UpstreamStatusCodeLastCleared() {
		_spec.ClearField(modelavailability.FieldUpstreamStatusCodeLast, field.TypeInt)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(modelavailability.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(modelavailability.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SampleOk24h(); ok {
		_spec.SetField(modelavailability.FieldSampleOk24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSampleOk24h(); ok {
		_spec.AddField(modelavailability.FieldSampleOk24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SampleTotal24h(); ok {
		_spec.SetField(modelavailability.FieldSampleTotal24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSampleTotal24h(); ok {
		_spec.AddField(modelavailability.FieldSampleTotal24h, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RollingWindowStartedAt(); ok {
		_spec.SetField(modelavailability.FieldRollingWindowStartedAt, field.TypeTime, value)
	}
	if _u.mutation.RollingWindowStartedAtCleared() {
		_spec.ClearField(modelavailability.FieldRollingWindowStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastAccountID(); ok {
		_spec.SetField(modelavailability.FieldLastAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastAccountID(); ok {
		_spec.AddField(modelavailability.FieldLastAccountID, field.TypeInt64, value)
	}
	if _u.mutation.LastAccountIDCleared() {
		_spec.ClearField(modelavailability.FieldLastAccountID, field.TypeInt64)
	}
	_node = &ModelAvailability{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelavailability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
