// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/qaarchiveshard"
)

// QAArchiveShardUpdate is the builder for updating QAArchiveShard entities.
type QAArchiveShardUpdate struct {
	config
	hooks    []Hook
	mutation *QAArchiveShardMutation
}

// Where appends a list predicates to the QAArchiveShardUpdate builder.
func (_u *QAArchiveShardUpdate) Where(ps ...predicate.QAArchiveShard) *QAArchiveShardUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWindowEnd sets the "window_end" field.
func (_u *QAArchiveShardUpdate) SetWindowEnd(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableWindowEnd(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *QAArchiveShardUpdate) SetGeneration(v int) *QAArchiveShardUpdate {
	_u.mutation.ResetGeneration()
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableGeneration(v *int) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// AddGeneration adds value to the "generation" field.
func (_u *QAArchiveShardUpdate) AddGeneration(v int) *QAArchiveShardUpdate {
	_u.mutation.AddGeneration(v)
	return _u
}

// SetState sets the "state" field.
func (_u *QAArchiveShardUpdate) SetState(v string) *QAArchiveShardUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableState(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *QAArchiveShardUpdate) SetRecordCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableRecordCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *QAArchiveShardUpdate) AddRecordCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddRecordCount(v)
	return _u
}

// SetBlobRefCount sets the "blob_ref_count" field.
func (_u *QAArchiveShardUpdate) SetBlobRefCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetBlobRefCount()
	_u.mutation.SetBlobRefCount(v)
	return _u
}

// SetNillableBlobRefCount sets the "blob_ref_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableBlobRefCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetBlobRefCount(*v)
	}
	return _u
}

// AddBlobRefCount adds value to the "blob_ref_count" field.
func (_u *QAArchiveShardUpdate) AddBlobRefCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddBlobRefCount(v)
	return _u
}

// SetBlobPresentCount sets the "blob_present_count" field.
func (_u *QAArchiveShardUpdate) SetBlobPresentCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetBlobPresentCount()
	_u.mutation.SetBlobPresentCount(v)
	return _u
}

// SetNillableBlobPresentCount sets the "blob_present_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableBlobPresentCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetBlobPresentCount(*v)
	}
	return _u
}

// AddBlobPresentCount adds value to the "blob_present_count" field.
func (_u *QAArchiveShardUpdate) AddBlobPresentCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddBlobPresentCount(v)
	return _u
}

// SetBlobMissingCount sets the "blob_missing_count" field.
func (_u *QAArchiveShardUpdate) SetBlobMissingCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetBlobMissingCount()
	_u.mutation.SetBlobMissingCount(v)
	return _u
}

// SetNillableBlobMissingCount sets the "blob_missing_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableBlobMissingCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetBlobMissingCount(*v)
	}
	return _u
}

// AddBlobMissingCount adds value to the "blob_missing_count" field.
func (_u *QAArchiveShardUpdate) AddBlobMissingCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddBlobMissingCount(v)
	return _u
}

// SetLogicalBytes sets the "logical_bytes" field.
func (_u *QAArchiveShardUpdate) SetLogicalBytes(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetLogicalBytes()
	_u.mutation.SetLogicalBytes(v)
	return _u
}

// SetNillableLogicalBytes sets the "logical_bytes" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableLogicalBytes(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetLogicalBytes(*v)
	}
	return _u
}

// AddLogicalBytes adds value to the "logical_bytes" field.
func (_u *QAArchiveShardUpdate) AddLogicalBytes(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddLogicalBytes(v)
	return _u
}

// SetArtifactBytes sets the "artifact_bytes" field.
func (_u *QAArchiveShardUpdate) SetArtifactBytes(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetArtifactBytes()
	_u.mutation.SetArtifactBytes(v)
	return _u
}

// SetNillableArtifactBytes sets the "artifact_bytes" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableArtifactBytes(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetArtifactBytes(*v)
	}
	return _u
}

// AddArtifactBytes adds value to the "artifact_bytes" field.
func (_u *QAArchiveShardUpdate) AddArtifactBytes(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddArtifactBytes(v)
	return _u
}

// SetChecksums sets the "checksums" field.
func (_u *QAArchiveShardUpdate) SetChecksums(v map[string]string) *QAArchiveShardUpdate {
	_u.mutation.SetChecksums(v)
	return _u
}

// SetS3Prefix sets the "s3_prefix" field.
func (_u *QAArchiveShardUpdate) SetS3Prefix(v string) *QAArchiveShardUpdate {
	_u.mutation.SetS3Prefix(v)
	return _u
}

// SetNillableS3Prefix sets the "s3_prefix" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableS3Prefix(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetS3Prefix(*v)
	}
	return _u
}

// SetManifestKey sets the "manifest_key" field.
func (_u *QAArchiveShardUpdate) SetManifestKey(v string) *QAArchiveShardUpdate {
	_u.mutation.SetManifestKey(v)
	return _u
}

// SetNillableManifestKey sets the "manifest_key" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableManifestKey(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetManifestKey(*v)
	}
	return _u
}

// ClearManifestKey clears the value of the "manifest_key" field.
func (_u *QAArchiveShardUpdate) ClearManifestKey() *QAArchiveShardUpdate {
	_u.mutation.ClearManifestKey()
	return _u
}

// SetCommitKey sets the "commit_key" field.
func (_u *QAArchiveShardUpdate) SetCommitKey(v string) *QAArchiveShardUpdate {
	_u.mutation.SetCommitKey(v)
	return _u
}

// SetNillableCommitKey sets the "commit_key" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableCommitKey(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetCommitKey(*v)
	}
	return _u
}

// ClearCommitKey clears the value of the "commit_key" field.
func (_u *QAArchiveShardUpdate) ClearCommitKey() *QAArchiveShardUpdate {
	_u.mutation.ClearCommitKey()
	return _u
}

// SetCommitEtag sets the "commit_etag" field.
func (_u *QAArchiveShardUpdate) SetCommitEtag(v string) *QAArchiveShardUpdate {
	_u.mutation.SetCommitEtag(v)
	return _u
}

// SetNillableCommitEtag sets the "commit_etag" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableCommitEtag(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetCommitEtag(*v)
	}
	return _u
}

// ClearCommitEtag clears the value of the "commit_etag" field.
func (_u *QAArchiveShardUpdate) ClearCommitEtag() *QAArchiveShardUpdate {
	_u.mutation.ClearCommitEtag()
	return _u
}

// SetAggregateRecordCount sets the "aggregate_record_count" field.
func (_u *QAArchiveShardUpdate) SetAggregateRecordCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetAggregateRecordCount()
	_u.mutation.SetAggregateRecordCount(v)
	return _u
}

// SetNillableAggregateRecordCount sets the "aggregate_record_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableAggregateRecordCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetAggregateRecordCount(*v)
	}
	return _u
}

// AddAggregateRecordCount adds value to the "aggregate_record_count" field.
func (_u *QAArchiveShardUpdate) AddAggregateRecordCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddAggregateRecordCount(v)
	return _u
}

// SetAggregateBlobRefCount sets the "aggregate_blob_ref_count" field.
func (_u *QAArchiveShardUpdate) SetAggregateBlobRefCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetAggregateBlobRefCount()
	_u.mutation.SetAggregateBlobRefCount(v)
	return _u
}

// SetNillableAggregateBlobRefCount sets the "aggregate_blob_ref_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableAggregateBlobRefCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetAggregateBlobRefCount(*v)
	}
	return _u
}

// AddAggregateBlobRefCount adds value to the "aggregate_blob_ref_count" field.
func (_u *QAArchiveShardUpdate) AddAggregateBlobRefCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddAggregateBlobRefCount(v)
	return _u
}

// SetAggregateBlobPresentCount sets the "aggregate_blob_present_count" field.
func (_u *QAArchiveShardUpdate) SetAggregateBlobPresentCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetAggregateBlobPresentCount()
	_u.mutation.SetAggregateBlobPresentCount(v)
	return _u
}

// SetNillableAggregateBlobPresentCount sets the "aggregate_blob_present_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableAggregateBlobPresentCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetAggregateBlobPresentCount(*v)
	}
	return _u
}

// AddAggregateBlobPresentCount adds value to the "aggregate_blob_present_count" field.
func (_u *QAArchiveShardUpdate) AddAggregateBlobPresentCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddAggregateBlobPresentCount(v)
	return _u
}

// SetAggregateBlobMissingCount sets the "aggregate_blob_missing_count" field.
func (_u *QAArchiveShardUpdate) SetAggregateBlobMissingCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.ResetAggregateBlobMissingCount()
	_u.mutation.SetAggregateBlobMissingCount(v)
	return _u
}

// SetNillableAggregateBlobMissingCount sets the "aggregate_blob_missing_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableAggregateBlobMissingCount(v *int64) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetAggregateBlobMissingCount(*v)
	}
	return _u
}

// AddAggregateBlobMissingCount adds value to the "aggregate_blob_missing_count" field.
func (_u *QAArchiveShardUpdate) AddAggregateBlobMissingCount(v int64) *QAArchiveShardUpdate {
	_u.mutation.AddAggregateBlobMissingCount(v)
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *QAArchiveShardUpdate) SetVerifiedAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableVerifiedAt(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *QAArchiveShardUpdate) ClearVerifiedAt() *QAArchiveShardUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetRestoreVerifiedAt sets the "restore_verified_at" field.
func (_u *QAArchiveShardUpdate) SetRestoreVerifiedAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetRestoreVerifiedAt(v)
	return _u
}

// SetNillableRestoreVerifiedAt sets the "restore_verified_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableRestoreVerifiedAt(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetRestoreVerifiedAt(*v)
	}
	return _u
}

// ClearRestoreVerifiedAt clears the value of the "restore_verified_at" field.
func (_u *QAArchiveShardUpdate) ClearRestoreVerifiedAt() *QAArchiveShardUpdate {
	_u.mutation.ClearRestoreVerifiedAt()
	return _u
}

// SetVerificationErrorCode sets the "verification_error_code" field.
func (_u *QAArchiveShardUpdate) SetVerificationErrorCode(v string) *QAArchiveShardUpdate {
	_u.mutation.SetVerificationErrorCode(v)
	return _u
}

// SetNillableVerificationErrorCode sets the "verification_error_code" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableVerificationErrorCode(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetVerificationErrorCode(*v)
	}
	return _u
}

// ClearVerificationErrorCode clears the value of the "verification_error_code" field.
func (_u *QAArchiveShardUpdate) ClearVerificationErrorCode() *QAArchiveShardUpdate {
	_u.mutation.ClearVerificationErrorCode()
	return _u
}

// SetLastReconciledAt sets the "last_reconciled_at" field.
func (_u *QAArchiveShardUpdate) SetLastReconciledAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetLastReconciledAt(v)
	return _u
}

// SetNillableLastReconciledAt sets the "last_reconciled_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableLastReconciledAt(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetLastReconciledAt(*v)
	}
	return _u
}

// ClearLastReconciledAt clears the value of the "last_reconciled_at" field.
func (_u *QAArchiveShardUpdate) ClearLastReconciledAt() *QAArchiveShardUpdate {
	_u.mutation.ClearLastReconciledAt()
	return _u
}

// SetFinalReconciledAt sets the "final_reconciled_at" field.
func (_u *QAArchiveShardUpdate) SetFinalReconciledAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetFinalReconciledAt(v)
	return _u
}

// SetNillableFinalReconciledAt sets the "final_reconciled_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableFinalReconciledAt(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetFinalReconciledAt(*v)
	}
	return _u
}

// ClearFinalReconciledAt clears the value of the "final_reconciled_at" field.
func (_u *QAArchiveShardUpdate) ClearFinalReconciledAt() *QAArchiveShardUpdate {
	_u.mutation.ClearFinalReconciledAt()
	return _u
}

// SetCleanupEligible sets the "cleanup_eligible" field.
func (_u *QAArchiveShardUpdate) SetCleanupEligible(v bool) *QAArchiveShardUpdate {
	_u.mutation.SetCleanupEligible(v)
	return _u
}

// SetNillableCleanupEligible sets the "cleanup_eligible" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableCleanupEligible(v *bool) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetCleanupEligible(*v)
	}
	return _u
}

// SetForwardCutover sets the "forward_cutover" field.
func (_u *QAArchiveShardUpdate) SetForwardCutover(v bool) *QAArchiveShardUpdate {
	_u.mutation.SetForwardCutover(v)
	return _u
}

// SetNillableForwardCutover sets the "forward_cutover" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableForwardCutover(v *bool) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetForwardCutover(*v)
	}
	return _u
}

// SetFirstAttemptAt sets the "first_attempt_at" field.
func (_u *QAArchiveShardUpdate) SetFirstAttemptAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetFirstAttemptAt(v)
	return _u
}

// SetNillableFirstAttemptAt sets the "first_attempt_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableFirstAttemptAt(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetFirstAttemptAt(*v)
	}
	return _u
}

// ClearFirstAttemptAt clears the value of the "first_attempt_at" field.
func (_u *QAArchiveShardUpdate) ClearFirstAttemptAt() *QAArchiveShardUpdate {
	_u.mutation.ClearFirstAttemptAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *QAArchiveShardUpdate) SetCompletedAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableCompletedAt(v *time.Time) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *QAArchiveShardUpdate) ClearCompletedAt() *QAArchiveShardUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *QAArchiveShardUpdate) SetLastError(v string) *QAArchiveShardUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *QAArchiveShardUpdate) SetNillableLastError(v *string) *QAArchiveShardUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *QAArchiveShardUpdate) ClearLastError() *QAArchiveShardUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QAArchiveShardUpdate) SetUpdatedAt(v time.Time) *QAArchiveShardUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the QAArchiveShardMutation object of the builder.
func (_u *QAArchiveShardUpdate) Mutation() *QAArchiveShardMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QAArchiveShardUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QAArchiveShardUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QAArchiveShardUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QAArchiveShardUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QAArchiveShardUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := qaarchiveshard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *QAArchiveShardUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(qaarchiveshard.Table, qaarchiveshard.Columns, sqlgraph.NewFieldSpec(qaarchiveshard.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(qaarchiveshard.FieldWindowEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(qaarchiveshard.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGeneration(); ok {
		_spec.AddField(qaarchiveshard.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(qaarchiveshard.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(qaarchiveshard.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(qaarchiveshard.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobRefCount(); ok {
		_spec.SetField(qaarchiveshard.FieldBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlobRefCount(); ok {
		_spec.AddField(qaarchiveshard.FieldBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobPresentCount(); ok {
		_spec.SetField(qaarchiveshard.FieldBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlobPresentCount(); ok {
		_spec.AddField(qaarchiveshard.FieldBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobMissingCount(); ok {
		_spec.SetField(qaarchiveshard.FieldBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlobMissingCount(); ok {
		_spec.AddField(qaarchiveshard.FieldBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LogicalBytes(); ok {
		_spec.SetField(qaarchiveshard.FieldLogicalBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLogicalBytes(); ok {
		_spec.AddField(qaarchiveshard.FieldLogicalBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ArtifactBytes(); ok {
		_spec.SetField(qaarchiveshard.FieldArtifactBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedArtifactBytes(); ok {
		_spec.AddField(qaarchiveshard.FieldArtifactBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Checksums(); ok {
		_spec.SetField(qaarchiveshard.FieldChecksums, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.S3Prefix(); ok {
		_spec.SetField(qaarchiveshard.FieldS3Prefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManifestKey(); ok {
		_spec.SetField(qaarchiveshard.FieldManifestKey, field.TypeString, value)
	}
	if _u.mutation.ManifestKeyCleared() {
		_spec.ClearField(qaarchiveshard.FieldManifestKey, field.TypeString)
	}
	if value, ok := _u.mutation.CommitKey(); ok {
		_spec.SetField(qaarchiveshard.FieldCommitKey, field.TypeString, value)
	}
	if _u.mutation.CommitKeyCleared() {
		_spec.ClearField(qaarchiveshard.FieldCommitKey, field.TypeString)
	}
	if value, ok := _u.mutation.CommitEtag(); ok {
		_spec.SetField(qaarchiveshard.FieldCommitEtag, field.TypeString, value)
	}
	if _u.mutation.CommitEtagCleared() {
		_spec.ClearField(qaarchiveshard.FieldCommitEtag, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateRecordCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateRecordCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateBlobRefCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateBlobRefCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateBlobPresentCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateBlobPresentCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateBlobMissingCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateBlobMissingCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RestoreVerifiedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldRestoreVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.RestoreVerifiedAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldRestoreVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VerificationErrorCode(); ok {
		_spec.SetField(qaarchiveshard.FieldVerificationErrorCode, field.TypeString, value)
	}
	if _u.mutation.VerificationErrorCodeCleared() {
		_spec.ClearField(qaarchiveshard.FieldVerificationErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastReconciledAt(); ok {
		_spec.SetField(qaarchiveshard.FieldLastReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.LastReconciledAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldLastReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinalReconciledAt(); ok {
		_spec.SetField(qaarchiveshard.FieldFinalReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.FinalReconciledAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldFinalReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CleanupEligible(); ok {
		_spec.SetField(qaarchiveshard.FieldCleanupEligible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ForwardCutover(); ok {
		_spec.SetField(qaarchiveshard.FieldForwardCutover, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FirstAttemptAt(); ok {
		_spec.SetField(qaarchiveshard.FieldFirstAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.FirstAttemptAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldFirstAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(qaarchiveshard.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(qaarchiveshard.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{qaarchiveshard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QAArchiveShardUpdateOne is the builder for updating a single QAArchiveShard entity.
type QAArchiveShardUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QAArchiveShardMutation
}

// SetWindowEnd sets the "window_end" field.
func (_u *QAArchiveShardUpdateOne) SetWindowEnd(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetWindowEnd(v)
	return _u
}

// SetNillableWindowEnd sets the "window_end" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableWindowEnd(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetWindowEnd(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *QAArchiveShardUpdateOne) SetGeneration(v int) *QAArchiveShardUpdateOne {
	_u.mutation.ResetGeneration()
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableGeneration(v *int) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// AddGeneration adds value to the "generation" field.
func (_u *QAArchiveShardUpdateOne) AddGeneration(v int) *QAArchiveShardUpdateOne {
	_u.mutation.AddGeneration(v)
	return _u
}

// SetState sets the "state" field.
func (_u *QAArchiveShardUpdateOne) SetState(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableState(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetRecordCount sets the "record_count" field.
func (_u *QAArchiveShardUpdateOne) SetRecordCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetRecordCount()
	_u.mutation.SetRecordCount(v)
	return _u
}

// SetNillableRecordCount sets the "record_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableRecordCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetRecordCount(*v)
	}
	return _u
}

// AddRecordCount adds value to the "record_count" field.
func (_u *QAArchiveShardUpdateOne) AddRecordCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddRecordCount(v)
	return _u
}

// SetBlobRefCount sets the "blob_ref_count" field.
func (_u *QAArchiveShardUpdateOne) SetBlobRefCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetBlobRefCount()
	_u.mutation.SetBlobRefCount(v)
	return _u
}

// SetNillableBlobRefCount sets the "blob_ref_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableBlobRefCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetBlobRefCount(*v)
	}
	return _u
}

// AddBlobRefCount adds value to the "blob_ref_count" field.
func (_u *QAArchiveShardUpdateOne) AddBlobRefCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddBlobRefCount(v)
	return _u
}

// SetBlobPresentCount sets the "blob_present_count" field.
func (_u *QAArchiveShardUpdateOne) SetBlobPresentCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetBlobPresentCount()
	_u.mutation.SetBlobPresentCount(v)
	return _u
}

// SetNillableBlobPresentCount sets the "blob_present_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableBlobPresentCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetBlobPresentCount(*v)
	}
	return _u
}

// AddBlobPresentCount adds value to the "blob_present_count" field.
func (_u *QAArchiveShardUpdateOne) AddBlobPresentCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddBlobPresentCount(v)
	return _u
}

// SetBlobMissingCount sets the "blob_missing_count" field.
func (_u *QAArchiveShardUpdateOne) SetBlobMissingCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetBlobMissingCount()
	_u.mutation.SetBlobMissingCount(v)
	return _u
}

// SetNillableBlobMissingCount sets the "blob_missing_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableBlobMissingCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetBlobMissingCount(*v)
	}
	return _u
}

// AddBlobMissingCount adds value to the "blob_missing_count" field.
func (_u *QAArchiveShardUpdateOne) AddBlobMissingCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddBlobMissingCount(v)
	return _u
}

// SetLogicalBytes sets the "logical_bytes" field.
func (_u *QAArchiveShardUpdateOne) SetLogicalBytes(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetLogicalBytes()
	_u.mutation.SetLogicalBytes(v)
	return _u
}

// SetNillableLogicalBytes sets the "logical_bytes" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableLogicalBytes(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetLogicalBytes(*v)
	}
	return _u
}

// AddLogicalBytes adds value to the "logical_bytes" field.
func (_u *QAArchiveShardUpdateOne) AddLogicalBytes(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddLogicalBytes(v)
	return _u
}

// SetArtifactBytes sets the "artifact_bytes" field.
func (_u *QAArchiveShardUpdateOne) SetArtifactBytes(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetArtifactBytes()
	_u.mutation.SetArtifactBytes(v)
	return _u
}

// SetNillableArtifactBytes sets the "artifact_bytes" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableArtifactBytes(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetArtifactBytes(*v)
	}
	return _u
}

// AddArtifactBytes adds value to the "artifact_bytes" field.
func (_u *QAArchiveShardUpdateOne) AddArtifactBytes(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddArtifactBytes(v)
	return _u
}

// SetChecksums sets the "checksums" field.
func (_u *QAArchiveShardUpdateOne) SetChecksums(v map[string]string) *QAArchiveShardUpdateOne {
	_u.mutation.SetChecksums(v)
	return _u
}

// SetS3Prefix sets the "s3_prefix" field.
func (_u *QAArchiveShardUpdateOne) SetS3Prefix(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetS3Prefix(v)
	return _u
}

// SetNillableS3Prefix sets the "s3_prefix" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableS3Prefix(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetS3Prefix(*v)
	}
	return _u
}

// SetManifestKey sets the "manifest_key" field.
func (_u *QAArchiveShardUpdateOne) SetManifestKey(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetManifestKey(v)
	return _u
}

// SetNillableManifestKey sets the "manifest_key" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableManifestKey(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetManifestKey(*v)
	}
	return _u
}

// ClearManifestKey clears the value of the "manifest_key" field.
func (_u *QAArchiveShardUpdateOne) ClearManifestKey() *QAArchiveShardUpdateOne {
	_u.mutation.ClearManifestKey()
	return _u
}

// SetCommitKey sets the "commit_key" field.
func (_u *QAArchiveShardUpdateOne) SetCommitKey(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetCommitKey(v)
	return _u
}

// SetNillableCommitKey sets the "commit_key" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableCommitKey(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetCommitKey(*v)
	}
	return _u
}

// ClearCommitKey clears the value of the "commit_key" field.
func (_u *QAArchiveShardUpdateOne) ClearCommitKey() *QAArchiveShardUpdateOne {
	_u.mutation.ClearCommitKey()
	return _u
}

// SetCommitEtag sets the "commit_etag" field.
func (_u *QAArchiveShardUpdateOne) SetCommitEtag(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetCommitEtag(v)
	return _u
}

// SetNillableCommitEtag sets the "commit_etag" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableCommitEtag(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetCommitEtag(*v)
	}
	return _u
}

// ClearCommitEtag clears the value of the "commit_etag" field.
func (_u *QAArchiveShardUpdateOne) ClearCommitEtag() *QAArchiveShardUpdateOne {
	_u.mutation.ClearCommitEtag()
	return _u
}

// SetAggregateRecordCount sets the "aggregate_record_count" field.
func (_u *QAArchiveShardUpdateOne) SetAggregateRecordCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetAggregateRecordCount()
	_u.mutation.SetAggregateRecordCount(v)
	return _u
}

// SetNillableAggregateRecordCount sets the "aggregate_record_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableAggregateRecordCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetAggregateRecordCount(*v)
	}
	return _u
}

// AddAggregateRecordCount adds value to the "aggregate_record_count" field.
func (_u *QAArchiveShardUpdateOne) AddAggregateRecordCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddAggregateRecordCount(v)
	return _u
}

// SetAggregateBlobRefCount sets the "aggregate_blob_ref_count" field.
func (_u *QAArchiveShardUpdateOne) SetAggregateBlobRefCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetAggregateBlobRefCount()
	_u.mutation.SetAggregateBlobRefCount(v)
	return _u
}

// SetNillableAggregateBlobRefCount sets the "aggregate_blob_ref_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableAggregateBlobRefCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetAggregateBlobRefCount(*v)
	}
	return _u
}

// AddAggregateBlobRefCount adds value to the "aggregate_blob_ref_count" field.
func (_u *QAArchiveShardUpdateOne) AddAggregateBlobRefCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddAggregateBlobRefCount(v)
	return _u
}

// SetAggregateBlobPresentCount sets the "aggregate_blob_present_count" field.
func (_u *QAArchiveShardUpdateOne) SetAggregateBlobPresentCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetAggregateBlobPresentCount()
	_u.mutation.SetAggregateBlobPresentCount(v)
	return _u
}

// SetNillableAggregateBlobPresentCount sets the "aggregate_blob_present_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableAggregateBlobPresentCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetAggregateBlobPresentCount(*v)
	}
	return _u
}

// AddAggregateBlobPresentCount adds value to the "aggregate_blob_present_count" field.
func (_u *QAArchiveShardUpdateOne) AddAggregateBlobPresentCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddAggregateBlobPresentCount(v)
	return _u
}

// SetAggregateBlobMissingCount sets the "aggregate_blob_missing_count" field.
func (_u *QAArchiveShardUpdateOne) SetAggregateBlobMissingCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.ResetAggregateBlobMissingCount()
	_u.mutation.SetAggregateBlobMissingCount(v)
	return _u
}

// SetNillableAggregateBlobMissingCount sets the "aggregate_blob_missing_count" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableAggregateBlobMissingCount(v *int64) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetAggregateBlobMissingCount(*v)
	}
	return _u
}

// AddAggregateBlobMissingCount adds value to the "aggregate_blob_missing_count" field.
func (_u *QAArchiveShardUpdateOne) AddAggregateBlobMissingCount(v int64) *QAArchiveShardUpdateOne {
	_u.mutation.AddAggregateBlobMissingCount(v)
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *QAArchiveShardUpdateOne) SetVerifiedAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableVerifiedAt(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *QAArchiveShardUpdateOne) ClearVerifiedAt() *QAArchiveShardUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetRestoreVerifiedAt sets the "restore_verified_at" field.
func (_u *QAArchiveShardUpdateOne) SetRestoreVerifiedAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetRestoreVerifiedAt(v)
	return _u
}

// SetNillableRestoreVerifiedAt sets the "restore_verified_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableRestoreVerifiedAt(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetRestoreVerifiedAt(*v)
	}
	return _u
}

// ClearRestoreVerifiedAt clears the value of the "restore_verified_at" field.
func (_u *QAArchiveShardUpdateOne) ClearRestoreVerifiedAt() *QAArchiveShardUpdateOne {
	_u.mutation.ClearRestoreVerifiedAt()
	return _u
}

// SetVerificationErrorCode sets the "verification_error_code" field.
func (_u *QAArchiveShardUpdateOne) SetVerificationErrorCode(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetVerificationErrorCode(v)
	return _u
}

// SetNillableVerificationErrorCode sets the "verification_error_code" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableVerificationErrorCode(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetVerificationErrorCode(*v)
	}
	return _u
}

// ClearVerificationErrorCode clears the value of the "verification_error_code" field.
func (_u *QAArchiveShardUpdateOne) ClearVerificationErrorCode() *QAArchiveShardUpdateOne {
	_u.mutation.ClearVerificationErrorCode()
	return _u
}

// SetLastReconciledAt sets the "last_reconciled_at" field.
func (_u *QAArchiveShardUpdateOne) SetLastReconciledAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetLastReconciledAt(v)
	return _u
}

// SetNillableLastReconciledAt sets the "last_reconciled_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableLastReconciledAt(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetLastReconciledAt(*v)
	}
	return _u
}

// ClearLastReconciledAt clears the value of the "last_reconciled_at" field.
func (_u *QAArchiveShardUpdateOne) ClearLastReconciledAt() *QAArchiveShardUpdateOne {
	_u.mutation.ClearLastReconciledAt()
	return _u
}

// SetFinalReconciledAt sets the "final_reconciled_at" field.
func (_u *QAArchiveShardUpdateOne) SetFinalReconciledAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetFinalReconciledAt(v)
	return _u
}

// SetNillableFinalReconciledAt sets the "final_reconciled_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableFinalReconciledAt(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetFinalReconciledAt(*v)
	}
	return _u
}

// ClearFinalReconciledAt clears the value of the "final_reconciled_at" field.
func (_u *QAArchiveShardUpdateOne) ClearFinalReconciledAt() *QAArchiveShardUpdateOne {
	_u.mutation.ClearFinalReconciledAt()
	return _u
}

// SetCleanupEligible sets the "cleanup_eligible" field.
func (_u *QAArchiveShardUpdateOne) SetCleanupEligible(v bool) *QAArchiveShardUpdateOne {
	_u.mutation.SetCleanupEligible(v)
	return _u
}

// SetNillableCleanupEligible sets the "cleanup_eligible" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableCleanupEligible(v *bool) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetCleanupEligible(*v)
	}
	return _u
}

// SetForwardCutover sets the "forward_cutover" field.
func (_u *QAArchiveShardUpdateOne) SetForwardCutover(v bool) *QAArchiveShardUpdateOne {
	_u.mutation.SetForwardCutover(v)
	return _u
}

// SetNillableForwardCutover sets the "forward_cutover" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableForwardCutover(v *bool) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetForwardCutover(*v)
	}
	return _u
}

// SetFirstAttemptAt sets the "first_attempt_at" field.
func (_u *QAArchiveShardUpdateOne) SetFirstAttemptAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetFirstAttemptAt(v)
	return _u
}

// SetNillableFirstAttemptAt sets the "first_attempt_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableFirstAttemptAt(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetFirstAttemptAt(*v)
	}
	return _u
}

// ClearFirstAttemptAt clears the value of the "first_attempt_at" field.
func (_u *QAArchiveShardUpdateOne) ClearFirstAttemptAt() *QAArchiveShardUpdateOne {
	_u.mutation.ClearFirstAttemptAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *QAArchiveShardUpdateOne) SetCompletedAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableCompletedAt(v *time.Time) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *QAArchiveShardUpdateOne) ClearCompletedAt() *QAArchiveShardUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *QAArchiveShardUpdateOne) SetLastError(v string) *QAArchiveShardUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *QAArchiveShardUpdateOne) SetNillableLastError(v *string) *QAArchiveShardUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *QAArchiveShardUpdateOne) ClearLastError() *QAArchiveShardUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *QAArchiveShardUpdateOne) SetUpdatedAt(v time.Time) *QAArchiveShardUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the QAArchiveShardMutation object of the builder.
func (_u *QAArchiveShardUpdateOne) Mutation() *QAArchiveShardMutation {
	return _u.mutation
}

// Where appends a list predicates to the QAArchiveShardUpdate builder.
func (_u *QAArchiveShardUpdateOne) Where(ps ...predicate.QAArchiveShard) *QAArchiveShardUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QAArchiveShardUpdateOne) Select(field string, fields ...string) *QAArchiveShardUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated QAArchiveShard entity.
func (_u *QAArchiveShardUpdateOne) Save(ctx context.Context) (*QAArchiveShard, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QAArchiveShardUpdateOne) SaveX(ctx context.Context) *QAArchiveShard {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QAArchiveShardUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QAArchiveShardUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *QAArchiveShardUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := qaarchiveshard.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *QAArchiveShardUpdateOne) sqlSave(ctx context.Context) (_node *QAArchiveShard, err error) {
	_spec := sqlgraph.NewUpdateSpec(qaarchiveshard.Table, qaarchiveshard.Columns, sqlgraph.NewFieldSpec(qaarchiveshard.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "QAArchiveShard.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, qaarchiveshard.FieldID)
		for _, f := range fields {
			if !qaarchiveshard.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != qaarchiveshard.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WindowEnd(); ok {
		_spec.SetField(qaarchiveshard.FieldWindowEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(qaarchiveshard.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGeneration(); ok {
		_spec.AddField(qaarchiveshard.FieldGeneration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(qaarchiveshard.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecordCount(); ok {
		_spec.SetField(qaarchiveshard.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRecordCount(); ok {
		_spec.AddField(qaarchiveshard.FieldRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobRefCount(); ok {
		_spec.SetField(qaarchiveshard.FieldBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlobRefCount(); ok {
		_spec.AddField(qaarchiveshard.FieldBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobPresentCount(); ok {
		_spec.SetField(qaarchiveshard.FieldBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlobPresentCount(); ok {
		_spec.AddField(qaarchiveshard.FieldBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.BlobMissingCount(); ok {
		_spec.SetField(qaarchiveshard.FieldBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBlobMissingCount(); ok {
		_spec.AddField(qaarchiveshard.FieldBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LogicalBytes(); ok {
		_spec.SetField(qaarchiveshard.FieldLogicalBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLogicalBytes(); ok {
		_spec.AddField(qaarchiveshard.FieldLogicalBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ArtifactBytes(); ok {
		_spec.SetField(qaarchiveshard.FieldArtifactBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedArtifactBytes(); ok {
		_spec.AddField(qaarchiveshard.FieldArtifactBytes, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Checksums(); ok {
		_spec.SetField(qaarchiveshard.FieldChecksums, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.S3Prefix(); ok {
		_spec.SetField(qaarchiveshard.FieldS3Prefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.ManifestKey(); ok {
		_spec.SetField(qaarchiveshard.FieldManifestKey, field.TypeString, value)
	}
	if _u.mutation.ManifestKeyCleared() {
		_spec.ClearField(qaarchiveshard.FieldManifestKey, field.TypeString)
	}
	if value, ok := _u.mutation.CommitKey(); ok {
		_spec.SetField(qaarchiveshard.FieldCommitKey, field.TypeString, value)
	}
	if _u.mutation.CommitKeyCleared() {
		_spec.ClearField(qaarchiveshard.FieldCommitKey, field.TypeString)
	}
	if value, ok := _u.mutation.CommitEtag(); ok {
		_spec.SetField(qaarchiveshard.FieldCommitEtag, field.TypeString, value)
	}
	if _u.mutation.CommitEtagCleared() {
		_spec.ClearField(qaarchiveshard.FieldCommitEtag, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateRecordCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateRecordCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateRecordCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateBlobRefCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateBlobRefCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateBlobRefCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateBlobPresentCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateBlobPresentCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateBlobPresentCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateBlobMissingCount(); ok {
		_spec.SetField(qaarchiveshard.FieldAggregateBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateBlobMissingCount(); ok {
		_spec.AddField(qaarchiveshard.FieldAggregateBlobMissingCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RestoreVerifiedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldRestoreVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.RestoreVerifiedAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldRestoreVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VerificationErrorCode(); ok {
		_spec.SetField(qaarchiveshard.FieldVerificationErrorCode, field.TypeString, value)
	}
	if _u.mutation.VerificationErrorCodeCleared() {
		_spec.ClearField(qaarchiveshard.FieldVerificationErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.LastReconciledAt(); ok {
		_spec.SetField(qaarchiveshard.FieldLastReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.LastReconciledAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldLastReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinalReconciledAt(); ok {
		_spec.SetField(qaarchiveshard.FieldFinalReconciledAt, field.TypeTime, value)
	}
	if _u.mutation.FinalReconciledAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldFinalReconciledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CleanupEligible(); ok {
		_spec.SetField(qaarchiveshard.FieldCleanupEligible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ForwardCutover(); ok {
		_spec.SetField(qaarchiveshard.FieldForwardCutover, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FirstAttemptAt(); ok {
		_spec.SetField(qaarchiveshard.FieldFirstAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.FirstAttemptAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldFirstAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(qaarchiveshard.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(qaarchiveshard.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(qaarchiveshard.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(qaarchiveshard.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &QAArchiveShard{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{qaarchiveshard.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
