// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/qaexportjob"
)

// QAExportJob is the model entity for the QAExportJob schema.
type QAExportJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ExportKind holds the value of the "export_kind" field.
	ExportKind string `json:"export_kind,omitempty"`
	// Format holds the value of the "format" field.
	Format string `json:"format,omitempty"`
	// WindowStart holds the value of the "window_start" field.
	WindowStart *time.Time `json:"window_start,omitempty"`
	// WindowEnd holds the value of the "window_end" field.
	WindowEnd *time.Time `json:"window_end,omitempty"`
	// StorageKey holds the value of the "storage_key" field.
	StorageKey string `json:"storage_key,omitempty"`
	// RecordCount holds the value of the "record_count" field.
	RecordCount int `json:"record_count,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QAExportJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case qaexportjob.FieldID, qaexportjob.FieldUserID, qaexportjob.FieldAPIKeyID, qaexportjob.FieldRecordCount:
			values[i] = new(sql.NullInt64)
		case qaexportjob.FieldJobID, qaexportjob.FieldStatus, qaexportjob.FieldExportKind, qaexportjob.FieldFormat, qaexportjob.FieldStorageKey, qaexportjob.FieldError:
			values[i] = new(sql.NullString)
		case qaexportjob.FieldCreatedAt, qaexportjob.FieldUpdatedAt, qaexportjob.FieldWindowStart, qaexportjob.FieldWindowEnd, qaexportjob.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QAExportJob fields.
func (_m *QAExportJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case qaexportjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case qaexportjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case qaexportjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case qaexportjob.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case qaexportjob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case qaexportjob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case qaexportjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case qaexportjob.FieldExportKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field export_kind", values[i])
			} else if value.Valid {
				_m.ExportKind = value.String
			}
		case qaexportjob.FieldFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field format", values[i])
			} else if value.Valid {
				_m.Format = value.String
			}
		case qaexportjob.FieldWindowStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_start", values[i])
			} else if value.Valid {
				_m.WindowStart = new(time.Time)
				*_m.WindowStart = value.Time
			}
		case qaexportjob.FieldWindowEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field window_end", values[i])
			} else if value.Valid {
				_m.WindowEnd = new(time.Time)
				*_m.WindowEnd = value.Time
			}
		case qaexportjob.FieldStorageKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field storage_key", values[i])
			} else if value.Valid {
				_m.StorageKey = value.String
			}
		case qaexportjob.FieldRecordCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field record_count", values[i])
			} else if value.Valid {
				_m.RecordCount = int(value.Int64)
			}
		case qaexportjob.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = new(string)
				*_m.Error = value.String
			}
		case qaexportjob.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QAExportJob.
// This includes values selected through modifiers, order, etc.
func (_m *QAExportJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this QAExportJob.
// Note that you need to call QAExportJob.Unwrap() before calling this method if this QAExportJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QAExportJob) Update() *QAExportJobUpdateOne {
	return NewQAExportJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QAExportJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QAExportJob) Unwrap() *QAExportJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QAExportJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QAExportJob) String() string {
	var builder strings.Builder
	builder.WriteString("QAExportJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("export_kind=")
	builder.WriteString(_m.ExportKind)
	builder.WriteString(", ")
	builder.WriteString("format=")
	builder.WriteString(_m.Format)
	builder.WriteString(", ")
	if v := _m.WindowStart; v != nil {
		builder.WriteString("window_start=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.WindowEnd; v != nil {
		builder.WriteString("window_end=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("storage_key=")
	builder.WriteString(_m.StorageKey)
	builder.WriteString(", ")
	builder.WriteString("record_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecordCount))
	builder.WriteString(", ")
	if v := _m.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// QAExportJobs is a parsable slice of QAExportJob.
type QAExportJobs []*QAExportJob
