// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/qarecord"
)

// QARecordCreate is the builder for creating a QARecord entity.
type QARecordCreate struct {
	config
	mutation *QARecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *QARecordCreate) SetRequestID(v string) *QARecordCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *QARecordCreate) SetUserID(v int64) *QARecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *QARecordCreate) SetAPIKeyID(v int64) *QARecordCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *QARecordCreate) SetAccountID(v int64) *QARecordCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableAccountID(v *int64) *QARecordCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *QARecordCreate) SetPlatform(v string) *QARecordCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_c *QARecordCreate) SetNillablePlatform(v *string) *QARecordCreate {
	if v != nil {
		_c.SetPlatform(*v)
	}
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *QARecordCreate) SetRequestedModel(v string) *QARecordCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableRequestedModel(v *string) *QARecordCreate {
	if v != nil {
		_c.SetRequestedModel(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *QARecordCreate) SetUpstreamModel(v string) *QARecordCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableUpstreamModel(v *string) *QARecordCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (_c *QARecordCreate) SetInboundEndpoint(v string) *QARecordCreate {
	_c.mutation.SetInboundEndpoint(v)
	return _c
}

// SetNillableInboundEndpoint sets the "inbound_endpoint" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableInboundEndpoint(v *string) *QARecordCreate {
	if v != nil {
		_c.SetInboundEndpoint(*v)
	}
	return _c
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_c *QARecordCreate) SetUpstreamEndpoint(v string) *QARecordCreate {
	_c.mutation.SetUpstreamEndpoint(v)
	return _c
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableUpstreamEndpoint(v *string) *QARecordCreate {
	if v != nil {
		_c.SetUpstreamEndpoint(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *QARecordCreate) SetStatusCode(v int) *QARecordCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableStatusCode(v *int) *QARecordCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *QARecordCreate) SetDurationMs(v int64) *QARecordCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableDurationMs(v *int64) *QARecordCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (_c *QARecordCreate) SetFirstTokenMs(v int64) *QARecordCreate {
	_c.mutation.SetFirstTokenMs(v)
	return _c
}

// SetNillableFirstTokenMs sets the "first_token_ms" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableFirstTokenMs(v *int64) *QARecordCreate {
	if v != nil {
		_c.SetFirstTokenMs(*v)
	}
	return _c
}

// SetStream sets the "stream" field.
func (_c *QARecordCreate) SetStream(v bool) *QARecordCreate {
	_c.mutation.SetStream(v)
	return _c
}

// SetNillableStream sets the "stream" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableStream(v *bool) *QARecordCreate {
	if v != nil {
		_c.SetStream(*v)
	}
	return _c
}

// SetToolCallsPresent sets the "tool_calls_present" field.
func (_c *QARecordCreate) SetToolCallsPresent(v bool) *QARecordCreate {
	_c.mutation.SetToolCallsPresent(v)
	return _c
}

// SetNillableToolCallsPresent sets the "tool_calls_present" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableToolCallsPresent(v *bool) *QARecordCreate {
	if v != nil {
		_c.SetToolCallsPresent(*v)
	}
	return _c
}

// SetMultimodalPresent sets the "multimodal_present" field.
func (_c *QARecordCreate) SetMultimodalPresent(v bool) *QARecordCreate {
	_c.mutation.SetMultimodalPresent(v)
	return _c
}

// SetNillableMultimodalPresent sets the "multimodal_present" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableMultimodalPresent(v *bool) *QARecordCreate {
	if v != nil {
		_c.SetMultimodalPresent(*v)
	}
	return _c
}

// SetInputTokens sets the "input_tokens" field.
func (_c *QARecordCreate) SetInputTokens(v int) *QARecordCreate {
	_c.mutation.SetInputTokens(v)
	return _c
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableInputTokens(v *int) *QARecordCreate {
	if v != nil {
		_c.SetInputTokens(*v)
	}
	return _c
}

// SetOutputTokens sets the "output_tokens" field.
func (_c *QARecordCreate) SetOutputTokens(v int) *QARecordCreate {
	_c.mutation.SetOutputTokens(v)
	return _c
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableOutputTokens(v *int) *QARecordCreate {
	if v != nil {
		_c.SetOutputTokens(*v)
	}
	return _c
}

// SetCachedTokens sets the "cached_tokens" field.
func (_c *QARecordCreate) SetCachedTokens(v int) *QARecordCreate {
	_c.mutation.SetCachedTokens(v)
	return _c
}

// SetNillableCachedTokens sets the "cached_tokens" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableCachedTokens(v *int) *QARecordCreate {
	if v != nil {
		_c.SetCachedTokens(*v)
	}
	return _c
}

// SetRequestSha256 sets the "request_sha256" field.
func (_c *QARecordCreate) SetRequestSha256(v string) *QARecordCreate {
	_c.mutation.SetRequestSha256(v)
	return _c
}

// SetNillableRequestSha256 sets the "request_sha256" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableRequestSha256(v *string) *QARecordCreate {
	if v != nil {
		_c.SetRequestSha256(*v)
	}
	return _c
}

// SetResponseSha256 sets the "response_sha256" field.
func (_c *QARecordCreate) SetResponseSha256(v string) *QARecordCreate {
	_c.mutation.SetResponseSha256(v)
	return _c
}

// SetNillableResponseSha256 sets the "response_sha256" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableResponseSha256(v *string) *QARecordCreate {
	if v != nil {
		_c.SetResponseSha256(*v)
	}
	return _c
}

// SetBlobURI sets the "blob_uri" field.
func (_c *QARecordCreate) SetBlobURI(v string) *QARecordCreate {
	_c.mutation.SetBlobURI(v)
	return _c
}

// SetNillableBlobURI sets the "blob_uri" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableBlobURI(v *string) *QARecordCreate {
	if v != nil {
		_c.SetBlobURI(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *QARecordCreate) SetTags(v []string) *QARecordCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QARecordCreate) SetCreatedAt(v time.Time) *QARecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QARecordCreate) SetNillableCreatedAt(v *time.Time) *QARecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRetentionUntil sets the "retention_until" field.
func (_c *QARecordCreate) SetRetentionUntil(v time.Time) *QARecordCreate {
	_c.mutation.SetRetentionUntil(v)
	return _c
}

// Mutation returns the QARecordMutation object of the builder.
func (_c *QARecordCreate) Mutation() *QARecordMutation {
	return _c.mutation
}

// Save creates the QARecord in the database.
func (_c *QARecordCreate) Save(ctx context.Context) (*QARecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QARecordCreate) SaveX(ctx context.Context) *QARecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QARecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QARecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QARecordCreate) defaults() {
	if _, ok := _c.mutation.Platform(); !ok {
		v := qarecord.DefaultPlatform
		_c.mutation.SetPlatform(v)
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		v := qarecord.DefaultRequestedModel
		_c.mutation.SetRequestedModel(v)
	}
	if _, ok := _c.mutation.InboundEndpoint(); !ok {
		v := qarecord.DefaultInboundEndpoint
		_c.mutation.SetInboundEndpoint(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := qarecord.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := qarecord.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.Stream(); !ok {
		v := qarecord.DefaultStream
		_c.mutation.SetStream(v)
	}
	if _, ok := _c.mutation.ToolCallsPresent(); !ok {
		v := qarecord.DefaultToolCallsPresent
		_c.mutation.SetToolCallsPresent(v)
	}
	if _, ok := _c.mutation.MultimodalPresent(); !ok {
		v := qarecord.DefaultMultimodalPresent
		_c.mutation.SetMultimodalPresent(v)
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		v := qarecord.DefaultInputTokens
		_c.mutation.SetInputTokens(v)
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		v := qarecord.DefaultOutputTokens
		_c.mutation.SetOutputTokens(v)
	}
	if _, ok := _c.mutation.CachedTokens(); !ok {
		v := qarecord.DefaultCachedTokens
		_c.mutation.SetCachedTokens(v)
	}
	if _, ok := _c.mutation.RequestSha256(); !ok {
		v := qarecord.DefaultRequestSha256
		_c.mutation.SetRequestSha256(v)
	}
	if _, ok := _c.mutation.ResponseSha256(); !ok {
		v := qarecord.DefaultResponseSha256
		_c.mutation.SetResponseSha256(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := qarecord.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := qarecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QARecordCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "QARecord.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := qarecord.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "QARecord.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "QARecord.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "QARecord.api_key_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "QARecord.platform"`)}
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		return &ValidationError{Name: "requested_model", err: errors.New(`ent: missing required field "QARecord.requested_model"`)}
	}
	if _, ok := _c.mutation.InboundEndpoint(); !ok {
		return &ValidationError{Name: "inbound_endpoint", err: errors.New(`ent: missing required field "QARecord.inbound_endpoint"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "QARecord.status_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "QARecord.duration_ms"`)}
	}
	if _, ok := _c.mutation.Stream(); !ok {
		return &ValidationError{Name: "stream", err: errors.New(`ent: missing required field "QARecord.stream"`)}
	}
	if _, ok := _c.mutation.ToolCallsPresent(); !ok {
		return &ValidationError{Name: "tool_calls_present", err: errors.New(`ent: missing required field "QARecord.tool_calls_present"`)}
	}
	if _, ok := _c.mutation.MultimodalPresent(); !ok {
		return &ValidationError{Name: "multimodal_present", err: errors.New(`ent: missing required field "QARecord.multimodal_present"`)}
	}
	if _, ok := _c.mutation.InputTokens(); !ok {
		return &ValidationError{Name: "input_tokens", err: errors.New(`ent: missing required field "QARecord.input_tokens"`)}
	}
	if _, ok := _c.mutation.OutputTokens(); !ok {
		return &ValidationError{Name: "output_tokens", err: errors.New(`ent: missing required field "QARecord.output_tokens"`)}
	}
	if _, ok := _c.mutation.CachedTokens(); !ok {
		return &ValidationError{Name: "cached_tokens", err: errors.New(`ent: missing required field "QARecord.cached_tokens"`)}
	}
	if _, ok := _c.mutation.RequestSha256(); !ok {
		return &ValidationError{Name: "request_sha256", err: errors.New(`ent: missing required field "QARecord.request_sha256"`)}
	}
	if _, ok := _c.mutation.ResponseSha256(); !ok {
		return &ValidationError{Name: "response_sha256", err: errors.New(`ent: missing required field "QARecord.response_sha256"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "QARecord.tags"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QARecord.created_at"`)}
	}
	if _, ok := _c.mutation.RetentionUntil(); !ok {
		return &ValidationError{Name: "retention_until", err: errors.New(`ent: missing required field "QARecord.retention_until"`)}
	}
	return nil
}

func (_c *QARecordCreate) sqlSave(ctx context.Context) (*QARecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QARecordCreate) createSpec() (*QARecord, *sqlgraph.CreateSpec) {
	var (
		_node = &QARecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(qarecord.Table, sqlgraph.NewFieldSpec(qarecord.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(qarecord.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(qarecord.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(qarecord.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(qarecord.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(qarecord.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(qarecord.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(qarecord.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = &value
	}
	if value, ok := _c.mutation.InboundEndpoint(); ok {
		_spec.SetField(qarecord.FieldInboundEndpoint, field.TypeString, value)
		_node.InboundEndpoint = value
	}
	if value, ok := _c.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(qarecord.FieldUpstreamEndpoint, field.TypeString, value)
		_node.UpstreamEndpoint = &value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(qarecord.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(qarecord.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.FirstTokenMs(); ok {
		_spec.SetField(qarecord.FieldFirstTokenMs, field.TypeInt64, value)
		_node.FirstTokenMs = &value
	}
	if value, ok := _c.mutation.Stream(); ok {
		_spec.SetField(qarecord.FieldStream, field.TypeBool, value)
		_node.Stream = value
	}
	if value, ok := _c.mutation.ToolCallsPresent(); ok {
		_spec.SetField(qarecord.FieldToolCallsPresent, field.TypeBool, value)
		_node.ToolCallsPresent = value
	}
	if value, ok := _c.mutation.MultimodalPresent(); ok {
		_spec.SetField(qarecord.FieldMultimodalPresent, field.TypeBool, value)
		_node.MultimodalPresent = value
	}
	if value, ok := _c.mutation.InputTokens(); ok {
		_spec.SetField(qarecord.FieldInputTokens, field.TypeInt, value)
		_node.InputTokens = value
	}
	if value, ok := _c.mutation.OutputTokens(); ok {
		_spec.SetField(qarecord.FieldOutputTokens, field.TypeInt, value)
		_node.OutputTokens = value
	}
	if value, ok := _c.mutation.CachedTokens(); ok {
		_spec.SetField(qarecord.FieldCachedTokens, field.TypeInt, value)
		_node.CachedTokens = value
	}
	if value, ok := _c.mutation.RequestSha256(); ok {
		_spec.SetField(qarecord.FieldRequestSha256, field.TypeString, value)
		_node.RequestSha256 = value
	}
	if value, ok := _c.mutation.ResponseSha256(); ok {
		_spec.SetField(qarecord.FieldResponseSha256, field.TypeString, value)
		_node.ResponseSha256 = value
	}
	if value, ok := _c.mutation.BlobURI(); ok {
		_spec.SetField(qarecord.FieldBlobURI, field.TypeString, value)
		_node.BlobURI = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(qarecord.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(qarecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.RetentionUntil(); ok {
		_spec.SetField(qarecord.FieldRetentionUntil, field.TypeTime, value)
		_node.RetentionUntil = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QARecord.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QARecordUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *QARecordCreate) OnConflict(opts ...sql.ConflictOption) *QARecordUpsertOne {
	_c.conflict = opts
	return &QARecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QARecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QARecordCreate) OnConflictColumns(columns ...string) *QARecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QARecordUpsertOne{
		create: _c,
	}
}

type (
	// QARecordUpsertOne is the builder for "upsert"-ing
	//  one QARecord node.
	QARecordUpsertOne struct {
		create *QARecordCreate
	}

	// QARecordUpsert is the "OnConflict" setter.
	QARecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *QARecordUpsert) SetRequestID(v string) *QARecordUpsert {
	u.Set(qarecord.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateRequestID() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldRequestID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *QARecordUpsert) SetUserID(v int64) *QARecordUpsert {
	u.Set(qarecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateUserID() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *QARecordUpsert) AddUserID(v int64) *QARecordUpsert {
	u.Add(qarecord.FieldUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *QARecordUpsert) SetAPIKeyID(v int64) *QARecordUpsert {
	u.Set(qarecord.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateAPIKeyID() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *QARecordUpsert) AddAPIKeyID(v int64) *QARecordUpsert {
	u.Add(qarecord.FieldAPIKeyID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *QARecordUpsert) SetAccountID(v int64) *QARecordUpsert {
	u.Set(qarecord.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateAccountID() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *QARecordUpsert) AddAccountID(v int64) *QARecordUpsert {
	u.Add(qarecord.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *QARecordUpsert) ClearAccountID() *QARecordUpsert {
	u.SetNull(qarecord.FieldAccountID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *QARecordUpsert) SetPlatform(v string) *QARecordUpsert {
	u.Set(qarecord.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *QARecordUpsert) UpdatePlatform() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldPlatform)
	return u
}

// SetRequestedModel sets the "requested_model" field.
func (u *QARecordUpsert) SetRequestedModel(v string) *QARecordUpsert {
	u.Set(qarecord.FieldRequestedModel, v)
	return u
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateRequestedModel() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldRequestedModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *QARecordUpsert) SetUpstreamModel(v string) *QARecordUpsert {
	u.Set(qarecord.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateUpstreamModel() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldUpstreamModel)
	return u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *QARecordUpsert) ClearUpstreamModel() *QARecordUpsert {
	u.SetNull(qarecord.FieldUpstreamModel)
	return u
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (u *QARecordUpsert) SetInboundEndpoint(v string) *QARecordUpsert {
	u.Set(qarecord.FieldInboundEndpoint, v)
	return u
}

// UpdateInboundEndpoint sets the "inbound_endpoint" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateInboundEndpoint() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldInboundEndpoint)
	return u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *QARecordUpsert) SetUpstreamEndpoint(v string) *QARecordUpsert {
	u.Set(qarecord.FieldUpstreamEndpoint, v)
	return u
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateUpstreamEndpoint() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldUpstreamEndpoint)
	return u
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (u *QARecordUpsert) ClearUpstreamEndpoint() *QARecordUpsert {
	u.SetNull(qarecord.FieldUpstreamEndpoint)
	return u
}

// SetStatusCode sets the "status_code" field.
func (u *QARecordUpsert) SetStatusCode(v int) *QARecordUpsert {
	u.Set(qarecord.FieldStatusCode, v)
	return u
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateStatusCode() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldStatusCode)
	return u
}

// AddStatusCode adds v to the "status_code" field.
func (u *QARecordUpsert) AddStatusCode(v int) *QARecordUpsert {
	u.Add(qarecord.FieldStatusCode, v)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *QARecordUpsert) SetDurationMs(v int64) *QARecordUpsert {
	u.Set(qarecord.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateDurationMs() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *QARecordUpsert) AddDurationMs(v int64) *QARecordUpsert {
	u.Add(qarecord.FieldDurationMs, v)
	return u
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *QARecordUpsert) SetFirstTokenMs(v int64) *QARecordUpsert {
	u.Set(qarecord.FieldFirstTokenMs, v)
	return u
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateFirstTokenMs() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldFirstTokenMs)
	return u
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *QARecordUpsert) AddFirstTokenMs(v int64) *QARecordUpsert {
	u.Add(qarecord.FieldFirstTokenMs, v)
	return u
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *QARecordUpsert) ClearFirstTokenMs() *QARecordUpsert {
	u.SetNull(qarecord.FieldFirstTokenMs)
	return u
}

// SetStream sets the "stream" field.
func (u *QARecordUpsert) SetStream(v bool) *QARecordUpsert {
	u.Set(qarecord.FieldStream, v)
	return u
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateStream() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldStream)
	return u
}

// SetToolCallsPresent sets the "tool_calls_present" field.
func (u *QARecordUpsert) SetToolCallsPresent(v bool) *QARecordUpsert {
	u.Set(qarecord.FieldToolCallsPresent, v)
	return u
}

// UpdateToolCallsPresent sets the "tool_calls_present" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateToolCallsPresent() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldToolCallsPresent)
	return u
}

// SetMultimodalPresent sets the "multimodal_present" field.
func (u *QARecordUpsert) SetMultimodalPresent(v bool) *QARecordUpsert {
	u.Set(qarecord.FieldMultimodalPresent, v)
	return u
}

// UpdateMultimodalPresent sets the "multimodal_present" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateMultimodalPresent() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldMultimodalPresent)
	return u
}

// SetInputTokens sets the "input_tokens" field.
func (u *QARecordUpsert) SetInputTokens(v int) *QARecordUpsert {
	u.Set(qarecord.FieldInputTokens, v)
	return u
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateInputTokens() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldInputTokens)
	return u
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *QARecordUpsert) AddInputTokens(v int) *QARecordUpsert {
	u.Add(qarecord.FieldInputTokens, v)
	return u
}

// SetOutputTokens sets the "output_tokens" field.
func (u *QARecordUpsert) SetOutputTokens(v int) *QARecordUpsert {
	u.Set(qarecord.FieldOutputTokens, v)
	return u
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateOutputTokens() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldOutputTokens)
	return u
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *QARecordUpsert) AddOutputTokens(v int) *QARecordUpsert {
	u.Add(qarecord.FieldOutputTokens, v)
	return u
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *QARecordUpsert) SetCachedTokens(v int) *QARecordUpsert {
	u.Set(qarecord.FieldCachedTokens, v)
	return u
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateCachedTokens() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldCachedTokens)
	return u
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *QARecordUpsert) AddCachedTokens(v int) *QARecordUpsert {
	u.Add(qarecord.FieldCachedTokens, v)
	return u
}

// SetRequestSha256 sets the "request_sha256" field.
func (u *QARecordUpsert) SetRequestSha256(v string) *QARecordUpsert {
	u.Set(qarecord.FieldRequestSha256, v)
	return u
}

// UpdateRequestSha256 sets the "request_sha256" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateRequestSha256() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldRequestSha256)
	return u
}

// SetResponseSha256 sets the "response_sha256" field.
func (u *QARecordUpsert) SetResponseSha256(v string) *QARecordUpsert {
	u.Set(qarecord.FieldResponseSha256, v)
	return u
}

// UpdateResponseSha256 sets the "response_sha256" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateResponseSha256() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldResponseSha256)
	return u
}

// SetBlobURI sets the "blob_uri" field.
func (u *QARecordUpsert) SetBlobURI(v string) *QARecordUpsert {
	u.Set(qarecord.FieldBlobURI, v)
	return u
}

// UpdateBlobURI sets the "blob_uri" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateBlobURI() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldBlobURI)
	return u
}

// ClearBlobURI clears the value of the "blob_uri" field.
func (u *QARecordUpsert) ClearBlobURI() *QARecordUpsert {
	u.SetNull(qarecord.FieldBlobURI)
	return u
}

// SetTags sets the "tags" field.
func (u *QARecordUpsert) SetTags(v []string) *QARecordUpsert {
	u.Set(qarecord.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateTags() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldTags)
	return u
}

// SetRetentionUntil sets the "retention_until" field.
func (u *QARecordUpsert) SetRetentionUntil(v time.Time) *QARecordUpsert {
	u.Set(qarecord.FieldRetentionUntil, v)
	return u
}

// UpdateRetentionUntil sets the "retention_until" field to the value that was provided on create.
func (u *QARecordUpsert) UpdateRetentionUntil() *QARecordUpsert {
	u.SetExcluded(qarecord.FieldRetentionUntil)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.QARecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QARecordUpsertOne) UpdateNewValues() *QARecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(qarecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QARecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QARecordUpsertOne) Ignore() *QARecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QARecordUpsertOne) DoNothing() *QARecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QARecordCreate.OnConflict
// documentation for more info.
func (u *QARecordUpsertOne) Update(set func(*QARecordUpsert)) *QARecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QARecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *QARecordUpsertOne) SetRequestID(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateRequestID() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *QARecordUpsertOne) SetUserID(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *QARecordUpsertOne) AddUserID(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateUserID() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *QARecordUpsertOne) SetAPIKeyID(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *QARecordUpsertOne) AddAPIKeyID(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateAPIKeyID() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *QARecordUpsertOne) SetAccountID(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *QARecordUpsertOne) AddAccountID(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateAccountID() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *QARecordUpsertOne) ClearAccountID() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *QARecordUpsertOne) SetPlatform(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdatePlatform() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdatePlatform()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *QARecordUpsertOne) SetRequestedModel(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateRequestedModel() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *QARecordUpsertOne) SetUpstreamModel(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateUpstreamModel() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateUpstreamModel()
	})
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *QARecordUpsertOne) ClearUpstreamModel() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearUpstreamModel()
	})
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (u *QARecordUpsertOne) SetInboundEndpoint(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetInboundEndpoint(v)
	})
}

// UpdateInboundEndpoint sets the "inbound_endpoint" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateInboundEndpoint() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateInboundEndpoint()
	})
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *QARecordUpsertOne) SetUpstreamEndpoint(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetUpstreamEndpoint(v)
	})
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateUpstreamEndpoint() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateUpstreamEndpoint()
	})
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (u *QARecordUpsertOne) ClearUpstreamEndpoint() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearUpstreamEndpoint()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *QARecordUpsertOne) SetStatusCode(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *QARecordUpsertOne) AddStatusCode(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateStatusCode() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *QARecordUpsertOne) SetDurationMs(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *QARecordUpsertOne) AddDurationMs(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateDurationMs() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateDurationMs()
	})
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *QARecordUpsertOne) SetFirstTokenMs(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetFirstTokenMs(v)
	})
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *QARecordUpsertOne) AddFirstTokenMs(v int64) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddFirstTokenMs(v)
	})
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateFirstTokenMs() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateFirstTokenMs()
	})
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *QARecordUpsertOne) ClearFirstTokenMs() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearFirstTokenMs()
	})
}

// SetStream sets the "stream" field.
func (u *QARecordUpsertOne) SetStream(v bool) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateStream() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateStream()
	})
}

// SetToolCallsPresent sets the "tool_calls_present" field.
func (u *QARecordUpsertOne) SetToolCallsPresent(v bool) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetToolCallsPresent(v)
	})
}

// UpdateToolCallsPresent sets the "tool_calls_present" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateToolCallsPresent() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateToolCallsPresent()
	})
}

// SetMultimodalPresent sets the "multimodal_present" field.
func (u *QARecordUpsertOne) SetMultimodalPresent(v bool) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetMultimodalPresent(v)
	})
}

// UpdateMultimodalPresent sets the "multimodal_present" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateMultimodalPresent() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateMultimodalPresent()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *QARecordUpsertOne) SetInputTokens(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *QARecordUpsertOne) AddInputTokens(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateInputTokens() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *QARecordUpsertOne) SetOutputTokens(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *QARecordUpsertOne) AddOutputTokens(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateOutputTokens() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *QARecordUpsertOne) SetCachedTokens(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetCachedTokens(v)
	})
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *QARecordUpsertOne) AddCachedTokens(v int) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.AddCachedTokens(v)
	})
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateCachedTokens() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateCachedTokens()
	})
}

// SetRequestSha256 sets the "request_sha256" field.
func (u *QARecordUpsertOne) SetRequestSha256(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRequestSha256(v)
	})
}

// UpdateRequestSha256 sets the "request_sha256" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateRequestSha256() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRequestSha256()
	})
}

// SetResponseSha256 sets the "response_sha256" field.
func (u *QARecordUpsertOne) SetResponseSha256(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetResponseSha256(v)
	})
}

// UpdateResponseSha256 sets the "response_sha256" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateResponseSha256() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateResponseSha256()
	})
}

// SetBlobURI sets the "blob_uri" field.
func (u *QARecordUpsertOne) SetBlobURI(v string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetBlobURI(v)
	})
}

// UpdateBlobURI sets the "blob_uri" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateBlobURI() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateBlobURI()
	})
}

// ClearBlobURI clears the value of the "blob_uri" field.
func (u *QARecordUpsertOne) ClearBlobURI() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearBlobURI()
	})
}

// SetTags sets the "tags" field.
func (u *QARecordUpsertOne) SetTags(v []string) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateTags() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateTags()
	})
}

// SetRetentionUntil sets the "retention_until" field.
func (u *QARecordUpsertOne) SetRetentionUntil(v time.Time) *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRetentionUntil(v)
	})
}

// UpdateRetentionUntil sets the "retention_until" field to the value that was provided on create.
func (u *QARecordUpsertOne) UpdateRetentionUntil() *QARecordUpsertOne {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRetentionUntil()
	})
}

// Exec executes the query.
func (u *QARecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QARecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QARecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QARecordUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QARecordUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QARecordCreateBulk is the builder for creating many QARecord entities in bulk.
type QARecordCreateBulk struct {
	config
	err      error
	builders []*QARecordCreate
	conflict []sql.ConflictOption
}

// Save creates the QARecord entities in the database.
func (_c *QARecordCreateBulk) Save(ctx context.Context) ([]*QARecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QARecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QARecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QARecordCreateBulk) SaveX(ctx context.Context) []*QARecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QARecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QARecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QARecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QARecordUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *QARecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *QARecordUpsertBulk {
	_c.conflict = opts
	return &QARecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QARecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QARecordCreateBulk) OnConflictColumns(columns ...string) *QARecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QARecordUpsertBulk{
		create: _c,
	}
}

// QARecordUpsertBulk is the builder for "upsert"-ing
// a bulk of QARecord nodes.
type QARecordUpsertBulk struct {
	create *QARecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QARecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *QARecordUpsertBulk) UpdateNewValues() *QARecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(qarecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QARecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QARecordUpsertBulk) Ignore() *QARecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QARecordUpsertBulk) DoNothing() *QARecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QARecordCreateBulk.OnConflict
// documentation for more info.
func (u *QARecordUpsertBulk) Update(set func(*QARecordUpsert)) *QARecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QARecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *QARecordUpsertBulk) SetRequestID(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateRequestID() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRequestID()
	})
}

// SetUserID sets the "user_id" field.
func (u *QARecordUpsertBulk) SetUserID(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *QARecordUpsertBulk) AddUserID(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateUserID() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *QARecordUpsertBulk) SetAPIKeyID(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *QARecordUpsertBulk) AddAPIKeyID(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateAPIKeyID() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *QARecordUpsertBulk) SetAccountID(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *QARecordUpsertBulk) AddAccountID(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateAccountID() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *QARecordUpsertBulk) ClearAccountID() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *QARecordUpsertBulk) SetPlatform(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdatePlatform() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdatePlatform()
	})
}

// SetRequestedModel sets the "requested_model" field.
func (u *QARecordUpsertBulk) SetRequestedModel(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRequestedModel(v)
	})
}

// UpdateRequestedModel sets the "requested_model" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateRequestedModel() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRequestedModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *QARecordUpsertBulk) SetUpstreamModel(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateUpstreamModel() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateUpstreamModel()
	})
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *QARecordUpsertBulk) ClearUpstreamModel() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearUpstreamModel()
	})
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (u *QARecordUpsertBulk) SetInboundEndpoint(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetInboundEndpoint(v)
	})
}

// UpdateInboundEndpoint sets the "inbound_endpoint" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateInboundEndpoint() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateInboundEndpoint()
	})
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (u *QARecordUpsertBulk) SetUpstreamEndpoint(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetUpstreamEndpoint(v)
	})
}

// UpdateUpstreamEndpoint sets the "upstream_endpoint" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateUpstreamEndpoint() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateUpstreamEndpoint()
	})
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (u *QARecordUpsertBulk) ClearUpstreamEndpoint() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearUpstreamEndpoint()
	})
}

// SetStatusCode sets the "status_code" field.
func (u *QARecordUpsertBulk) SetStatusCode(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetStatusCode(v)
	})
}

// AddStatusCode adds v to the "status_code" field.
func (u *QARecordUpsertBulk) AddStatusCode(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddStatusCode(v)
	})
}

// UpdateStatusCode sets the "status_code" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateStatusCode() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateStatusCode()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *QARecordUpsertBulk) SetDurationMs(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *QARecordUpsertBulk) AddDurationMs(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateDurationMs() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateDurationMs()
	})
}

// SetFirstTokenMs sets the "first_token_ms" field.
func (u *QARecordUpsertBulk) SetFirstTokenMs(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetFirstTokenMs(v)
	})
}

// AddFirstTokenMs adds v to the "first_token_ms" field.
func (u *QARecordUpsertBulk) AddFirstTokenMs(v int64) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddFirstTokenMs(v)
	})
}

// UpdateFirstTokenMs sets the "first_token_ms" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateFirstTokenMs() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateFirstTokenMs()
	})
}

// ClearFirstTokenMs clears the value of the "first_token_ms" field.
func (u *QARecordUpsertBulk) ClearFirstTokenMs() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearFirstTokenMs()
	})
}

// SetStream sets the "stream" field.
func (u *QARecordUpsertBulk) SetStream(v bool) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetStream(v)
	})
}

// UpdateStream sets the "stream" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateStream() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateStream()
	})
}

// SetToolCallsPresent sets the "tool_calls_present" field.
func (u *QARecordUpsertBulk) SetToolCallsPresent(v bool) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetToolCallsPresent(v)
	})
}

// UpdateToolCallsPresent sets the "tool_calls_present" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateToolCallsPresent() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateToolCallsPresent()
	})
}

// SetMultimodalPresent sets the "multimodal_present" field.
func (u *QARecordUpsertBulk) SetMultimodalPresent(v bool) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetMultimodalPresent(v)
	})
}

// UpdateMultimodalPresent sets the "multimodal_present" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateMultimodalPresent() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateMultimodalPresent()
	})
}

// SetInputTokens sets the "input_tokens" field.
func (u *QARecordUpsertBulk) SetInputTokens(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetInputTokens(v)
	})
}

// AddInputTokens adds v to the "input_tokens" field.
func (u *QARecordUpsertBulk) AddInputTokens(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddInputTokens(v)
	})
}

// UpdateInputTokens sets the "input_tokens" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateInputTokens() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateInputTokens()
	})
}

// SetOutputTokens sets the "output_tokens" field.
func (u *QARecordUpsertBulk) SetOutputTokens(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetOutputTokens(v)
	})
}

// AddOutputTokens adds v to the "output_tokens" field.
func (u *QARecordUpsertBulk) AddOutputTokens(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddOutputTokens(v)
	})
}

// UpdateOutputTokens sets the "output_tokens" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateOutputTokens() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateOutputTokens()
	})
}

// SetCachedTokens sets the "cached_tokens" field.
func (u *QARecordUpsertBulk) SetCachedTokens(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetCachedTokens(v)
	})
}

// AddCachedTokens adds v to the "cached_tokens" field.
func (u *QARecordUpsertBulk) AddCachedTokens(v int) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.AddCachedTokens(v)
	})
}

// UpdateCachedTokens sets the "cached_tokens" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateCachedTokens() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateCachedTokens()
	})
}

// SetRequestSha256 sets the "request_sha256" field.
func (u *QARecordUpsertBulk) SetRequestSha256(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRequestSha256(v)
	})
}

// UpdateRequestSha256 sets the "request_sha256" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateRequestSha256() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRequestSha256()
	})
}

// SetResponseSha256 sets the "response_sha256" field.
func (u *QARecordUpsertBulk) SetResponseSha256(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetResponseSha256(v)
	})
}

// UpdateResponseSha256 sets the "response_sha256" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateResponseSha256() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateResponseSha256()
	})
}

// SetBlobURI sets the "blob_uri" field.
func (u *QARecordUpsertBulk) SetBlobURI(v string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetBlobURI(v)
	})
}

// UpdateBlobURI sets the "blob_uri" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateBlobURI() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateBlobURI()
	})
}

// ClearBlobURI clears the value of the "blob_uri" field.
func (u *QARecordUpsertBulk) ClearBlobURI() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.ClearBlobURI()
	})
}

// SetTags sets the "tags" field.
func (u *QARecordUpsertBulk) SetTags(v []string) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateTags() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateTags()
	})
}

// SetRetentionUntil sets the "retention_until" field.
func (u *QARecordUpsertBulk) SetRetentionUntil(v time.Time) *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.SetRetentionUntil(v)
	})
}

// UpdateRetentionUntil sets the "retention_until" field to the value that was provided on create.
func (u *QARecordUpsertBulk) UpdateRetentionUntil() *QARecordUpsertBulk {
	return u.Update(func(s *QARecordUpsert) {
		s.UpdateRetentionUntil()
	})
}

// Exec executes the query.
func (u *QARecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QARecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QARecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QARecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
