// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/tier"
)

// TierUpdate is the builder for updating Tier entities.
type TierUpdate struct {
	config
	hooks    []Hook
	mutation *TierMutation
}

// Where appends a list predicates to the TierUpdate builder.
func (_u *TierUpdate) Where(ps ...predicate.Tier) *TierUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TierUpdate) SetUpdatedAt(v time.Time) *TierUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TierUpdate) SetName(v string) *TierUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TierUpdate) SetNillableName(v *string) *TierUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TierUpdate) SetDescription(v string) *TierUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TierUpdate) SetNillableDescription(v *string) *TierUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TierUpdate) ClearDescription() *TierUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *TierUpdate) SetConcurrency(v int) *TierUpdate {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *TierUpdate) SetNillableConcurrency(v *int) *TierUpdate {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *TierUpdate) AddConcurrency(v int) *TierUpdate {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TierUpdate) SetPriority(v int) *TierUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TierUpdate) SetNillablePriority(v *int) *TierUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TierUpdate) AddPriority(v int) *TierUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *TierUpdate) SetRateMultiplier(v float64) *TierUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *TierUpdate) SetNillableRateMultiplier(v *float64) *TierUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *TierUpdate) AddRateMultiplier(v float64) *TierUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetBaseRpm sets the "base_rpm" field.
func (_u *TierUpdate) SetBaseRpm(v int) *TierUpdate {
	_u.mutation.ResetBaseRpm()
	_u.mutation.SetBaseRpm(v)
	return _u
}

// SetNillableBaseRpm sets the "base_rpm" field if the given value is not nil.
func (_u *TierUpdate) SetNillableBaseRpm(v *int) *TierUpdate {
	if v != nil {
		_u.SetBaseRpm(*v)
	}
	return _u
}

// AddBaseRpm adds value to the "base_rpm" field.
func (_u *TierUpdate) AddBaseRpm(v int) *TierUpdate {
	_u.mutation.AddBaseRpm(v)
	return _u
}

// SetMaxSessions sets the "max_sessions" field.
func (_u *TierUpdate) SetMaxSessions(v int) *TierUpdate {
	_u.mutation.ResetMaxSessions()
	_u.mutation.SetMaxSessions(v)
	return _u
}

// SetNillableMaxSessions sets the "max_sessions" field if the given value is not nil.
func (_u *TierUpdate) SetNillableMaxSessions(v *int) *TierUpdate {
	if v != nil {
		_u.SetMaxSessions(*v)
	}
	return _u
}

// AddMaxSessions adds value to the "max_sessions" field.
func (_u *TierUpdate) AddMaxSessions(v int) *TierUpdate {
	_u.mutation.AddMaxSessions(v)
	return _u
}

// SetRpmStickyBuffer sets the "rpm_sticky_buffer" field.
func (_u *TierUpdate) SetRpmStickyBuffer(v int) *TierUpdate {
	_u.mutation.ResetRpmStickyBuffer()
	_u.mutation.SetRpmStickyBuffer(v)
	return _u
}

// SetNillableRpmStickyBuffer sets the "rpm_sticky_buffer" field if the given value is not nil.
func (_u *TierUpdate) SetNillableRpmStickyBuffer(v *int) *TierUpdate {
	if v != nil {
		_u.SetRpmStickyBuffer(*v)
	}
	return _u
}

// AddRpmStickyBuffer adds value to the "rpm_sticky_buffer" field.
func (_u *TierUpdate) AddRpmStickyBuffer(v int) *TierUpdate {
	_u.mutation.AddRpmStickyBuffer(v)
	return _u
}

// SetSessionIdleTimeoutMinutes sets the "session_idle_timeout_minutes" field.
func (_u *TierUpdate) SetSessionIdleTimeoutMinutes(v int) *TierUpdate {
	_u.mutation.ResetSessionIdleTimeoutMinutes()
	_u.mutation.SetSessionIdleTimeoutMinutes(v)
	return _u
}

// SetNillableSessionIdleTimeoutMinutes sets the "session_idle_timeout_minutes" field if the given value is not nil.
func (_u *TierUpdate) SetNillableSessionIdleTimeoutMinutes(v *int) *TierUpdate {
	if v != nil {
		_u.SetSessionIdleTimeoutMinutes(*v)
	}
	return _u
}

// AddSessionIdleTimeoutMinutes adds value to the "session_idle_timeout_minutes" field.
func (_u *TierUpdate) AddSessionIdleTimeoutMinutes(v int) *TierUpdate {
	_u.mutation.AddSessionIdleTimeoutMinutes(v)
	return _u
}

// SetWindowCostLimit sets the "window_cost_limit" field.
func (_u *TierUpdate) SetWindowCostLimit(v float64) *TierUpdate {
	_u.mutation.ResetWindowCostLimit()
	_u.mutation.SetWindowCostLimit(v)
	return _u
}

// SetNillableWindowCostLimit sets the "window_cost_limit" field if the given value is not nil.
func (_u *TierUpdate) SetNillableWindowCostLimit(v *float64) *TierUpdate {
	if v != nil {
		_u.SetWindowCostLimit(*v)
	}
	return _u
}

// AddWindowCostLimit adds value to the "window_cost_limit" field.
func (_u *TierUpdate) AddWindowCostLimit(v float64) *TierUpdate {
	_u.mutation.AddWindowCostLimit(v)
	return _u
}

// SetWindowCostStickyReserve sets the "window_cost_sticky_reserve" field.
func (_u *TierUpdate) SetWindowCostStickyReserve(v float64) *TierUpdate {
	_u.mutation.ResetWindowCostStickyReserve()
	_u.mutation.SetWindowCostStickyReserve(v)
	return _u
}

// SetNillableWindowCostStickyReserve sets the "window_cost_sticky_reserve" field if the given value is not nil.
func (_u *TierUpdate) SetNillableWindowCostStickyReserve(v *float64) *TierUpdate {
	if v != nil {
		_u.SetWindowCostStickyReserve(*v)
	}
	return _u
}

// AddWindowCostStickyReserve adds value to the "window_cost_sticky_reserve" field.
func (_u *TierUpdate) AddWindowCostStickyReserve(v float64) *TierUpdate {
	_u.mutation.AddWindowCostStickyReserve(v)
	return _u
}

// SetCacheTTLOverrideEnabled sets the "cache_ttl_override_enabled" field.
func (_u *TierUpdate) SetCacheTTLOverrideEnabled(v bool) *TierUpdate {
	_u.mutation.SetCacheTTLOverrideEnabled(v)
	return _u
}

// SetNillableCacheTTLOverrideEnabled sets the "cache_ttl_override_enabled" field if the given value is not nil.
func (_u *TierUpdate) SetNillableCacheTTLOverrideEnabled(v *bool) *TierUpdate {
	if v != nil {
		_u.SetCacheTTLOverrideEnabled(*v)
	}
	return _u
}

// SetCacheTTLOverrideTarget sets the "cache_ttl_override_target" field.
func (_u *TierUpdate) SetCacheTTLOverrideTarget(v string) *TierUpdate {
	_u.mutation.SetCacheTTLOverrideTarget(v)
	return _u
}

// SetNillableCacheTTLOverrideTarget sets the "cache_ttl_override_target" field if the given value is not nil.
func (_u *TierUpdate) SetNillableCacheTTLOverrideTarget(v *string) *TierUpdate {
	if v != nil {
		_u.SetCacheTTLOverrideTarget(*v)
	}
	return _u
}

// ClearCacheTTLOverrideTarget clears the value of the "cache_ttl_override_target" field.
func (_u *TierUpdate) ClearCacheTTLOverrideTarget() *TierUpdate {
	_u.mutation.ClearCacheTTLOverrideTarget()
	return _u
}

// SetTLSProfileName sets the "tls_profile_name" field.
func (_u *TierUpdate) SetTLSProfileName(v string) *TierUpdate {
	_u.mutation.SetTLSProfileName(v)
	return _u
}

// SetNillableTLSProfileName sets the "tls_profile_name" field if the given value is not nil.
func (_u *TierUpdate) SetNillableTLSProfileName(v *string) *TierUpdate {
	if v != nil {
		_u.SetTLSProfileName(*v)
	}
	return _u
}

// ClearTLSProfileName clears the value of the "tls_profile_name" field.
func (_u *TierUpdate) ClearTLSProfileName() *TierUpdate {
	_u.mutation.ClearTLSProfileName()
	return _u
}

// SetTLSProfileID sets the "tls_profile_id" field.
func (_u *TierUpdate) SetTLSProfileID(v int64) *TierUpdate {
	_u.mutation.ResetTLSProfileID()
	_u.mutation.SetTLSProfileID(v)
	return _u
}

// SetNillableTLSProfileID sets the "tls_profile_id" field if the given value is not nil.
func (_u *TierUpdate) SetNillableTLSProfileID(v *int64) *TierUpdate {
	if v != nil {
		_u.SetTLSProfileID(*v)
	}
	return _u
}

// AddTLSProfileID adds value to the "tls_profile_id" field.
func (_u *TierUpdate) AddTLSProfileID(v int64) *TierUpdate {
	_u.mutation.AddTLSProfileID(v)
	return _u
}

// ClearTLSProfileID clears the value of the "tls_profile_id" field.
func (_u *TierUpdate) ClearTLSProfileID() *TierUpdate {
	_u.mutation.ClearTLSProfileID()
	return _u
}

// Mutation returns the TierMutation object of the builder.
func (_u *TierUpdate) Mutation() *TierMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TierUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TierUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TierUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TierUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TierUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TierUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheTTLOverrideTarget(); ok {
		if err := tier.CacheTTLOverrideTargetValidator(v); err != nil {
			return &ValidationError{Name: "cache_ttl_override_target", err: fmt.Errorf(`ent: validator failed for field "Tier.cache_ttl_override_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TLSProfileName(); ok {
		if err := tier.TLSProfileNameValidator(v); err != nil {
			return &ValidationError{Name: "tls_profile_name", err: fmt.Errorf(`ent: validator failed for field "Tier.tls_profile_name": %w`, err)}
		}
	}
	return nil
}

func (_u *TierUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tier.Table, tier.Columns, sqlgraph.NewFieldSpec(tier.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tier.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tier.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tier.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(tier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(tier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(tier.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(tier.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(tier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(tier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BaseRpm(); ok {
		_spec.SetField(tier.FieldBaseRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBaseRpm(); ok {
		_spec.AddField(tier.FieldBaseRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxSessions(); ok {
		_spec.SetField(tier.FieldMaxSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxSessions(); ok {
		_spec.AddField(tier.FieldMaxSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmStickyBuffer(); ok {
		_spec.SetField(tier.FieldRpmStickyBuffer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmStickyBuffer(); ok {
		_spec.AddField(tier.FieldRpmStickyBuffer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionIdleTimeoutMinutes(); ok {
		_spec.SetField(tier.FieldSessionIdleTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionIdleTimeoutMinutes(); ok {
		_spec.AddField(tier.FieldSessionIdleTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WindowCostLimit(); ok {
		_spec.SetField(tier.FieldWindowCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWindowCostLimit(); ok {
		_spec.AddField(tier.FieldWindowCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WindowCostStickyReserve(); ok {
		_spec.SetField(tier.FieldWindowCostStickyReserve, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWindowCostStickyReserve(); ok {
		_spec.AddField(tier.FieldWindowCostStickyReserve, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheTTLOverrideEnabled(); ok {
		_spec.SetField(tier.FieldCacheTTLOverrideEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CacheTTLOverrideTarget(); ok {
		_spec.SetField(tier.FieldCacheTTLOverrideTarget, field.TypeString, value)
	}
	if _u.mutation.CacheTTLOverrideTargetCleared() {
		_spec.ClearField(tier.FieldCacheTTLOverrideTarget, field.TypeString)
	}
	if value, ok := _u.mutation.TLSProfileName(); ok {
		_spec.SetField(tier.FieldTLSProfileName, field.TypeString, value)
	}
	if _u.mutation.TLSProfileNameCleared() {
		_spec.ClearField(tier.FieldTLSProfileName, field.TypeString)
	}
	if value, ok := _u.mutation.TLSProfileID(); ok {
		_spec.SetField(tier.FieldTLSProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTLSProfileID(); ok {
		_spec.AddField(tier.FieldTLSProfileID, field.TypeInt64, value)
	}
	if _u.mutation.TLSProfileIDCleared() {
		_spec.ClearField(tier.FieldTLSProfileID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TierUpdateOne is the builder for updating a single Tier entity.
type TierUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TierMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TierUpdateOne) SetUpdatedAt(v time.Time) *TierUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *TierUpdateOne) SetName(v string) *TierUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableName(v *string) *TierUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TierUpdateOne) SetDescription(v string) *TierUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableDescription(v *string) *TierUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TierUpdateOne) ClearDescription() *TierUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetConcurrency sets the "concurrency" field.
func (_u *TierUpdateOne) SetConcurrency(v int) *TierUpdateOne {
	_u.mutation.ResetConcurrency()
	_u.mutation.SetConcurrency(v)
	return _u
}

// SetNillableConcurrency sets the "concurrency" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableConcurrency(v *int) *TierUpdateOne {
	if v != nil {
		_u.SetConcurrency(*v)
	}
	return _u
}

// AddConcurrency adds value to the "concurrency" field.
func (_u *TierUpdateOne) AddConcurrency(v int) *TierUpdateOne {
	_u.mutation.AddConcurrency(v)
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TierUpdateOne) SetPriority(v int) *TierUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillablePriority(v *int) *TierUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *TierUpdateOne) AddPriority(v int) *TierUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *TierUpdateOne) SetRateMultiplier(v float64) *TierUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableRateMultiplier(v *float64) *TierUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *TierUpdateOne) AddRateMultiplier(v float64) *TierUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetBaseRpm sets the "base_rpm" field.
func (_u *TierUpdateOne) SetBaseRpm(v int) *TierUpdateOne {
	_u.mutation.ResetBaseRpm()
	_u.mutation.SetBaseRpm(v)
	return _u
}

// SetNillableBaseRpm sets the "base_rpm" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableBaseRpm(v *int) *TierUpdateOne {
	if v != nil {
		_u.SetBaseRpm(*v)
	}
	return _u
}

// AddBaseRpm adds value to the "base_rpm" field.
func (_u *TierUpdateOne) AddBaseRpm(v int) *TierUpdateOne {
	_u.mutation.AddBaseRpm(v)
	return _u
}

// SetMaxSessions sets the "max_sessions" field.
func (_u *TierUpdateOne) SetMaxSessions(v int) *TierUpdateOne {
	_u.mutation.ResetMaxSessions()
	_u.mutation.SetMaxSessions(v)
	return _u
}

// SetNillableMaxSessions sets the "max_sessions" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableMaxSessions(v *int) *TierUpdateOne {
	if v != nil {
		_u.SetMaxSessions(*v)
	}
	return _u
}

// AddMaxSessions adds value to the "max_sessions" field.
func (_u *TierUpdateOne) AddMaxSessions(v int) *TierUpdateOne {
	_u.mutation.AddMaxSessions(v)
	return _u
}

// SetRpmStickyBuffer sets the "rpm_sticky_buffer" field.
func (_u *TierUpdateOne) SetRpmStickyBuffer(v int) *TierUpdateOne {
	_u.mutation.ResetRpmStickyBuffer()
	_u.mutation.SetRpmStickyBuffer(v)
	return _u
}

// SetNillableRpmStickyBuffer sets the "rpm_sticky_buffer" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableRpmStickyBuffer(v *int) *TierUpdateOne {
	if v != nil {
		_u.SetRpmStickyBuffer(*v)
	}
	return _u
}

// AddRpmStickyBuffer adds value to the "rpm_sticky_buffer" field.
func (_u *TierUpdateOne) AddRpmStickyBuffer(v int) *TierUpdateOne {
	_u.mutation.AddRpmStickyBuffer(v)
	return _u
}

// SetSessionIdleTimeoutMinutes sets the "session_idle_timeout_minutes" field.
func (_u *TierUpdateOne) SetSessionIdleTimeoutMinutes(v int) *TierUpdateOne {
	_u.mutation.ResetSessionIdleTimeoutMinutes()
	_u.mutation.SetSessionIdleTimeoutMinutes(v)
	return _u
}

// SetNillableSessionIdleTimeoutMinutes sets the "session_idle_timeout_minutes" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableSessionIdleTimeoutMinutes(v *int) *TierUpdateOne {
	if v != nil {
		_u.SetSessionIdleTimeoutMinutes(*v)
	}
	return _u
}

// AddSessionIdleTimeoutMinutes adds value to the "session_idle_timeout_minutes" field.
func (_u *TierUpdateOne) AddSessionIdleTimeoutMinutes(v int) *TierUpdateOne {
	_u.mutation.AddSessionIdleTimeoutMinutes(v)
	return _u
}

// SetWindowCostLimit sets the "window_cost_limit" field.
func (_u *TierUpdateOne) SetWindowCostLimit(v float64) *TierUpdateOne {
	_u.mutation.ResetWindowCostLimit()
	_u.mutation.SetWindowCostLimit(v)
	return _u
}

// SetNillableWindowCostLimit sets the "window_cost_limit" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableWindowCostLimit(v *float64) *TierUpdateOne {
	if v != nil {
		_u.SetWindowCostLimit(*v)
	}
	return _u
}

// AddWindowCostLimit adds value to the "window_cost_limit" field.
func (_u *TierUpdateOne) AddWindowCostLimit(v float64) *TierUpdateOne {
	_u.mutation.AddWindowCostLimit(v)
	return _u
}

// SetWindowCostStickyReserve sets the "window_cost_sticky_reserve" field.
func (_u *TierUpdateOne) SetWindowCostStickyReserve(v float64) *TierUpdateOne {
	_u.mutation.ResetWindowCostStickyReserve()
	_u.mutation.SetWindowCostStickyReserve(v)
	return _u
}

// SetNillableWindowCostStickyReserve sets the "window_cost_sticky_reserve" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableWindowCostStickyReserve(v *float64) *TierUpdateOne {
	if v != nil {
		_u.SetWindowCostStickyReserve(*v)
	}
	return _u
}

// AddWindowCostStickyReserve adds value to the "window_cost_sticky_reserve" field.
func (_u *TierUpdateOne) AddWindowCostStickyReserve(v float64) *TierUpdateOne {
	_u.mutation.AddWindowCostStickyReserve(v)
	return _u
}

// SetCacheTTLOverrideEnabled sets the "cache_ttl_override_enabled" field.
func (_u *TierUpdateOne) SetCacheTTLOverrideEnabled(v bool) *TierUpdateOne {
	_u.mutation.SetCacheTTLOverrideEnabled(v)
	return _u
}

// SetNillableCacheTTLOverrideEnabled sets the "cache_ttl_override_enabled" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableCacheTTLOverrideEnabled(v *bool) *TierUpdateOne {
	if v != nil {
		_u.SetCacheTTLOverrideEnabled(*v)
	}
	return _u
}

// SetCacheTTLOverrideTarget sets the "cache_ttl_override_target" field.
func (_u *TierUpdateOne) SetCacheTTLOverrideTarget(v string) *TierUpdateOne {
	_u.mutation.SetCacheTTLOverrideTarget(v)
	return _u
}

// SetNillableCacheTTLOverrideTarget sets the "cache_ttl_override_target" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableCacheTTLOverrideTarget(v *string) *TierUpdateOne {
	if v != nil {
		_u.SetCacheTTLOverrideTarget(*v)
	}
	return _u
}

// ClearCacheTTLOverrideTarget clears the value of the "cache_ttl_override_target" field.
func (_u *TierUpdateOne) ClearCacheTTLOverrideTarget() *TierUpdateOne {
	_u.mutation.ClearCacheTTLOverrideTarget()
	return _u
}

// SetTLSProfileName sets the "tls_profile_name" field.
func (_u *TierUpdateOne) SetTLSProfileName(v string) *TierUpdateOne {
	_u.mutation.SetTLSProfileName(v)
	return _u
}

// SetNillableTLSProfileName sets the "tls_profile_name" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableTLSProfileName(v *string) *TierUpdateOne {
	if v != nil {
		_u.SetTLSProfileName(*v)
	}
	return _u
}

// ClearTLSProfileName clears the value of the "tls_profile_name" field.
func (_u *TierUpdateOne) ClearTLSProfileName() *TierUpdateOne {
	_u.mutation.ClearTLSProfileName()
	return _u
}

// SetTLSProfileID sets the "tls_profile_id" field.
func (_u *TierUpdateOne) SetTLSProfileID(v int64) *TierUpdateOne {
	_u.mutation.ResetTLSProfileID()
	_u.mutation.SetTLSProfileID(v)
	return _u
}

// SetNillableTLSProfileID sets the "tls_profile_id" field if the given value is not nil.
func (_u *TierUpdateOne) SetNillableTLSProfileID(v *int64) *TierUpdateOne {
	if v != nil {
		_u.SetTLSProfileID(*v)
	}
	return _u
}

// AddTLSProfileID adds value to the "tls_profile_id" field.
func (_u *TierUpdateOne) AddTLSProfileID(v int64) *TierUpdateOne {
	_u.mutation.AddTLSProfileID(v)
	return _u
}

// ClearTLSProfileID clears the value of the "tls_profile_id" field.
func (_u *TierUpdateOne) ClearTLSProfileID() *TierUpdateOne {
	_u.mutation.ClearTLSProfileID()
	return _u
}

// Mutation returns the TierMutation object of the builder.
func (_u *TierUpdateOne) Mutation() *TierMutation {
	return _u.mutation
}

// Where appends a list predicates to the TierUpdate builder.
func (_u *TierUpdateOne) Where(ps ...predicate.Tier) *TierUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TierUpdateOne) Select(field string, fields ...string) *TierUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tier entity.
func (_u *TierUpdateOne) Save(ctx context.Context) (*Tier, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TierUpdateOne) SaveX(ctx context.Context) *Tier {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TierUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TierUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TierUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := tier.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TierUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := tier.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tier.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CacheTTLOverrideTarget(); ok {
		if err := tier.CacheTTLOverrideTargetValidator(v); err != nil {
			return &ValidationError{Name: "cache_ttl_override_target", err: fmt.Errorf(`ent: validator failed for field "Tier.cache_ttl_override_target": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TLSProfileName(); ok {
		if err := tier.TLSProfileNameValidator(v); err != nil {
			return &ValidationError{Name: "tls_profile_name", err: fmt.Errorf(`ent: validator failed for field "Tier.tls_profile_name": %w`, err)}
		}
	}
	return nil
}

func (_u *TierUpdateOne) sqlSave(ctx context.Context) (_node *Tier, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tier.Table, tier.Columns, sqlgraph.NewFieldSpec(tier.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tier.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tier.FieldID)
		for _, f := range fields {
			if !tier.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tier.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tier.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tier.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tier.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tier.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Concurrency(); ok {
		_spec.SetField(tier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConcurrency(); ok {
		_spec.AddField(tier.FieldConcurrency, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(tier.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(tier.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(tier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(tier.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BaseRpm(); ok {
		_spec.SetField(tier.FieldBaseRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBaseRpm(); ok {
		_spec.AddField(tier.FieldBaseRpm, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxSessions(); ok {
		_spec.SetField(tier.FieldMaxSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxSessions(); ok {
		_spec.AddField(tier.FieldMaxSessions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RpmStickyBuffer(); ok {
		_spec.SetField(tier.FieldRpmStickyBuffer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRpmStickyBuffer(); ok {
		_spec.AddField(tier.FieldRpmStickyBuffer, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionIdleTimeoutMinutes(); ok {
		_spec.SetField(tier.FieldSessionIdleTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionIdleTimeoutMinutes(); ok {
		_spec.AddField(tier.FieldSessionIdleTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WindowCostLimit(); ok {
		_spec.SetField(tier.FieldWindowCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWindowCostLimit(); ok {
		_spec.AddField(tier.FieldWindowCostLimit, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.WindowCostStickyReserve(); ok {
		_spec.SetField(tier.FieldWindowCostStickyReserve, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWindowCostStickyReserve(); ok {
		_spec.AddField(tier.FieldWindowCostStickyReserve, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CacheTTLOverrideEnabled(); ok {
		_spec.SetField(tier.FieldCacheTTLOverrideEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CacheTTLOverrideTarget(); ok {
		_spec.SetField(tier.FieldCacheTTLOverrideTarget, field.TypeString, value)
	}
	if _u.mutation.CacheTTLOverrideTargetCleared() {
		_spec.ClearField(tier.FieldCacheTTLOverrideTarget, field.TypeString)
	}
	if value, ok := _u.mutation.TLSProfileName(); ok {
		_spec.SetField(tier.FieldTLSProfileName, field.TypeString, value)
	}
	if _u.mutation.TLSProfileNameCleared() {
		_spec.ClearField(tier.FieldTLSProfileName, field.TypeString)
	}
	if value, ok := _u.mutation.TLSProfileID(); ok {
		_spec.SetField(tier.FieldTLSProfileID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTLSProfileID(); ok {
		_spec.AddField(tier.FieldTLSProfileID, field.TypeInt64, value)
	}
	if _u.mutation.TLSProfileIDCleared() {
		_spec.ClearField(tier.FieldTLSProfileID, field.TypeInt64)
	}
	_node = &Tier{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tier.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
