// Code generated by ent, DO NOT EDIT.

package qaarchiveshard

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the qaarchiveshard type in the database.
	Label = "qa_archive_shard"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldWindowStart holds the string denoting the window_start field in the database.
	FieldWindowStart = "window_start"
	// FieldWindowEnd holds the string denoting the window_end field in the database.
	FieldWindowEnd = "window_end"
	// FieldGeneration holds the string denoting the generation field in the database.
	FieldGeneration = "generation"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldRecordCount holds the string denoting the record_count field in the database.
	FieldRecordCount = "record_count"
	// FieldBlobRefCount holds the string denoting the blob_ref_count field in the database.
	FieldBlobRefCount = "blob_ref_count"
	// FieldBlobPresentCount holds the string denoting the blob_present_count field in the database.
	FieldBlobPresentCount = "blob_present_count"
	// FieldBlobMissingCount holds the string denoting the blob_missing_count field in the database.
	FieldBlobMissingCount = "blob_missing_count"
	// FieldLogicalBytes holds the string denoting the logical_bytes field in the database.
	FieldLogicalBytes = "logical_bytes"
	// FieldArtifactBytes holds the string denoting the artifact_bytes field in the database.
	FieldArtifactBytes = "artifact_bytes"
	// FieldChecksums holds the string denoting the checksums field in the database.
	FieldChecksums = "checksums"
	// FieldS3Prefix holds the string denoting the s3_prefix field in the database.
	FieldS3Prefix = "s3_prefix"
	// FieldManifestKey holds the string denoting the manifest_key field in the database.
	FieldManifestKey = "manifest_key"
	// FieldCommitKey holds the string denoting the commit_key field in the database.
	FieldCommitKey = "commit_key"
	// FieldFirstAttemptAt holds the string denoting the first_attempt_at field in the database.
	FieldFirstAttemptAt = "first_attempt_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the qaarchiveshard in the database.
	Table = "qa_archive_shards"
)

// Columns holds all SQL columns for qaarchiveshard fields.
var Columns = []string{
	FieldID,
	FieldWindowStart,
	FieldWindowEnd,
	FieldGeneration,
	FieldState,
	FieldRecordCount,
	FieldBlobRefCount,
	FieldBlobPresentCount,
	FieldBlobMissingCount,
	FieldLogicalBytes,
	FieldArtifactBytes,
	FieldChecksums,
	FieldS3Prefix,
	FieldManifestKey,
	FieldCommitKey,
	FieldFirstAttemptAt,
	FieldCompletedAt,
	FieldLastError,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultGeneration holds the default value on creation for the "generation" field.
	DefaultGeneration int
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// DefaultRecordCount holds the default value on creation for the "record_count" field.
	DefaultRecordCount int64
	// DefaultBlobRefCount holds the default value on creation for the "blob_ref_count" field.
	DefaultBlobRefCount int64
	// DefaultBlobPresentCount holds the default value on creation for the "blob_present_count" field.
	DefaultBlobPresentCount int64
	// DefaultBlobMissingCount holds the default value on creation for the "blob_missing_count" field.
	DefaultBlobMissingCount int64
	// DefaultLogicalBytes holds the default value on creation for the "logical_bytes" field.
	DefaultLogicalBytes int64
	// DefaultArtifactBytes holds the default value on creation for the "artifact_bytes" field.
	DefaultArtifactBytes int64
	// DefaultChecksums holds the default value on creation for the "checksums" field.
	DefaultChecksums map[string]string
	// DefaultS3Prefix holds the default value on creation for the "s3_prefix" field.
	DefaultS3Prefix string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the QAArchiveShard queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByWindowStart orders the results by the window_start field.
func ByWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowStart, opts...).ToFunc()
}

// ByWindowEnd orders the results by the window_end field.
func ByWindowEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindowEnd, opts...).ToFunc()
}

// ByGeneration orders the results by the generation field.
func ByGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGeneration, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByRecordCount orders the results by the record_count field.
func ByRecordCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecordCount, opts...).ToFunc()
}

// ByBlobRefCount orders the results by the blob_ref_count field.
func ByBlobRefCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobRefCount, opts...).ToFunc()
}

// ByBlobPresentCount orders the results by the blob_present_count field.
func ByBlobPresentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobPresentCount, opts...).ToFunc()
}

// ByBlobMissingCount orders the results by the blob_missing_count field.
func ByBlobMissingCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobMissingCount, opts...).ToFunc()
}

// ByLogicalBytes orders the results by the logical_bytes field.
func ByLogicalBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogicalBytes, opts...).ToFunc()
}

// ByArtifactBytes orders the results by the artifact_bytes field.
func ByArtifactBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtifactBytes, opts...).ToFunc()
}

// ByS3Prefix orders the results by the s3_prefix field.
func ByS3Prefix(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldS3Prefix, opts...).ToFunc()
}

// ByManifestKey orders the results by the manifest_key field.
func ByManifestKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestKey, opts...).ToFunc()
}

// ByCommitKey orders the results by the commit_key field.
func ByCommitKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitKey, opts...).ToFunc()
}

// ByFirstAttemptAt orders the results by the first_attempt_at field.
func ByFirstAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstAttemptAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
