//go:build unit

package service

import (
	"context"
	"errors"
	"sync"
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/stretchr/testify/require"
)

// US-030 unit coverage: auto-issued "trial" API key after registration.
//
// We use a recording fake TrialKeyIssuer (not the real APIKeyService) so the
// test asserts on the AuthService → issuer call contract instead of pulling in
// the entire APIKeyService dependency graph (groups / cache / cfg).
//
// The full apiKeyTrialIssuer.IssueTrialKeyIfEnabled implementation is also
// exercised below against in-memory stubs to verify the toggle + name-fallback
// semantics and that errors are swallowed (best-effort contract).

type recordingTrialKeyIssuer struct {
	mu    sync.Mutex
	calls []int64
}

func (r *recordingTrialKeyIssuer) IssueTrialKeyIfEnabled(_ context.Context, userID int64) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.calls = append(r.calls, userID)
}

func (r *recordingTrialKeyIssuer) callCount() int {
	r.mu.Lock()
	defer r.mu.Unlock()
	return len(r.calls)
}

func TestUS030_RegisterEmailPath_InvokesTrialKeyIssuer(t *testing.T) {
	// AC-001 / AC-002: a successful email registration must trigger exactly
	// one IssueTrialKeyIfEnabled call with the new user's ID.
	repo := &userRepoStub{nextID: 11}
	svc := newAuthService(repo, map[string]string{
		SettingKeyRegistrationEnabled: "true",
	}, nil)

	issuer := &recordingTrialKeyIssuer{}
	svc.SetTrialKeyIssuer(issuer)

	_, user, err := svc.Register(context.Background(), "u@test.com", "password")
	require.NoError(t, err)
	require.Equal(t, int64(11), user.ID)
	require.Equal(t, 1, issuer.callCount(), "trial-key issuer must be called once per fresh registration")
	require.Equal(t, []int64{11}, issuer.calls)
}

func TestUS030_RegisterEmailPath_NoIssuerWired_NoPanic(t *testing.T) {
	// Defensive: missing issuer in tests / partial init must be a silent no-op,
	// never a panic that breaks registration.
	repo := &userRepoStub{nextID: 12}
	svc := newAuthService(repo, map[string]string{
		SettingKeyRegistrationEnabled: "true",
	}, nil)
	// Intentionally NOT calling SetTrialKeyIssuer.

	_, user, err := svc.Register(context.Background(), "u@test.com", "password")
	require.NoError(t, err)
	require.NotNil(t, user)
}

func TestUS030_RegisterEmailPath_FailedCreate_SkipsIssuer(t *testing.T) {
	// AC defensive: when user creation fails, the issuer must NOT be called
	// (no orphan trial keys for users that don't exist).
	repo := &userRepoStub{createErr: errors.New("db down")}
	svc := newAuthService(repo, map[string]string{
		SettingKeyRegistrationEnabled: "true",
	}, nil)

	issuer := &recordingTrialKeyIssuer{}
	svc.SetTrialKeyIssuer(issuer)

	_, _, err := svc.Register(context.Background(), "u@test.com", "password")
	require.Error(t, err)
	require.Equal(t, 0, issuer.callCount(),
		"failed registrations must not trigger trial-key issuance")
}

func TestUS030_RegisterEmailPath_RaceEmailExists_SkipsIssuer(t *testing.T) {
	// Defensive: when Create races against a parallel registration and returns
	// ErrEmailExists, no trial key should be issued because no NEW user was
	// inserted in this code path.
	repo := &userRepoStub{createErr: ErrEmailExists}
	svc := newAuthService(repo, map[string]string{
		SettingKeyRegistrationEnabled: "true",
	}, nil)

	issuer := &recordingTrialKeyIssuer{}
	svc.SetTrialKeyIssuer(issuer)

	_, _, err := svc.Register(context.Background(), "u@test.com", "password")
	require.ErrorIs(t, err, ErrEmailExists)
	require.Equal(t, 0, issuer.callCount(),
		"email-exists race must not issue a trial key for an existing account")
}

// ---------------------------------------------------------------------------
// apiKeyTrialIssuer (production impl) coverage
// ---------------------------------------------------------------------------

func TestUS030_NewTrialKeyIssuer_NilDeps_ReturnsNil(t *testing.T) {
	require.Nil(t, NewTrialKeyIssuer(nil, nil))
	require.Nil(t, NewTrialKeyIssuer(nil, &SettingService{}))
	require.Nil(t, NewTrialKeyIssuer(&APIKeyService{}, nil))
}

func TestUS030_ApiKeyTrialIssuer_DisabledSetting_NoCall(t *testing.T) {
	// AC: when auto_generate_default_token=false, the issuer must short-circuit
	// before reaching APIKeyService.Create. We pass an APIKeyService with a nil
	// userRepo; if the issuer ever reached Create, the test would panic at
	// the first userRepo.GetByID call, so the absence of a panic is the
	// behavior assertion.
	settings := NewSettingService(&settingRepoStub{values: map[string]string{
		SettingKeyAutoGenerateDefaultToken: "false",
	}}, &config.Config{})

	issuer := &apiKeyTrialIssuer{
		apiKeyService:  &APIKeyService{}, // would panic on Create — must NOT be reached
		settingService: settings,
	}
	require.NotPanics(t, func() {
		issuer.IssueTrialKeyIfEnabled(context.Background(), 1)
	})
}

func TestUS030_ApiKeyTrialIssuer_NilSelf_NoPanic(t *testing.T) {
	var issuer *apiKeyTrialIssuer
	require.NotPanics(t, func() {
		issuer.IssueTrialKeyIfEnabled(context.Background(), 1)
	})
}

func TestUS030_ApiKeyTrialIssuer_DefaultName_Trial(t *testing.T) {
	// US-030 explicit naming requirement: when no admin override is set, the
	// configured key name MUST be "trial" (not "default", not empty). We
	// verify GetAutoGenerateDefaultTokenName fallback through the issuer's
	// path by checking it directly on SettingService.
	settings := NewSettingService(&settingRepoStub{values: map[string]string{}}, &config.Config{})
	require.Equal(t, "trial", settings.GetAutoGenerateDefaultTokenName(context.Background()),
		"missing setting row must default to 'trial', NOT 'default' or empty")
}
