//go:build unit

package service

import (
	"context"
	"errors"
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/stretchr/testify/require"
)

// csRepoStub is a minimal Setting repository stub used only by the cold-start
// unit tests. It mirrors the bmRepoStub pattern in setting_service_backend_mode_test.go
// but stays in this file so the cold-start spec is self-contained.
type csRepoStub struct {
	values    map[string]string
	getErrFor map[string]error
	getCalls  map[string]int
	updates   map[string]string
}

func newCSRepoStub() *csRepoStub {
	return &csRepoStub{
		values:    map[string]string{},
		getErrFor: map[string]error{},
		getCalls:  map[string]int{},
	}
}

func (s *csRepoStub) Get(ctx context.Context, key string) (*Setting, error) {
	panic("unexpected Get call")
}

func (s *csRepoStub) GetValue(ctx context.Context, key string) (string, error) {
	s.getCalls[key]++
	if err := s.getErrFor[key]; err != nil {
		return "", err
	}
	v, ok := s.values[key]
	if !ok {
		return "", ErrSettingNotFound
	}
	return v, nil
}

func (s *csRepoStub) Set(ctx context.Context, key, value string) error {
	panic("unexpected Set call")
}

func (s *csRepoStub) GetMultiple(ctx context.Context, keys []string) (map[string]string, error) {
	panic("unexpected GetMultiple call")
}

func (s *csRepoStub) SetMultiple(ctx context.Context, settings map[string]string) error {
	if s.updates == nil {
		s.updates = make(map[string]string, len(settings))
	}
	for k, v := range settings {
		s.updates[k] = v
	}
	return nil
}

func (s *csRepoStub) GetAll(ctx context.Context) (map[string]string, error) {
	panic("unexpected GetAll call")
}

func (s *csRepoStub) Delete(ctx context.Context, key string) error {
	panic("unexpected Delete call")
}

// ---------------------------------------------------------------------------
// Pure helpers (no DB stub needed) — tkMergeDefault / tkApplyParsed / tkAppend
// ---------------------------------------------------------------------------

// TestColdStart_Defaults_LockUSDAndTrialKeyName proves the design v3 contract:
//   - bonus = $1.00 USD
//   - auto-key name = "trial" (NOT "default")
//   - all 5 toggles default to ON
func TestColdStart_Defaults_LockUSDAndTrialKeyName(t *testing.T) {
	defaults := map[string]string{}
	tkMergeDefaultColdStartSettings(defaults)

	require.Equal(t, "true", defaults[SettingKeySignupBonusEnabled],
		"signup bonus default must be ON; design v3 §2 P0-B")
	require.Equal(t, "1.00000000", defaults[SettingKeySignupBonusBalance],
		"signup bonus default must be $1.00 USD; design v3 §0 + §6")
	require.Equal(t, "true", defaults[SettingKeyAutoGenerateDefaultToken],
		"auto-issue trial key default must be ON; design v3 §2 P0-C")
	require.Equal(t, "trial", defaults[SettingKeyAutoGenerateDefaultTokenName],
		"auto-key default name must be 'trial', NOT 'default'; design v3 §0 revision")
	require.Equal(t, "true", defaults[SettingKeyPricingCatalogPublic],
		"public pricing catalog default must be ON; design v3 §2 P0-A")
}

// TestColdStart_ParseSettings_FallbackOnMissingRows proves the read path
// fails-closed-toward-on so a fresh DB still issues bonus + trial key.
func TestColdStart_ParseSettings_FallbackOnMissingRows(t *testing.T) {
	result := &SystemSettings{}
	tkApplyColdStartParsed(map[string]string{}, result)

	require.True(t, result.SignupBonusEnabled, "missing row -> default ON")
	require.InDelta(t, 1.00, result.SignupBonusBalance, 1e-9, "missing row -> $1.00")
	require.True(t, result.AutoGenerateDefaultToken, "missing row -> default ON")
	require.Equal(t, "trial", result.AutoGenerateDefaultTokenName, "missing row -> 'trial'")
	require.True(t, result.PricingCatalogPublic, "missing row -> default ON")
}

// TestColdStart_ParseSettings_ExplicitFalseTurnsOff proves admin can disable.
func TestColdStart_ParseSettings_ExplicitFalseTurnsOff(t *testing.T) {
	result := &SystemSettings{}
	tkApplyColdStartParsed(map[string]string{
		SettingKeySignupBonusEnabled:           "false",
		SettingKeySignupBonusBalance:           "5.50",
		SettingKeyAutoGenerateDefaultToken:     "false",
		SettingKeyAutoGenerateDefaultTokenName: "free-tier",
		SettingKeyPricingCatalogPublic:         "false",
	}, result)

	require.False(t, result.SignupBonusEnabled)
	require.InDelta(t, 5.50, result.SignupBonusBalance, 1e-9,
		"admin-configured balance must be honored")
	require.False(t, result.AutoGenerateDefaultToken)
	require.Equal(t, "free-tier", result.AutoGenerateDefaultTokenName,
		"admin-configured key name must be honored (US-029 AC-008)")
	require.False(t, result.PricingCatalogPublic)
}

// TestColdStart_ParseSettings_NegativeBalanceFallsBackToDefault prevents
// admin typo from creating negative-balance accounts.
func TestColdStart_ParseSettings_NegativeBalanceFallsBackToDefault(t *testing.T) {
	result := &SystemSettings{}
	tkApplyColdStartParsed(map[string]string{
		SettingKeySignupBonusBalance: "-3.14",
	}, result)
	require.InDelta(t, 1.00, result.SignupBonusBalance, 1e-9,
		"negative balance must fall back to safe default, not poison new users")
}

// TestColdStart_AppendUpdates_ClampsNegativeBalance ensures the write path
// also defends against negative input from a misbehaving admin frontend.
func TestColdStart_AppendUpdates_ClampsNegativeBalance(t *testing.T) {
	updates := map[string]string{}
	settings := &SystemSettings{
		SignupBonusEnabled:           true,
		SignupBonusBalance:           -5.0,
		AutoGenerateDefaultToken:     true,
		AutoGenerateDefaultTokenName: "",
		PricingCatalogPublic:         true,
	}
	(&SettingService{}).tkAppendColdStartSettingUpdates(updates, settings)

	require.Equal(t, "0.00000000", updates[SettingKeySignupBonusBalance],
		"negative balance must be clamped to 0 before persisting")
	require.Equal(t, "trial", updates[SettingKeyAutoGenerateDefaultTokenName],
		"empty key name must fall back to 'trial' before persisting")
}

// ---------------------------------------------------------------------------
// Getter tests (with DB stub)
// ---------------------------------------------------------------------------

func TestComputeSignupBonus_HonorsEnabledFlag(t *testing.T) {
	repo := newCSRepoStub()
	repo.values[SettingKeySignupBonusEnabled] = "false"
	repo.values[SettingKeySignupBonusBalance] = "10.00"
	svc := NewSettingService(repo, &config.Config{})

	got := svc.ComputeSignupBonus(context.Background())
	require.InDelta(t, 0.0, got, 1e-9,
		"disabled flag must short-circuit even when balance > 0")
}

func TestComputeSignupBonus_ReturnsConfiguredValue(t *testing.T) {
	repo := newCSRepoStub()
	repo.values[SettingKeySignupBonusEnabled] = "true"
	repo.values[SettingKeySignupBonusBalance] = "2.50"
	svc := NewSettingService(repo, &config.Config{})

	got := svc.ComputeSignupBonus(context.Background())
	require.InDelta(t, 2.50, got, 1e-9)
}

func TestComputeSignupBonus_DefaultOneDollarOnFreshDB(t *testing.T) {
	repo := newCSRepoStub()
	svc := NewSettingService(repo, &config.Config{})

	got := svc.ComputeSignupBonus(context.Background())
	require.InDelta(t, 1.00, got, 1e-9,
		"fresh DB (no rows) must still issue $1.00 USD per design v3 §0")
}

func TestComputeSignupBonus_FallsBackOnDBError(t *testing.T) {
	repo := newCSRepoStub()
	repo.getErrFor[SettingKeySignupBonusEnabled] = errors.New("db down")
	repo.getErrFor[SettingKeySignupBonusBalance] = errors.New("db down")
	svc := NewSettingService(repo, &config.Config{})

	got := svc.ComputeSignupBonus(context.Background())
	require.InDelta(t, 1.00, got, 1e-9,
		"transient DB error must not leave new users at $0")
}

func TestGetAutoGenerateDefaultTokenName_FallsBackToTrial(t *testing.T) {
	repo := newCSRepoStub()
	svc := NewSettingService(repo, &config.Config{})

	require.Equal(t, "trial", svc.GetAutoGenerateDefaultTokenName(context.Background()),
		"missing row must fall back to 'trial', not empty string")
}

func TestGetAutoGenerateDefaultTokenName_HonorsAdminOverride(t *testing.T) {
	repo := newCSRepoStub()
	repo.values[SettingKeyAutoGenerateDefaultTokenName] = "starter-pack"
	svc := NewSettingService(repo, &config.Config{})

	require.Equal(t, "starter-pack", svc.GetAutoGenerateDefaultTokenName(context.Background()),
		"admin-configured name must be returned verbatim (US-029 AC-008)")
}

func TestIsAutoGenerateDefaultTokenEnabled_DefaultsOn(t *testing.T) {
	repo := newCSRepoStub()
	svc := NewSettingService(repo, &config.Config{})
	require.True(t, svc.IsAutoGenerateDefaultTokenEnabled(context.Background()))
}

func TestIsAutoGenerateDefaultTokenEnabled_ExplicitFalse(t *testing.T) {
	repo := newCSRepoStub()
	repo.values[SettingKeyAutoGenerateDefaultToken] = "false"
	svc := NewSettingService(repo, &config.Config{})
	require.False(t, svc.IsAutoGenerateDefaultTokenEnabled(context.Background()))
}

func TestIsPricingCatalogPublic_DefaultsOn(t *testing.T) {
	repo := newCSRepoStub()
	svc := NewSettingService(repo, &config.Config{})
	require.True(t, svc.IsPricingCatalogPublic(context.Background()))
}

func TestIsPricingCatalogPublic_ExplicitFalseClosesEndpoint(t *testing.T) {
	repo := newCSRepoStub()
	repo.values[SettingKeyPricingCatalogPublic] = "false"
	svc := NewSettingService(repo, &config.Config{})
	require.False(t, svc.IsPricingCatalogPublic(context.Background()),
		"admin must be able to close the public pricing endpoint per design v3 §6")
}
