//go:build unit

package service

import (
	"context"
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/config"
	"github.com/stretchr/testify/require"
)

// Tests for the priced-serving-gate enabled SET (setting_service_tk_cold_start.go):
// IsPricedServingGateEnabled membership semantics + SystemSettings round-trip.

func TestIsPricedServingGateEnabled_SetMembership(t *testing.T) {
	ctx := context.Background()

	cases := []struct {
		name       string
		enabledSet string // "" = row absent
		platform   string
		want       bool
	}{
		{"absent row → off", "", "gemini", false},
		{"empty value → off", "   ", "gemini", false},
		{"gemini in single-member set", "gemini", "gemini", true},
		{"anthropic NOT in gemini-only set", "gemini", "anthropic", false},
		{"openai NOT in gemini-only set", "gemini", "openai", false},
		{"member of multi set (gemini)", "gemini,openai", "gemini", true},
		{"member of multi set (openai)", "gemini,openai", "openai", true},
		{"non-member of multi set", "gemini,openai", "anthropic", false},
		{"whitespace + case tolerant", " Gemini , OpenAI ", "gemini", true},
		{"empty platform never matches", "gemini", "", false},
		{"platform case-insensitive match", "gemini", "GEMINI", true},
		// post-pivot "*" all-platforms wildcard (default).
		{"wildcard '*' matches gemini", "*", "gemini", true},
		{"wildcard '*' matches anthropic", "*", "anthropic", true},
		{"wildcard '*' matches newapi", "*", "newapi", true},
		{"wildcard '*' in a list matches any member-or-not", "gemini,*", "anthropic", true},
		{"wildcard '*' still needs a non-empty platform", "*", "", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			repo := newGateRepoStub()
			if tc.enabledSet != "" {
				repo.values[SettingKeyPricedServingGateEnabled] = tc.enabledSet
			}
			svc := NewSettingService(repo, &config.Config{})
			require.Equal(t, tc.want, svc.IsPricedServingGateEnabled(ctx, tc.platform))
		})
	}
}

func TestIsPricedServingGateEnabled_NilReceiverSafe(t *testing.T) {
	var svc *SettingService
	require.False(t, svc.IsPricedServingGateEnabled(context.Background(), "gemini"),
		"nil receiver must fail-open-toward-off (no panic)")
}

// TestPricedServingGate_ColdStartDefaultIsAll pins the post-pivot default: a fresh DB enables the
// gate for ALL platforms ("*"). Safe because family floors mean floored platforms (claude/gpt/
// gemini) never reject — only no-floor multi-vendor ids reject (the backstop).
func TestPricedServingGate_ColdStartDefaultIsAll(t *testing.T) {
	defaults := map[string]string{}
	tkMergeDefaultColdStartSettings(defaults)
	require.Equal(t, "*", defaults[SettingKeyPricedServingGateEnabled],
		"post-pivot default enabled set is '*' (all platforms; family floors prevent floored-platform mass-404)")
}

// TestPricedServingGate_SystemSettingsRoundTrip exercises the admin PUT→GET
// round-trip: a value written through tkAppendColdStartSettingUpdates is read
// back identically by tkApplyColdStartParsed, with the expected membership.
func TestPricedServingGate_SystemSettingsRoundTrip(t *testing.T) {
	ctx := context.Background()

	// 1. PUT: admin sets the enabled set to {gemini, openai}.
	svc := &SettingService{}
	updates := map[string]string{}
	svc.tkAppendColdStartSettingUpdates(updates, &SystemSettings{
		AutoGenerateDefaultTokenName: "trial",
		PricedServingGateEnabled:     "gemini, openai",
	})
	require.Equal(t, "gemini, openai", updates[SettingKeyPricedServingGateEnabled],
		"append must persist the set string verbatim (trimmed)")

	// 2. GET: parse the stored value back into a SystemSettings view.
	parsed := &SystemSettings{}
	tkApplyColdStartParsed(map[string]string{
		SettingKeyPricedServingGateEnabled: updates[SettingKeyPricedServingGateEnabled],
	}, parsed)
	require.Equal(t, "gemini, openai", parsed.PricedServingGateEnabled,
		"admin GET must read back exactly what was PUT")

	// 3. Membership derived from the stored value: gemini/openai in, anthropic out.
	repo := newGateRepoStub()
	repo.values[SettingKeyPricedServingGateEnabled] = parsed.PricedServingGateEnabled
	store := NewSettingService(repo, &config.Config{})
	require.True(t, store.IsPricedServingGateEnabled(ctx, "gemini"))
	require.True(t, store.IsPricedServingGateEnabled(ctx, "openai"))
	require.False(t, store.IsPricedServingGateEnabled(ctx, "anthropic"))
}

// TestPricedServingGate_EmptySetRollsBack pins the rollback path: clearing the
// set (empty string) disables the gate for every platform.
func TestPricedServingGate_EmptySetRollsBack(t *testing.T) {
	ctx := context.Background()
	svc := &SettingService{}
	updates := map[string]string{}
	svc.tkAppendColdStartSettingUpdates(updates, &SystemSettings{
		AutoGenerateDefaultTokenName: "trial",
		PricedServingGateEnabled:     "",
	})
	require.Equal(t, "", updates[SettingKeyPricedServingGateEnabled])

	repo := newGateRepoStub()
	repo.values[SettingKeyPricedServingGateEnabled] = ""
	store := NewSettingService(repo, &config.Config{})
	require.False(t, store.IsPricedServingGateEnabled(ctx, "gemini"),
		"empty set must disable the gate everywhere (rollback)")
}
