// Code generated by go run ./cmd/gpt-image-sizes-ssot; DO NOT EDIT.
// Owner: backend/internal/service/openai_images_aspect_ratio_tk.go (openAIImagesKnownSizeTable).

export const GPT_IMAGE_SIZES: { ratio: string; value: string }[] = [
  { ratio: "1:1", value: "1024x1024" },
  { ratio: "3:2", value: "1536x1024" },
  { ratio: "2:3", value: "1024x1536" },
  { ratio: "16:9", value: "2048x1152" },
  { ratio: "9:16", value: "1152x2048" },
]
