#!/usr/bin/env python3
"""
check-cc-version-sync.py — keep the Claude Code CLI version string in lockstep
across every place that carries it, with a single source of truth.

Source of truth (the ONE field a cc patch bump should edit):
  deploy/aws/stage0/anthropic-http-mimicry-baselines.json  ->  cc_version

This is the value `manage-anthropic-config.py sync-runtime` pushes to the live
fleet, so it is the authoritative cc version. Every other copy must agree with
it. Before this guard a cc bump (e.g. 2.1.158 -> 2.1.159, PR #482) required
hand-editing ~10 files and 5 of those edits were wrong — dead snapshots and
comments drifted because nothing mechanically checked them.

Every derived copy is AUTO-REGENERATED by --write, so a cc bump only hand-edits
cc_version in the source JSON. Note on go:embed: the Go compile defaults cannot
*derive* the value at runtime (go:embed cannot reach deploy/ from the backend
module, and they are the last-resort defaults a brand-new deploy boots with) —
but that constraint is about runtime derivation, NOT about edit-time rewriting.
--write rewrites them in place with the same anchored-regex subn technique used
for the dead snapshots, which needs no embed. check mode still runs in preflight
/ CI, so a manual edit that drifts (or a forgotten --write) is still caught.

1. Go compile-time fallback defaults — parsed, compared, and AUTO-REWRITTEN by
   --write (anchored regex subn; values are reviewed in the commit diff):
     - backend/internal/pkg/claude/constants.go
         CLICurrentVersion             = "X.Y.Z"
         DefaultHeaders["User-Agent"]  = "claude-cli/X.Y.Z (external, cli)"
     - backend/internal/service/identity_service.go
         defaultFingerprint.UserAgent  = "claude-cli/X.Y.Z (external, cli)"
     - backend/internal/service/identity_service_tk_canonical_http.go
         DefaultClaudeCodeUserAgentVersion = "X.Y.Z"

2. Pure dead snapshots — compared, and AUTO-REGENERATED with --write:
     - deploy/aws/stage0/tk_canonical_cc_oauth.json   observed.user_agent
     - ops/stage0/smoke_lib.sh                        smoke_default_claude_user_agent default

3. Embedded go:embed mirror — byte-compared to the source JSON, and AUTO-COPIED
   by --write. This copy is LOAD-BEARING, not a dead snapshot: the per-node
   config reconciler (EnsureClaudeCodeMimicryBaseline) self-heals the live
   settings.claude_code_user_agent_version toward it, so a stale mirror would
   actively fight sync-runtime and roll the fleet UA back after a deploy.
   Before this entry the mirror was hand-cp'd on every bump (PR #579, #593) —
   the same forgotten-copy failure mode this guard exists to kill:
     - backend/internal/baseline/anthropic-http-mimicry-baselines.json

Exit codes:
  0  — every copy agrees with cc_version.
  1  — drift detected (some copy != cc_version).
  2  — file missing, parse failure, or required symbol not found.

Usage:
  python3 scripts/sentinels/check-cc-version-sync.py            # check, verbose
  python3 scripts/sentinels/check-cc-version-sync.py --quiet    # check, print only on failure
  python3 scripts/sentinels/check-cc-version-sync.py --json     # machine-readable
  python3 scripts/sentinels/check-cc-version-sync.py --write    # regenerate ALL copies (Go defaults + dead snapshots) from source of truth
  python3 scripts/sentinels/check-cc-version-sync.py --selftest # run built-in fixture self-test

cc bump workflow (see tokenkey-cc-fingerprint-alignment skill):
  1. edit cc_version in anthropic-http-mimicry-baselines.json  (the ONE hand-edit)
  2. run this script with --write  (regenerates all 7 copies: 4 Go defaults + 2 dead snapshots + embedded mirror)
  3. re-run this script (--check)  — must exit 0; preflight enforces it
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOURCE_JSON = REPO_ROOT / "deploy" / "aws" / "stage0" / "anthropic-http-mimicry-baselines.json"

CONSTANTS_GO = REPO_ROOT / "backend" / "internal" / "pkg" / "claude" / "constants.go"
IDENTITY_GO = REPO_ROOT / "backend" / "internal" / "service" / "identity_service.go"
CANONICAL_HTTP_GO = (
    REPO_ROOT / "backend" / "internal" / "service" / "identity_service_tk_canonical_http.go"
)
CANONICAL_TLS_JSON = REPO_ROOT / "deploy" / "aws" / "stage0" / "tk_canonical_cc_oauth.json"
SMOKE_LIB_SH = REPO_ROOT / "ops" / "stage0" / "smoke_lib.sh"
EMBEDDED_JSON = (
    REPO_ROOT / "backend" / "internal" / "baseline" / "anthropic-http-mimicry-baselines.json"
)

SEMVER_RE = re.compile(r"\d+\.\d+\.\d+")

# Each parsed copy: one regex with a single capture group around the bare semver
# (so the field name stays anchored in the pattern — no column-number reads).
# label -> (file, compiled regex). The regex MUST capture exactly the X.Y.Z.
_PARSE_TARGETS = {
    "constants.go CLICurrentVersion": (
        CONSTANTS_GO,
        re.compile(r'const\s+CLICurrentVersion\s*=\s*"(\d+\.\d+\.\d+)"'),
    ),
    'constants.go DefaultHeaders["User-Agent"]': (
        CONSTANTS_GO,
        re.compile(r'"User-Agent":\s*"claude-cli/(\d+\.\d+\.\d+) \(external, cli\)"'),
    ),
    "identity_service.go defaultFingerprint.UserAgent": (
        IDENTITY_GO,
        re.compile(r'UserAgent:\s*"claude-cli/(\d+\.\d+\.\d+) \(external, cli\)"'),
    ),
    "identity_service_tk_canonical_http.go DefaultClaudeCodeUserAgentVersion": (
        CANONICAL_HTTP_GO,
        re.compile(r'DefaultClaudeCodeUserAgentVersion\s*=\s*"(\d+\.\d+\.\d+)"'),
    ),
}

# Dead snapshots: (file, parse regex, rewrite-template builder). The builder
# takes the new version and returns the full replacement line text. The parse
# regex captures the current semver for comparison.
_SMOKE_RE = re.compile(
    r'(printf \'%s\' "\$\{TK_SMOKE_CLAUDE_USER_AGENT:-claude-cli/)(\d+\.\d+\.\d+)( \(external, cli\)\}")'
)
_OBSERVED_UA_RE = re.compile(
    r'("user_agent":\s*"claude-cli/)(\d+\.\d+\.\d+)( \(external, cli\)")'
)


class CheckError(Exception):
    pass


def _read(path: Path) -> str:
    if not path.is_file():
        raise CheckError(f"file not found: {path.relative_to(REPO_ROOT)}")
    return path.read_text(encoding="utf-8")


def load_source_version(source_json: Path = SOURCE_JSON) -> str:
    text = _read(source_json)
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise CheckError(f"{source_json.relative_to(REPO_ROOT)} parse error: {exc}") from exc
    cc = data.get("cc_version")
    if not isinstance(cc, str) or not SEMVER_RE.fullmatch(cc.strip()):
        raise CheckError(
            f"{source_json.relative_to(REPO_ROOT)} cc_version missing or not X.Y.Z: {cc!r}"
        )
    return cc.strip()


def parse_copy(label: str, path: Path, regex: re.Pattern[str]) -> str:
    m = regex.search(_read(path))
    if not m:
        raise CheckError(
            f"{label}: pattern not found in {path.relative_to(REPO_ROOT)} "
            "(symbol renamed or reformatted? update check-cc-version-sync.py)"
        )
    return m.group(1)


def _parse_dead(label: str, path: Path, regex: re.Pattern[str], group: int) -> str:
    m = regex.search(_read(path))
    if not m:
        raise CheckError(
            f"{label}: pattern not found in {path.relative_to(REPO_ROOT)} "
            "(reformatted? update check-cc-version-sync.py)"
        )
    return m.group(group)


def gather(
    expected: str,
    *,
    source_json: Path = SOURCE_JSON,
    parse_targets: dict[str, tuple[Path, re.Pattern[str]]] = _PARSE_TARGETS,
    smoke_path: Path = SMOKE_LIB_SH,
    canonical_tls_path: Path = CANONICAL_TLS_JSON,
    embedded_path: Path = EMBEDDED_JSON,
) -> list[dict[str, object]]:
    findings: list[dict[str, object]] = []
    for label, (path, regex) in parse_targets.items():
        found = parse_copy(label, path, regex)
        findings.append(
            {"label": label, "kind": "go-default", "found": found, "ok": found == expected}
        )
    smoke_found = _parse_dead(
        "smoke_lib.sh smoke_default_claude_user_agent", smoke_path, _SMOKE_RE, 2
    )
    findings.append(
        {"label": "smoke_lib.sh smoke_default_claude_user_agent", "kind": "dead",
         "found": smoke_found, "ok": smoke_found == expected}
    )
    observed_found = _parse_dead(
        "tk_canonical_cc_oauth.json observed.user_agent", canonical_tls_path, _OBSERVED_UA_RE, 2
    )
    findings.append(
        {"label": "tk_canonical_cc_oauth.json observed.user_agent", "kind": "dead",
         "found": observed_found, "ok": observed_found == expected}
    )
    # Embedded go:embed mirror: must be byte-identical to the source JSON (it
    # mirrors the WHOLE document — beta lists included, not just cc_version).
    embedded_cc = load_source_version(embedded_path)
    embedded_ok = _read(embedded_path) == _read(source_json)
    embedded_found = embedded_cc
    if not embedded_ok and embedded_cc == expected:
        # cc_version agrees but bytes differ — beta lists (or formatting) drifted.
        embedded_found = f"{embedded_cc} (same cc_version, bytes differ — beta lists drifted?)"
    findings.append(
        {"label": "backend/internal/baseline mirror (byte-identical)", "kind": "embedded-mirror",
         "found": embedded_found, "ok": embedded_ok}
    )
    return findings


def _rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def write_dead_snapshots(
    expected: str,
    *,
    smoke_path: Path = SMOKE_LIB_SH,
    canonical_tls_path: Path = CANONICAL_TLS_JSON,
) -> list[str]:
    """Rewrite the dead snapshots to `expected`. Returns list of changed files."""
    changed: list[str] = []

    smoke_text = _read(smoke_path)
    new_smoke, n = _SMOKE_RE.subn(lambda m: m.group(1) + expected + m.group(3), smoke_text)
    if n == 0:
        raise CheckError(f"smoke_lib.sh: nothing to rewrite (pattern not found)")
    if new_smoke != smoke_text:
        smoke_path.write_text(new_smoke, encoding="utf-8")
        changed.append(_rel(smoke_path))

    tls_text = _read(canonical_tls_path)
    new_tls, n = _OBSERVED_UA_RE.subn(lambda m: m.group(1) + expected + m.group(3), tls_text)
    if n == 0:
        raise CheckError(f"tk_canonical_cc_oauth.json: nothing to rewrite (pattern not found)")
    if new_tls != tls_text:
        canonical_tls_path.write_text(new_tls, encoding="utf-8")
        changed.append(_rel(canonical_tls_path))

    return changed


def write_embedded_mirror(
    *,
    source_json: Path = SOURCE_JSON,
    embedded_path: Path = EMBEDDED_JSON,
) -> list[str]:
    """Byte-copy the source JSON into the go:embed mirror. Returns changed files."""
    src_text = _read(source_json)
    if not embedded_path.is_file():
        raise CheckError(f"file not found: {_rel(embedded_path)}")
    if embedded_path.read_text(encoding="utf-8") != src_text:
        embedded_path.write_text(src_text, encoding="utf-8")
        return [_rel(embedded_path)]
    return []


def write_go_defaults(
    expected: str,
    *,
    parse_targets: dict[str, tuple[Path, re.Pattern[str]]] = _PARSE_TARGETS,
) -> list[str]:
    """Rewrite the Go compile-default version literals to `expected` in place.

    Reuses each target's anchored parse regex and replaces only the captured
    version within the matched span (m.group(0)), so an unrelated version-like
    string elsewhere in the same file is untouched. go:embed is irrelevant here:
    this is an edit-time rewrite of source text, not a runtime derivation.
    Returns the list of changed files.
    """
    # Group regexes by file so a file carrying several targets (constants.go has
    # two) is read once, rewritten for every target, and written once.
    by_path: dict[Path, list[re.Pattern[str]]] = {}
    for _label, (path, regex) in parse_targets.items():
        by_path.setdefault(path, []).append(regex)

    changed: list[str] = []
    for path, regexes in by_path.items():
        text = _read(path)
        new_text = text
        for regex in regexes:
            new_text, n = regex.subn(
                lambda m: m.group(0).replace(m.group(1), expected), new_text
            )
            if n == 0:
                raise CheckError(
                    f"{_rel(path)}: nothing to rewrite (pattern not found; "
                    "symbol renamed or reformatted? update check-cc-version-sync.py)"
                )
        if new_text != text:
            path.write_text(new_text, encoding="utf-8")
            changed.append(_rel(path))
    return changed


def run_check(args: argparse.Namespace) -> int:
    expected = load_source_version()
    findings = gather(expected)
    drift = [f for f in findings if not f["ok"]]

    if args.json:
        print(json.dumps(
            {"expected": expected, "ok": not drift, "findings": findings},
            indent=2, sort_keys=True,
        ))
        return 1 if drift else 0

    if not drift:
        if not args.quiet:
            print(
                f"OK: cc_version={expected} consistent across "
                f"{len(findings)} copies (source: {SOURCE_JSON.relative_to(REPO_ROOT)})"
            )
        return 0

    print(
        f"FAIL: cc version DRIFT — source of truth "
        f"{SOURCE_JSON.relative_to(REPO_ROOT)} cc_version={expected}",
        file=sys.stderr,
    )
    for f in drift:
        print(f"  {f['label']}: found {f['found']} != {expected}", file=sys.stderr)
    print(
        "Fix all copies: python3 scripts/sentinels/check-cc-version-sync.py --write",
        file=sys.stderr,
    )
    return 1


def run_write(args: argparse.Namespace) -> int:
    expected = load_source_version()
    changed = write_dead_snapshots(expected) + write_go_defaults(expected) + write_embedded_mirror()
    if changed:
        for c in sorted(set(changed)):
            print(f"wrote {c} -> cc_version={expected}")
    else:
        print(f"no change: all copies already at cc_version={expected}")
    # Confirm every copy is consistent after the rewrite.
    findings = gather(expected)
    drift = [f for f in findings if not f["ok"]]
    if drift:
        print("NOTE: copies still drift after --write:", file=sys.stderr)
        for f in drift:
            print(f"  {f['label']}: {f['found']} != {expected}", file=sys.stderr)
        return 1
    return 0


# ---------------------------------------------------------------------------
# Built-in self-test: build a throwaway fixture tree, prove check + write.
# Runs alongside preflight so the guard's own logic stays honest.
# ---------------------------------------------------------------------------
def run_selftest() -> int:
    failures: list[str] = []

    def expect(cond: bool, msg: str) -> None:
        if not cond:
            failures.append(msg)

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        src = root / "src.json"
        smoke = root / "smoke_lib.sh"
        tls = root / "tk.json"
        go_const = root / "constants.go"
        embedded = root / "embedded.json"

        src.write_text(json.dumps({"schema_version": 1, "cc_version": "9.9.9"}), encoding="utf-8")
        # Embedded mirror starts stale (old version + different bytes).
        embedded.write_text(
            json.dumps({"schema_version": 1, "cc_version": "1.0.0"}), encoding="utf-8"
        )
        smoke.write_text(
            'printf \'%s\' "${TK_SMOKE_CLAUDE_USER_AGENT:-claude-cli/1.0.0 (external, cli)}"\n',
            encoding="utf-8",
        )
        tls.write_text(
            json.dumps({"observed": {"user_agent": "claude-cli/1.0.0 (external, cli)"}}, indent=2),
            encoding="utf-8",
        )
        # Two Go targets in ONE file, to exercise the read-once/rewrite-all path.
        go_const.write_text(
            'const CLICurrentVersion = "1.0.0"\n'
            'var DefaultHeaders = map[string]string{\n'
            '\t"User-Agent": "claude-cli/1.0.0 (external, cli)",\n'
            '}\n',
            encoding="utf-8",
        )

        expected = load_source_version(src)
        expect(expected == "9.9.9", f"source version parse: got {expected!r}")

        targets = {
            "constants.go CLICurrentVersion": (
                go_const,
                re.compile(r'const\s+CLICurrentVersion\s*=\s*"(\d+\.\d+\.\d+)"'),
            ),
            'constants.go DefaultHeaders["User-Agent"]': (
                go_const,
                re.compile(r'"User-Agent":\s*"claude-cli/(\d+\.\d+\.\d+) \(external, cli\)"'),
            ),
        }

        # before write: drift expected (smoke/tls/go/embedded all 1.0.0 != 9.9.9)
        findings = gather(
            expected, source_json=src, parse_targets=targets,
            smoke_path=smoke, canonical_tls_path=tls, embedded_path=embedded,
        )
        expect(all(not f["ok"] for f in findings), "pre-write: all copies should drift")

        # --write regenerates the dead snapshots, rewrites the Go defaults,
        # AND byte-copies the embedded mirror
        changed_dead = write_dead_snapshots(expected, smoke_path=smoke, canonical_tls_path=tls)
        expect(len(changed_dead) == 2, f"dead write should change 2 files, got {changed_dead}")
        changed_go = write_go_defaults(expected, parse_targets=targets)
        expect(len(changed_go) == 1, f"go write should change the one file once, got {changed_go}")
        changed_embedded = write_embedded_mirror(source_json=src, embedded_path=embedded)
        expect(
            len(changed_embedded) == 1,
            f"embedded write should change the mirror, got {changed_embedded}",
        )
        expect(
            embedded.read_text(encoding="utf-8") == src.read_text(encoding="utf-8"),
            "embedded mirror must be byte-identical to source after write",
        )

        findings = gather(
            expected, source_json=src, parse_targets=targets,
            smoke_path=smoke, canonical_tls_path=tls, embedded_path=embedded,
        )
        expect(all(f["ok"] for f in findings), "post-write: all copies (dead + go + embedded) should match")

        # idempotent: a second --write touches nothing
        again = (
            write_dead_snapshots(expected, smoke_path=smoke, canonical_tls_path=tls)
            + write_go_defaults(expected, parse_targets=targets)
            + write_embedded_mirror(source_json=src, embedded_path=embedded)
        )
        expect(again == [], f"second write should be a no-op, got {again}")

        # byte-only drift: source beta list edited, cc_version unchanged —
        # the mirror must still be flagged (and the message must say why).
        src.write_text(
            json.dumps({"schema_version": 1, "cc_version": "9.9.9", "haiku": ["new-beta"]}),
            encoding="utf-8",
        )
        findings = gather(
            expected, source_json=src, parse_targets=targets,
            smoke_path=smoke, canonical_tls_path=tls, embedded_path=embedded,
        )
        mirror = next(f for f in findings if f["kind"] == "embedded-mirror")
        expect(not mirror["ok"], "byte-only drift (same cc_version) must be caught")
        expect("bytes differ" in str(mirror["found"]), f"drift message should explain bytes differ, got {mirror['found']!r}")
        changed_embedded = write_embedded_mirror(source_json=src, embedded_path=embedded)
        expect(len(changed_embedded) == 1, "write must heal byte-only drift")
        expect(
            embedded.read_text(encoding="utf-8") == src.read_text(encoding="utf-8"),
            "embedded mirror must be byte-identical after byte-only heal",
        )

    if failures:
        print("SELFTEST FAIL:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print("ok: check-cc-version-sync self-test passed")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="cc version single-source guard")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate dead snapshots from cc_version")
    mode.add_argument("--selftest", action="store_true", help="run built-in fixture self-test")
    parser.add_argument("--quiet", action="store_true", help="check mode: print only on failure")
    parser.add_argument("--json", action="store_true", help="check mode: machine-readable report")
    args = parser.parse_args()

    if args.json and args.quiet:
        print("FATAL: --json and --quiet are mutually exclusive", file=sys.stderr)
        return 2

    try:
        if args.selftest:
            return run_selftest()
        if args.write:
            return run_write(args)
        return run_check(args)
    except CheckError as exc:
        print(f"FATAL: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
