#!/usr/bin/env bash
# scripts/edge-ip-status.sh — Snapshot the live edge EIP state per target.
#
# Reads deploy/aws/stage0/edge-targets.json and queries AWS for each target's
# CFN stack + EIP. Reads deploy/aws/stage0/edge-polluted-ips.json for the
# permanent exclusion list. Outputs Markdown tables suitable for pasting into
# § 1 "Active edge EIPs" and § 2 "Permanently excluded IPs" of
# docs/deploy/tokenkey-edge-ip-history.md.
#
# Usage:
#   scripts/edge-ip-status.sh             # print markdown tables to stdout
#   scripts/edge-ip-status.sh --json      # raw JSON for downstream tooling
#   scripts/edge-ip-status.sh --check     # exit non-zero if doc tables drifted
#                                           from live state; gracefully skipped
#                                           (exit 0) when AWS credentials are
#                                           unavailable so preflight stays
#                                           usable on dev laptops without AWS.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MATRIX="${REPO_ROOT}/deploy/aws/stage0/edge-targets.json"
POLLUTED="${REPO_ROOT}/deploy/aws/stage0/edge-polluted-ips.json"
DOC="${REPO_ROOT}/docs/deploy/tokenkey-edge-ip-history.md"
MODE="${1:---markdown}"

for f in "$MATRIX" "$POLLUTED"; do
  if [ ! -f "$f" ]; then
    echo "missing $f" >&2
    exit 1
  fi
done

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

has_aws_creds() {
  command -v aws >/dev/null 2>&1 || return 1
  aws sts get-caller-identity --output text >/dev/null 2>&1
}

# --check is the only mode that *requires* live AWS state to be meaningful;
# without credentials a drift report would always be false-positive. Skip
# early so preflight on dev laptops without AWS configured stays green.
if [ "$MODE" = "--check" ] && ! has_aws_creds; then
  echo "edge-ip-status: skipped (no AWS credentials available; --check requires live AWS state)"
  exit 0
fi

active_json="[]"
while IFS=$'\t' read -r edge_id region stack deployable drift_locked domain; do
  stack_status="not-deployed"
  eip="—"
  alloc="—"
  instance="—"
  active_since="—"

  if aws cloudformation describe-stacks --region "$region" --stack-name "$stack" \
       --query 'Stacks[0].StackStatus' --output text >/dev/null 2>&1; then
    stack_status=$(aws cloudformation describe-stacks --region "$region" --stack-name "$stack" \
      --query 'Stacks[0].StackStatus' --output text)
    created=$(aws cloudformation describe-stacks --region "$region" --stack-name "$stack" \
      --query 'Stacks[0].CreationTime' --output text)
    active_since="${created:0:10}"

    instance=$(aws ec2 describe-instances --region "$region" \
      --filters "Name=tag:aws:cloudformation:stack-name,Values=$stack" \
                "Name=instance-state-name,Values=running,stopped" \
      --query 'Reservations[0].Instances[0].InstanceId' --output text 2>/dev/null || echo "—")

    if [ "$instance" != "—" ] && [ "$instance" != "None" ]; then
      addr=$(aws ec2 describe-addresses --region "$region" \
        --filters "Name=instance-id,Values=$instance" \
        --query 'Addresses[0].{IP:PublicIp,Alloc:AllocationId}' --output json 2>/dev/null || echo '{}')
      eip=$(echo "$addr" | jq -r '.IP // "—"')
      alloc=$(echo "$addr" | jq -r '.Alloc // "—"')
    fi
  fi

  active_json=$(jq -c --arg edge "$edge_id" --arg region "$region" --arg stack "$stack" \
    --arg eip "$eip" --arg alloc "$alloc" --arg inst "$instance" \
    --arg since "$active_since" --arg domain "$domain" \
    --arg stack_status "$stack_status" \
    --argjson drift_locked "$drift_locked" \
    '. + [{edge:$edge,region:$region,stack:$stack,stack_status:$stack_status,eip:$eip,allocation:$alloc,instance:$inst,active_since:$since,domain:$domain,drift_locked:$drift_locked}]' \
    <<<"$active_json")
done < <(jq -r '.targets | to_entries[] | "\(.key)\t\(.value.region)\t\(.value.stack)\t\(.value.deployable)\t\(.value.drift_locked // false)\t\(.value.domain)"' "$MATRIX")

polluted_json=$(jq '.polluted' "$POLLUTED")

emit_active_block() {
  echo "<!-- BEGIN edge-ip-status:active (generated by scripts/edge-ip-status.sh, do not hand-edit) -->"
  echo "| Edge | Region | EIP | AllocationId | Active since | Instance | Notes |"
  echo "| --- | --- | --- | --- | --- | --- | --- |"
  jq -r '.[] |
    "| edge-\(.edge) | \(.region) | \(if .eip == "—" then "—" else "`\(.eip)`" end) | \(if .allocation == "—" then "—" else "`\(.allocation)`" end) | \(.active_since) | \(if .instance == "—" then "—" else "`\(.instance)`" end) | \(if .drift_locked then "⚠️ drift-locked" elif .stack_status == "not-deployed" then "stack not deployed" else "" end) |"' \
    <<<"$active_json"
  echo "<!-- END edge-ip-status:active -->"
}

emit_polluted_block() {
  echo "<!-- BEGIN edge-ip-status:polluted (generated from deploy/aws/stage0/edge-polluted-ips.json) -->"
  echo "| IP | Region | Retired on | Released on | Previously edge | Notes |"
  echo "| --- | --- | --- | --- | --- | --- |"
  jq -r '.[] | "| `\(.ip)` | \(.region) | \(.retired_on) | \(.released_on) | edge-\(.previous_edge) | \(.notes) |"' \
    <<<"$polluted_json"
  echo "<!-- END edge-ip-status:polluted -->"
}

emit_markdown() {
  local today
  today=$(date -u +%Y-%m-%d)
  emit_active_block
  echo
  echo "_Active table generated by \`scripts/edge-ip-status.sh\` on ${today}._"
  echo
  emit_polluted_block
  echo
  echo "_Polluted table sourced from \`deploy/aws/stage0/edge-polluted-ips.json\`._"
}

# Extract a single managed block (BEGIN tag … END tag) from the doc. The
# previous `--check` implementation used a single awk range that spanned both
# blocks and the prose between them, which made the comparison structurally
# impossible to satisfy. Per-block extraction keeps comparison narrow and
# precise; the prose between the two blocks is free-form and intentionally
# ignored by --check.
extract_block() {
  local tag="$1"
  awk -v begin="<!-- BEGIN edge-ip-status:${tag} " \
      -v end="<!-- END edge-ip-status:${tag} -->" '
    index($0, begin) == 1 { inside = 1 }
    inside { print }
    index($0, end) == 1 { inside = 0 }
  ' "$DOC"
}

case "$MODE" in
  --markdown)
    emit_markdown
    ;;
  --json)
    jq -nc --argjson active "$active_json" --argjson polluted "$polluted_json" \
      '{active:$active,polluted:$polluted}'
    ;;
  --check)
    if [ ! -f "$DOC" ]; then
      echo "missing $DOC" >&2
      exit 1
    fi
    drift=0
    for tag in active polluted; do
      if [ "$tag" = "active" ]; then
        expected=$(emit_active_block)
      else
        expected=$(emit_polluted_block)
      fi
      actual=$(extract_block "$tag")
      if [ -z "$actual" ]; then
        echo "edge-ip-status: $tag block missing from $DOC" >&2
        drift=1
        continue
      fi
      if [ "$expected" != "$actual" ]; then
        echo "edge-ip-status: $tag block in $DOC drifted from live state" >&2
        diff <(printf '%s\n' "$expected") <(printf '%s\n' "$actual") >&2 || true
        drift=1
      fi
    done
    if [ "$drift" -eq 0 ]; then
      echo "edge-ip-status: doc tables in sync with live state"
      exit 0
    fi
    exit 1
    ;;
  *)
    echo "usage: $0 [--markdown|--json|--check]" >&2
    exit 2
    ;;
esac
