#!/usr/bin/env python3
"""Unit tests for scripts/release-impact-files.sh — verify bucket classification
is deterministic and covers the documented paths. Uses fake git history in a
temp repo so the test does not depend on the real repo state.

stdlib-only.
"""
from __future__ import annotations

import json
import os
import pathlib
import shutil
import subprocess
import tempfile
import unittest

_SCRIPT = pathlib.Path(__file__).resolve().parent / "release-impact-files.sh"


def _scrubbed_env() -> dict:
    # When this test runs from a git pre-commit hook the parent process exports
    # GIT_DIR / GIT_INDEX_FILE / GIT_WORK_TREE pointing at the *outer* repo.
    # Subprocess git would then ignore cwd= and operate on the outer repo,
    # which both fails (the tmp repo has no commits yet) and is dangerous.
    env = dict(os.environ)
    for key in ("GIT_DIR", "GIT_INDEX_FILE", "GIT_WORK_TREE", "GIT_OBJECT_DIRECTORY", "GIT_COMMON_DIR"):
        env.pop(key, None)
    return env


def _run_git(cwd: pathlib.Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", *args], cwd=cwd, env=_scrubbed_env(),
        capture_output=True, text=True, check=True,
    )
    return proc.stdout


class ReleaseImpactFilesTest(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.repo = pathlib.Path(self._tmp.name) / "repo"
        self.repo.mkdir()
        _run_git(self.repo, "init", "-q", "-b", "main")
        _run_git(self.repo, "config", "user.email", "test@example.com")
        _run_git(self.repo, "config", "user.name", "Test")
        # Copy the script into the tmp repo so its REPO_ROOT calc lands here
        target_dir = self.repo / "scripts"
        target_dir.mkdir()
        shutil.copy(_SCRIPT, target_dir / "release-impact-files.sh")
        (target_dir / "release-impact-files.sh").chmod(0o755)
        # Commit a base state
        (self.repo / "README.md").write_text("base\n")
        _run_git(self.repo, "add", "-A")
        _run_git(self.repo, "commit", "-q", "-m", "base")
        self.base_sha = _run_git(self.repo, "rev-parse", "HEAD").strip()

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def _commit(self, files: dict[str, str], msg: str) -> str:
        for relpath, content in files.items():
            target = self.repo / relpath
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
        _run_git(self.repo, "add", "-A")
        _run_git(self.repo, "commit", "-q", "-m", msg)
        return _run_git(self.repo, "rev-parse", "HEAD").strip()

    def _classify(self, base: str, head: str) -> dict:
        proc = subprocess.run(
            ["bash", "scripts/release-impact-files.sh", base, head],
            cwd=self.repo, env=_scrubbed_env(),
            capture_output=True, text=True, check=True,
        )
        return json.loads(proc.stdout)

    def test_handler_service_repo_bucket_separation(self) -> None:
        head = self._commit({
            "backend/internal/handler/foo.go":     "package handler\n",
            "backend/internal/service/bar.go":     "package service\n",
            "backend/internal/repository/baz.go":  "package repository\n",
            "backend/internal/middleware/mw.go":   "package middleware\n",
        }, "add backend bits")
        out = self._classify(self.base_sha, head)
        self.assertEqual(out["buckets"]["backend_handler"], ["backend/internal/handler/foo.go"])
        self.assertEqual(out["buckets"]["backend_service"], ["backend/internal/service/bar.go"])
        self.assertEqual(out["buckets"]["backend_repository"], ["backend/internal/repository/baz.go"])
        self.assertEqual(out["buckets"]["backend_middleware"], ["backend/internal/middleware/mw.go"])
        self.assertEqual(out["totals"]["files_changed"], 4)

    def test_schema_vs_wire_gen(self) -> None:
        head = self._commit({
            "backend/ent/schema/user.go":     "// schema\n",
            "backend/migrations/099_x.sql":   "-- migration\n",
            "backend/cmd/server/wire_gen.go": "// generated\n",
            "backend/ent/account.go":         "// generated by ent\n",
        }, "schema/wire gen")
        out = self._classify(self.base_sha, head)
        self.assertEqual(set(out["buckets"]["backend_schema"]), {
            "backend/ent/schema/user.go", "backend/migrations/099_x.sql",
        })
        self.assertEqual(set(out["buckets"]["backend_wire_gen"]), {
            "backend/cmd/server/wire_gen.go", "backend/ent/account.go",
        })

    def test_sentinel_and_ci(self) -> None:
        head = self._commit({
            "scripts/sentinels/newapi.json":      "{}\n",
            ".github/workflows/release.yml":       "name: release\n",
        }, "sentinels + ci")
        out = self._classify(self.base_sha, head)
        self.assertEqual(out["buckets"]["sentinels"], ["scripts/sentinels/newapi.json"])
        self.assertEqual(out["buckets"]["ci_workflows"], [".github/workflows/release.yml"])

    def test_frontend_split(self) -> None:
        head = self._commit({
            "frontend/src/views/Foo.vue":         "<template/>",
            "frontend/src/components/Bar.vue":    "<template/>",
            "frontend/src/api/foo.ts":            "export {}",
            "frontend/src/stores/store.ts":       "export {}",
            "frontend/src/utils/helpers.ts":      "export {}",
        }, "frontend bits")
        out = self._classify(self.base_sha, head)
        self.assertEqual(set(out["buckets"]["frontend_views"]), {
            "frontend/src/views/Foo.vue", "frontend/src/components/Bar.vue",
        })
        self.assertEqual(out["buckets"]["frontend_api"], ["frontend/src/api/foo.ts"])
        self.assertEqual(out["buckets"]["frontend_stores"], ["frontend/src/stores/store.ts"])
        self.assertEqual(out["buckets"]["frontend_other"], ["frontend/src/utils/helpers.ts"])

    def test_deletions_surfaced(self) -> None:
        first = self._commit({
            "backend/internal/handler/old.go": "package handler\n",
        }, "add then delete")
        (self.repo / "backend/internal/handler/old.go").unlink()
        _run_git(self.repo, "add", "-A")
        _run_git(self.repo, "commit", "-q", "-m", "remove old handler")
        head = _run_git(self.repo, "rev-parse", "HEAD").strip()
        out = self._classify(first, head)
        deletions = [d["path"] for d in out["deleted"]]
        self.assertIn("backend/internal/handler/old.go", deletions)

    def test_deterministic_ordering(self) -> None:
        head = self._commit({
            "backend/internal/service/zzz.go": "package service\n",
            "backend/internal/service/aaa.go": "package service\n",
        }, "two service files")
        a = self._classify(self.base_sha, head)
        b = self._classify(self.base_sha, head)
        self.assertEqual(json.dumps(a, sort_keys=True), json.dumps(b, sort_keys=True))
        # Sorted lexicographically
        self.assertEqual(a["buckets"]["backend_service"], [
            "backend/internal/service/aaa.go",
            "backend/internal/service/zzz.go",
        ])


if __name__ == "__main__":
    unittest.main()
