// Code generated by ent, DO NOT EDIT.

package protocolendpointcapability

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the protocolendpointcapability type in the database.
	Label = "protocol_endpoint_capability"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCapabilityKey holds the string denoting the capability_key field in the database.
	FieldCapabilityKey = "capability_key"
	// FieldIdentity holds the string denoting the identity field in the database.
	FieldIdentity = "identity"
	// FieldSupportedProtocols holds the string denoting the supported_protocols field in the database.
	FieldSupportedProtocols = "supported_protocols"
	// FieldProbeEvidence holds the string denoting the probe_evidence field in the database.
	FieldProbeEvidence = "probe_evidence"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldLastProbedAt holds the string denoting the last_probed_at field in the database.
	FieldLastProbedAt = "last_probed_at"
	// FieldProbeLeaseOwner holds the string denoting the probe_lease_owner field in the database.
	FieldProbeLeaseOwner = "probe_lease_owner"
	// FieldProbeLeaseUntil holds the string denoting the probe_lease_until field in the database.
	FieldProbeLeaseUntil = "probe_lease_until"
	// FieldProbeGeneration holds the string denoting the probe_generation field in the database.
	FieldProbeGeneration = "probe_generation"
	// FieldIdentityConflict holds the string denoting the identity_conflict field in the database.
	FieldIdentityConflict = "identity_conflict"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// Table holds the table name of the protocolendpointcapability in the database.
	Table = "protocol_endpoint_capabilities"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "protocol_endpoint_capability_id"
)

// Columns holds all SQL columns for protocolendpointcapability fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCapabilityKey,
	FieldIdentity,
	FieldSupportedProtocols,
	FieldProbeEvidence,
	FieldRevision,
	FieldLastProbedAt,
	FieldProbeLeaseOwner,
	FieldProbeLeaseUntil,
	FieldProbeGeneration,
	FieldIdentityConflict,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CapabilityKeyValidator is a validator for the "capability_key" field. It is called by the builders before save.
	CapabilityKeyValidator func(string) error
	// DefaultSupportedProtocols holds the default value on creation for the "supported_protocols" field.
	DefaultSupportedProtocols func() []string
	// DefaultProbeEvidence holds the default value on creation for the "probe_evidence" field.
	DefaultProbeEvidence func() map[string]interface{}
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int64
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int64) error
	// DefaultProbeGeneration holds the default value on creation for the "probe_generation" field.
	DefaultProbeGeneration int64
	// ProbeGenerationValidator is a validator for the "probe_generation" field. It is called by the builders before save.
	ProbeGenerationValidator func(int64) error
	// DefaultIdentityConflict holds the default value on creation for the "identity_conflict" field.
	DefaultIdentityConflict bool
)

// OrderOption defines the ordering options for the ProtocolEndpointCapability queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCapabilityKey orders the results by the capability_key field.
func ByCapabilityKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapabilityKey, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByLastProbedAt orders the results by the last_probed_at field.
func ByLastProbedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbedAt, opts...).ToFunc()
}

// ByProbeLeaseOwner orders the results by the probe_lease_owner field.
func ByProbeLeaseOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeLeaseOwner, opts...).ToFunc()
}

// ByProbeLeaseUntil orders the results by the probe_lease_until field.
func ByProbeLeaseUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeLeaseUntil, opts...).ToFunc()
}

// ByProbeGeneration orders the results by the probe_generation field.
func ByProbeGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeGeneration, opts...).ToFunc()
}

// ByIdentityConflict orders the results by the identity_conflict field.
func ByIdentityConflict(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityConflict, opts...).ToFunc()
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
	)
}
